### ISSUE TITLE
500 edit radio

### ISSUE THREAD

**Issue by j2sdwebradio** [AzuraCast/AzuraCast#1224]
**Installation method**
Traditional

**Describe the bug**
When I want to edit the radio to change its name or description, the server issues a 500 error

**To Reproduce**
1. Go to dashboard
2. Click on Menu
3. Scroll down to admin
4. Click on station 
4. Click on edit

**Expected behavior**

**Relevant Logs**
0 /var/azuracast/www/vendor/pimple/pimple/src/Pimple/Container.php(114): Azura\DefaultServicesProvider->Azura\{closure}(Object(Azura\Container))
#1 /var/azuracast/www/vendor/azuracast/azuracore/src/Container.php(109): Pimple\Container->offsetGet('Redis')
#2 /var/azuracast/www/vendor/azuracast/azuracore/src/DefaultServicesProvider.php(151): Azura\Container->offsetGet('Redis')
#3 /var/azuracast/www/vendor/pimple/pimple/src/Pimple/Container.php(118): Azura\DefaultServicesProvider->Azura\{closure}(Object(Azura\Container))
#4 /var/azuracast/www/vendor/azuracast/azuracore/src/Container.php(109): Pimple\Container->offsetGet('Azura\\Cache')
#5 /var/azuracast/www/config/services.php(261): Azura\Container->offsetGet('Azura\\Cache')
#6 /var/azuracast/www/vendor/pimple/pimple/src/Pimple/Container.php(118): Azura\Container->{closure}(Object(Azura\Container))
#7 /var/azuracast/www/vendo in /var/azuracast/www/vendor/azuracast/azuracore/src/DefaultServicesProvider.php on line 391
[25-Feb-2019 15:32:41 Europe/Paris] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /var/azuracast/www/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/AbstractHydrator.php on line 320
[25-Feb-2019 15:35:44 Europe/Paris] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /var/azuracast/www/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php on line 2822
[25-Feb-2019 20:15:25 Europe/Paris] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/JsonArrayType.php on line 28
[26-Feb-2019 11:25:33 Europe/Paris] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /var/azuracast/www/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php on line 2822
[26-Feb-2019 11:57:34 Europe/Paris] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /var/azuracast/www/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/AbstractHydrator.php on line 314
[26-Feb-2019 12:09:53 Europe/Paris] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /var/azuracast/www/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/AbstractHydrator.php on line 314
[26-Feb-2019 12:13:28 Europe/Paris] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /var/azuracast/www/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php on line 2822
[26-Feb-2019 12:15:17 Europe/Paris] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /var/azuracast/www/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php on line 2822
[26-Feb-2019 12:26:30 Europe/Paris] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /var/azuracast/www/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php on line 2822
[26-Feb-2019 12:35:07 Europe/Paris] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/JsonArrayType.php on line 28
[26-Feb-2019 12:35:25 Europe/Paris] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /var/azuracast/www/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php on line 2822
[26-Feb-2019 12:36:50 Europe/Paris] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /var/azuracast/www/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php on line 2822
[26-Feb-2019 12:37:39 Europe/Paris] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /var/azuracast/www/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php on line 2822
[26-Feb-2019 16:40:10 Europe/Paris] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /var/azuracast/www/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php on line 2822
[27-Feb-2019 11:18:42 Europe/Paris] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /var/azuracast/www/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php on line 2822
[27-Feb-2019 11:36:52 Europe/Paris] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /var/azuracast/www/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php on line 2822
[27-Feb-2019 11:47:00 Europe/Paris] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /var/azuracast/www/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/AbstractHydrator.php on line 314

**Screenshots**
This page is not working. Can not process this request via azurcast.kipaza.com at the moment.
HTTP ERROR 500

**Device(s):**
 - Device: Chrome
 - OS: Windows 10
 - Browser: 
 - Version: 

**Additional context**

**Comment by Vaalyn** [comment]
I could replicate this issue with my stations and tracked back the issue to [this line](https://github.com/AzuraCast/azuracore/blob/master/src/Normalizer/DoctrineEntityNormalizer.php#L76) in the `DoctrineEntityNormalizer`. When the `$attribute` is set to `history` the `getAttributeValue()` method will fetch the complete station song history here. The `$deep` variable is set to `true` for this attribute.

**Comment by Vaalyn** [comment]
Fixed in #1243
