### ISSUE TITLE
Webinterface not working after update (E500)

### ISSUE THREAD

**Issue by MrSteelMiner** [AzuraCast/AzuraCast#1503]
**Using Ansible/Bare-metal (whatever the non-docker is called now) installation method**

**Host Operating System**

Ubuntu 18.04

**Describe the bug**

After updating, webinterface isn't available anymore (Error 500)

**Relevant Logs**

from php_errors.log
[03-May-2019 14:06:34 UTC] PHP Fatal error:  Uncaught Error: Class 'Redis' not found in /var/azuracast/www/vendor/azuracast/azuracore/src/DefaultServicesProvider.php:398
Stack trace:
#0 /var/azuracast/www/vendor/pimple/pimple/src/Pimple/Container.php(114): Azura\DefaultServicesProvider->Azura\{closure}(Object(Azura\Container))
#1 /var/azuracast/www/vendor/azuracast/azuracore/src/Container.php(109): Pimple\Container->offsetGet('Redis')
#2 /var/azuracast/www/vendor/azuracast/azuracore/src/DefaultServicesProvider.php(191): Azura\Container->offsetGet('Redis')
#3 /var/azuracast/www/vendor/pimple/pimple/src/Pimple/Container.php(118): Azura\DefaultServicesProvider->Azura\{closure}(Object(Azura\Container))
#4 /var/azuracast/www/vendor/azuracast/azuracore/src/Container.php(109): Pimple\Container->offsetGet('Doctrine\\Common...')
#5 /var/azuracast/www/vendor/azuracast/azuracore/src/DefaultServicesProvider.php(210): Azura\Container->offsetGet('Doctrine\\Common...')
#6 /var/azuracast/www/vendor/pimple/pimple/src/Pimple/Container.php(259): Azura\DefaultServicesProvi in /var/azuracast/www/vendor/azuracast/azuracore/src/DefaultServicesProvider.php on line 398

**Comment by MrSteelMiner** [comment]
Trying ./update.sh --full

**Comment by MrSteelMiner** [comment]
worked for me. 
If anyone has the same issue: update with './update.sh --full' and after that you have to reconfigure SSL-certificates in nginx-config (/etc/nginx/sites-available/00-azuracast) if you are using them.
