### ISSUE TITLE
Error 500 on non-existent pages and radio stream

### ISSUE THREAD

**Issue by LewisTehMinerz** [AzuraCast/AzuraCast#2004]
**Using Docker installation method**

Yes

**Host Operating System**

Ubuntu 19.04

**Describe the bug**

All non-existent pages return HTTP Error 500, as well as the radio stream.

**To Reproduce**

Go to https://radio.onepixel.dev/sdhkjf (obviously a non-existent page)

**Expected behavior**

A 404 page appears.

**Relevant Logs**

```
web_1       | Sep 24 17:46:38 d50e88b3ae3a php-fpm[66]: [WARNING] [pool www] child 3300 said into stderr: "[2019-09-24T17:46:38.562506+00:00] AzuraCast.WARNING: Not found. {"file":"/var/azuracast/www/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php","line":91,"code":404} []"
web_1       | 2019/09/24 17:46:38 [error] 73#73: *3940 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to a member function hasMessages() on null in /var/azuracast/www/templates/minimal.phtml:50
web_1       | Stack trace:
web_1       | #0 /var/azuracast/www/vendor/league/plates/src/Template/Template.php(153): include()
web_1       | #1 /var/azuracast/www/vendor/league/plates/src/Template/Template.php(160): League\Plates\Template\Template->render(NULL)
web_1       | #2 /var/azuracast/www/vendor/league/plates/src/Engine.php(277): League\Plates\Template\Template->render(NULL)
web_1       | #3 /var/azuracast/www/vendor/azuracast/azuracore/src/View.php(40): League\Plates\Engine->render('system/error_pa...', Array)
web_1       | #4 /var/azuracast/www/src/Http/ErrorHandler.php(74): Azura\View->renderToResponse(Object(App\Http\Response), 'system/error_pa...')
web_1       | #5 /var/azuracast/www/vendor/slim/slim/Slim/Handlers/ErrorHandler.php(154): App\Http\ErrorHandler->respond()
web_1       | #6 /var/azuracast/www/vendor/azuracast/azuracore/src/Http/ErrorHandler.php(60): Slim\Handlers\ErrorHandler->__invoke(Object(App\Http\ServerRequest), Object(Slim\Exception\HttpNotFoun" while reading response header from upstream, client: 172.22.0.1, server: localhost, request: "GET /error.mp3 HTTP/1.0", upstream: "fastcgi://127.0.0.1:9000", host: "radio.onepixel.dev"
web_1       | Sep 24 17:46:38 d50e88b3ae3a php-fpm[66]: [WARNING] [pool www] child 3300 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Uncaught Error: Call to a member function hasMessages() on null in /var/azuracast/www/templates/minimal.phtml:50"
web_1       | Sep 24 17:46:38 d50e88b3ae3a php-fpm[66]: [WARNING] [pool www] child 3300 said into stderr: "Stack trace:"
web_1       | Sep 24 17:46:38 d50e88b3ae3a php-fpm[66]: [WARNING] [pool www] child 3300 said into stderr: "#0 /var/azuracast/www/vendor/league/plates/src/Template/Template.php(153): include()"
web_1       | Sep 24 17:46:38 d50e88b3ae3a php-fpm[66]: [WARNING] [pool www] child 3300 said into stderr: "#1 /var/azuracast/www/vendor/league/plates/src/Template/Template.php(160): League\Plates\Template\Template->render(NULL)"
web_1       | Sep 24 17:46:38 d50e88b3ae3a php-fpm[66]: [WARNING] [pool www] child 3300 said into stderr: "#2 /var/azuracast/www/vendor/league/plates/src/Engine.php(277): League\Plates\Template\Template->render(NULL)"
web_1       | Sep 24 17:46:38 d50e88b3ae3a php-fpm[66]: [WARNING] [pool www] child 3300 said into stderr: "#3 /var/azuracast/www/vendor/azuracast/azuracore/src/View.php(40): League\Plates\Engine->render('system/error_pa...', Array)"
web_1       | Sep 24 17:46:38 d50e88b3ae3a php-fpm[66]: [WARNING] [pool www] child 3300 said into stderr: "#4 /var/azuracast/www/src/Http/ErrorHandler.php(74): Azura\View->renderToResponse(Object(App\Http\Response), 'system/error_pa...')"
web_1       | Sep 24 17:46:38 d50e88b3ae3a php-fpm[66]: [WARNING] [pool www] child 3300 said into stderr: "#5 /var/azuracast/www/vendor/slim/slim/Slim/Handlers/ErrorHandler.php(154): App\Http\ErrorHandler->respond()"
web_1       | Sep 24 17:46:38 d50e88b3ae3a php-fpm[66]: [WARNING] [pool www] child 3300 said into stderr: "#6 /var/azuracast/www/vendor/azuracast/azuracore/src/Http/ErrorHandler.php(60): Slim\Handlers\ErrorHandler->__invoke(Object(App\Http\ServerRequest), Object(Slim\Exception\Htt..."
```

**Screenshots**

![500 page shot](https://owo.whats-th.is/AXxWYSV.png)

**Device(s):**
 - Device: Desktop
 - OS: Windows
 - Browser: Chrome
 - Version: 77.0.3865.90

**Additional context**

I am running AzuraCast behind a reverse proxy (via nginx), maybe that could be the problem?

**Comment by SlvrEagle23** [comment]
@LewisTehMinerz Should be fixed now. Thanks for letting us know!
