### ISSUE TITLE
Couldn't Install - Followed all the steps stated, throws Traceback error - CentOS 7.5

### ISSUE THREAD

**Issue by MackPerfecto** [AzuraCast/AzuraCast#2203]
Docker is already installed! Continuing...
Traceback (most recent call last):
  File "/bin/docker-compose", line 5, in <module>
    from compose.cli.main import main
  File "/usr/lib/python2.7/site-packages/compose/cli/main.py", line 23, in <module>
    from ..bundle import get_image_digests
  File "/usr/lib/python2.7/site-packages/compose/bundle.py", line 12, in <module>
    from .config.serialize import denormalize_config
  File "/usr/lib/python2.7/site-packages/compose/config/__init__.py", line 6, in <module>
    from .config import ConfigurationError
  File "/usr/lib/python2.7/site-packages/compose/config/config.py", line 50, in <module>
    from .validation import match_named_volumes
  File "/usr/lib/python2.7/site-packages/compose/config/validation.py", line 12, in <module>
    from jsonschema import Draft4Validator
  File "/usr/lib/python2.7/site-packages/jsonschema/__init__.py", line 33, in <module>
    import importlib_metadata as metadata
  File "/usr/lib/python2.7/site-packages/importlib_metadata/__init__.py", line 9, in <module>
    import zipp
  File "/usr/lib/python2.7/site-packages/zipp.py", line 12, in <module>
    import more_itertools
  File "/usr/lib/python2.7/site-packages/more_itertools/__init__.py", line 1, in <module>
    from .more import *  # noqa
  File "/usr/lib/python2.7/site-packages/more_itertools/more.py", line 460
    yield from iterable
             ^
SyntaxError: invalid syntax
Docker Compose does not appear to be installed. Install Docker Compose now? [Y/n] Y
Traceback (most recent call last):
  File "/bin/docker-compose", line 5, in <module>
    from compose.cli.main import main
  File "/usr/lib/python2.7/site-packages/compose/cli/main.py", line 23, in <module>
    from ..bundle import get_image_digests
  File "/usr/lib/python2.7/site-packages/compose/bundle.py", line 12, in <module>
    from .config.serialize import denormalize_config
  File "/usr/lib/python2.7/site-packages/compose/config/__init__.py", line 6, in <module>
    from .config import ConfigurationError
  File "/usr/lib/python2.7/site-packages/compose/config/config.py", line 50, in <module>
    from .validation import match_named_volumes
  File "/usr/lib/python2.7/site-packages/compose/config/validation.py", line 12, in <module>
    from jsonschema import Draft4Validator
  File "/usr/lib/python2.7/site-packages/jsonschema/__init__.py", line 33, in <module>
    import importlib_metadata as metadata
  File "/usr/lib/python2.7/site-packages/importlib_metadata/__init__.py", line 9, in <module>
    import zipp
  File "/usr/lib/python2.7/site-packages/zipp.py", line 12, in <module>
    import more_itertools
  File "/usr/lib/python2.7/site-packages/more_itertools/__init__.py", line 1, in <module>
    from .more import *  # noqa
  File "/usr/lib/python2.7/site-packages/more_itertools/more.py", line 460
    yield from iterable
             ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/bin/docker-compose", line 5, in <module>
    from compose.cli.main import main
  File "/usr/lib/python2.7/site-packages/compose/cli/main.py", line 23, in <module>
    from ..bundle import get_image_digests
  File "/usr/lib/python2.7/site-packages/compose/bundle.py", line 12, in <module>
    from .config.serialize import denormalize_config
  File "/usr/lib/python2.7/site-packages/compose/config/__init__.py", line 6, in <module>
    from .config import ConfigurationError
  File "/usr/lib/python2.7/site-packages/compose/config/config.py", line 50, in <module>
    from .validation import match_named_volumes
  File "/usr/lib/python2.7/site-packages/compose/config/validation.py", line 12, in <module>
    from jsonschema import Draft4Validator
  File "/usr/lib/python2.7/site-packages/jsonschema/__init__.py", line 33, in <module>
    import importlib_metadata as metadata
  File "/usr/lib/python2.7/site-packages/importlib_metadata/__init__.py", line 9, in <module>
    import zipp
  File "/usr/lib/python2.7/site-packages/zipp.py", line 12, in <module>
    import more_itertools
  File "/usr/lib/python2.7/site-packages/more_itertools/__init__.py", line 1, in <module>
    from .more import *  # noqa
  File "/usr/lib/python2.7/site-packages/more_itertools/more.py", line 460
    yield from iterable
             ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/bin/docker-compose", line 5, in <module>
    from compose.cli.main import main
  File "/usr/lib/python2.7/site-packages/compose/cli/main.py", line 23, in <module>
    from ..bundle import get_image_digests
  File "/usr/lib/python2.7/site-packages/compose/bundle.py", line 12, in <module>
    from .config.serialize import denormalize_config
  File "/usr/lib/python2.7/site-packages/compose/config/__init__.py", line 6, in <module>
    from .config import ConfigurationError
  File "/usr/lib/python2.7/site-packages/compose/config/config.py", line 50, in <module>
    from .validation import match_named_volumes
  File "/usr/lib/python2.7/site-packages/compose/config/validation.py", line 12, in <module>
    from jsonschema import Draft4Validator
  File "/usr/lib/python2.7/site-packages/jsonschema/__init__.py", line 33, in <module>
    import importlib_metadata as metadata
  File "/usr/lib/python2.7/site-packages/importlib_metadata/__init__.py", line 9, in <module>
    import zipp
  File "/usr/lib/python2.7/site-packages/zipp.py", line 12, in <module>
    import more_itertools
  File "/usr/lib/python2.7/site-packages/more_itertools/__init__.py", line 1, in <module>
    from .more import *  # noqa
  File "/usr/lib/python2.7/site-packages/more_itertools/more.py", line 460
    yield from iterable
             ^
SyntaxError: invalid syntax

**Comment by SlvrEagle23** [comment]
@MackPerfecto This is definitely an issue with Docker Compose on your server OS, not AzuraCast itself.

What OS and version are you trying to install AzuraCast on?

**Comment by MackPerfecto** [comment]
Yeah, the issue was with Docker latest version... I'm running this on CentOS 7.4
`pip uninstall docker
pip uninstall docker-compose

pip install docker==2.3.0
pip install docker-compose==1.14.0
`

Installed the old version of docker using PIP and it worked... But I had to stop Apache and FTP in order to make this work which wasn't an optimal solution so I bought a droplet on Digital Ocean.

One more doubt
Flac file is not supported? I tried playing few Flac files and the song was running but the radio profile page kept saying "Stream Offline" but weirdly it was playing the songs I loaded.

Thanks.

**Comment by SlvrEagle23** [comment]
@MackPerfecto Please try to keep issues here on GitHub to "one issue per Issue", since we can't track progress of multiple issues easily.

I'm not quite sure why the latest Docker causes that problem, but you should definitely check Docker's GitHub repositories to see if they're aware of the problem already so they can publish a fix for newer versions.

**Comment by MackPerfecto** [comment]
Cool, Sorry about that. 

Okay, I'll check with Docker on this issue.

Thanks.
