### ISSUE TITLE
Error in log:  Uncaught TypeError: Return value of App\Entity\StationMedia::getItemForPlaylist()

### ISSUE THREAD

**Issue by yarik2720** [AzuraCast/AzuraCast#2307]
**Using Docker installation method**
Yes

**Host Operating System**
Ubuntu 16.04

**Relevant Logs**

```
web_1       | Fatal error: Uncaught TypeError: Return value of App\Entity\StationMedia::getItemForPlaylist() must be an instance of App\Entity\StationPlaylistMedia or null, bool returned in /var/azuracast/www/src/Entity/StationMedia.php:592
web_1       | Stack trace:
web_1       | #0 /var/azuracast/www/src/Radio/AutoDJ.php(319): App\Entity\StationMedia->getItemForPlaylist()
web_1       | #1 /var/azuracast/www/src/Radio/AutoDJ.php(295): App\Radio\AutoDJ->_playSongFromPlaylist()
web_1       | #2 /var/azuracast/www/vendor/azuracast/azuracore/src/DeferredCallable.php(45): App\Radio\AutoDJ->calculateNextSong()
web_1       | #3 /var/azuracast/www/vendor/symfony/event-dispatcher/EventDispatcher.php(251): Azura\DeferredCallable->__invoke()
web_1       | #4 /var/azuracast/www/vendor/symfony/event-dispatcher/EventDispatcher.php(73): Symfony\Component\EventDispatcher\EventDispatcher->callListeners()
web_1       | #5 /var/azuracast/www/src/Radio/AutoDJ.php(104): Symfony\Component\EventDispatcher\EventDispatcher->dispatch()
web_1       | #6 /var/azuracast/www/src/Sync/Task/NowPlaying.php(259): App\Radio\AutoDJ->getNextSong()
web_1       | #7 /var/azuracast/www/src/Sync/Ta in /var/azuracast/www/src/Entity/StationMedia.php on line 592
```

**Comment by SlvrEagle23** [comment]
@yarik2720 Should be fixed in latest update.
