### ISSUE TITLE
This page isn't working

### ISSUE THREAD

**Issue by IdkWhosThis** [AzuraCast/AzuraCast#2356]
**Using Docker installation method**

Yes

**Host Operating System**

Ubuntu 18.04

**Describe the bug**

Yesterday I installed AzuraCast, everything worked fine, but today I see "This page isn't working" (error 500) when accessing dashboard (thru my subdomain & server ip)

**Screenshots**

![Screenshot_2020-01-29-12-12-54-939_com android chrome](https://user-images.githubusercontent.com/39670563/73352110-b6ee0f00-4290-11ea-9460-b95e4d344b52.jpg)

**Device(s):**
 - Device: Mi9T & Desktop
 - OS: Android 10, Windiws 10
 - Browser: Chrome

**Comment by SlvrEagle23** [comment]
@IdkWhosThis Have you updated your installation since then?

You can see what may be causing the problem by logging into your server and checking the logs via:

```
cd /var/azuracast
docker-compose logs -f web
```

**Comment by IdkWhosThis** [comment]
Not updated. Trying to update it rn.

**Comment by IdkWhosThis** [comment]
Well.. working again after updating. Let this open please, I will monitor it if it will happen again tomorrow.

**Comment by IdkWhosThis** [comment]
So.. it happened again as I expected.
Here are logs from web
```
web_1       | 
web_1       | In AbstractMySQLDriver.php line 93:
web_1       |                                                                               
web_1       |   An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused  
web_1       |                                                                               
web_1       | 
web_1       | In PDOConnection.php line 31:
web_1       |                                              
web_1       |   SQLSTATE[HY000] [2002] Connection refused  
web_1       |                                              
web_1       | 
web_1       | In PDOConnection.php line 27:
web_1       |                                              
web_1       |   SQLSTATE[HY000] [2002] Connection refused  
web_1       |                                              
web_1       | 
web_1       | sync:run [<task>]
web_1       |
```

**Comment by IdkWhosThis** [comment]
@SlvrEagle23 I got full error rn

```
web_1       |   An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused
web_1       |
web_1       |
web_1       |
web_1       |   An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused
web_1       | In PDOConnection.php line 31:
web_1       |
web_1       |
web_1       | In PDOConnection.php line 31:
web_1       |
web_1       |   SQLSTATE[HY000] [2002] Connection refused
web_1       |
web_1       |
web_1       | In PDOConnection.php line 27:
web_1       |
web_1       |   SQLSTATE[HY000] [2002] Connection refused
web_1       |
web_1       |
web_1       | sync:run [<task>]
web_1       |
web_1       |
web_1       |   SQLSTATE[HY000] [2002] Connection refused
web_1       |
web_1       |
web_1       | In PDOConnection.php line 27:
web_1       |
web_1       |   SQLSTATE[HY000] [2002] Connection refused
web_1       |
web_1       |
web_1       | sync:run [<task>]
web_1       |
web_1       | 2020/01/30 14:01:15 [error] 54#54: *54753 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [2002] Connection refused in /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27
web_1       | Stack trace:
web_1       | #0 /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(27): PDO->__construct()
web_1       | #1 /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php(22): Doctrine\DBAL\Driver\PDOConnection->__construct()
web_1       | #2 /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(362): Doctrine\DBAL\Driver\PDOMySql\Driver->connect()
web_1       | #3 /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1443): Doctrine\DBAL\Connection->connect()
web_1       | #4 /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(890): Doctrine\DBAL\Connection->getWrappedConnection()
web_1       | #5 /var/azuracast/www/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Exec/SingleSelectExecutor.php(50): Doctrine\DBAL\Connection->executeQuery()
web_1       | #6 /var/azuracast/www/vendor/doctrine/or" while reading response header from upstream, client: 172.68.51.105, server: localhost, request: "GET /api/nowplaying/1?0 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "s1.cloudradio.cz", referrer: "https://cloudradio.cz/station"
web_1       | 2020/01/30 14:01:16 [error] 54#54: *54822 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [2002] Connection refused in /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27
web_1       | Stack trace:
web_1       | #0 /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(27): PDO->__construct()
web_1       | #1 /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php(22): Doctrine\DBAL\Driver\PDOConnection->__construct()
web_1       | #2 /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(362): Doctrine\DBAL\Driver\PDOMySql\Driver->connect()
web_1       | #3 /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1443): Doctrine\DBAL\Connection->connect()
web_1       | #4 /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(890): Doctrine\DBAL\Connection->getWrappedConnection()
web_1       | #5 /var/azuracast/www/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Exec/SingleSelectExecutor.php(50): Doctrine\DBAL\Connection->executeQuery()
web_1       | #6 /var/azuracast/www/vendor/doctrine/or" while reading response header from upstream, client: 172.68.51.105, server: localhost, request: "GET /api/nowplaying/1?0 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "s1.cloudradio.cz", referrer: "https://cloudradio.cz/station"
web_1       | 2020/01/30 14:01:17 [error] 54#54: *54264 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [2002] Connection refused in /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27
web_1       | Stack trace:
web_1       | #0 /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(27): PDO->__construct()
web_1       | #1 /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php(22): Doctrine\DBAL\Driver\PDOConnection->__construct()
web_1       | #2 /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(362): Doctrine\DBAL\Driver\PDOMySql\Driver->connect()
web_1       | #3 /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1443): Doctrine\DBAL\Connection->connect()
web_1       | #4 /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(890): Doctrine\DBAL\Connection->getWrappedConnection()
web_1       | #5 /var/azuracast/www/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Exec/SingleSelectExecutor.php(50): Doctrine\DBAL\Connection->executeQuery()
web_1       | #6 /var/azuracast/www/vendor/doctrine/or" while reading response header from upstream, client: 172.68.51.105, server: localhost, request: "GET /api/nowplaying/1?0 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "s1.cloudradio.cz", referrer: "https://cloudradio.cz/station"
web_1       | 2020/01/30 14:01:18 [error] 54#54: *54753 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [2002] Connection refused in /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27
web_1       | Stack trace:
web_1       | #0 /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(27): PDO->__construct()
web_1       | #1 /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php(22): Doctrine\DBAL\Driver\PDOConnection->__construct()
web_1       | #2 /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(362): Doctrine\DBAL\Driver\PDOMySql\Driver->connect()
web_1       | #3 /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1443): Doctrine\DBAL\Connection->connect()
web_1       | #4 /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(890): Doctrine\DBAL\Connection->getWrappedConnection()
web_1       | #5 /var/azuracast/www/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Exec/SingleSelectExecutor.php(50): Doctrine\DBAL\Connection->executeQuery()
web_1       | #6 /var/azuracast/www/vendor/doctrine/or" while reading response header from upstream, client: 172.68.51.105, server: localhost, request: "GET /api/nowplaying/1?0 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "s1.cloudradio.cz", referrer: "https://cloudradio.cz/station"
web_1       | 2020/01/30 14:01:19 [error] 54#54: *54264 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [2002] Connection refused in /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27
web_1       | Stack trace:
web_1       | #0 /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(27): PDO->__construct()
web_1       | #1 /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php(22): Doctrine\DBAL\Driver\PDOConnection->__construct()
web_1       | #2 /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(362): Doctrine\DBAL\Driver\PDOMySql\Driver->connect()
web_1       | #3 /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1443): Doctrine\DBAL\Connection->connect()
web_1       | #4 /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(890): Doctrine\DBAL\Connection->getWrappedConnection()
web_1       | #5 /var/azuracast/www/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Exec/SingleSelectExecutor.php(50): Doctrine\DBAL\Connection->executeQuery()
web_1       | #6 /var/azuracast/www/vendor/doctrine/or" while reading response header from upstream, client: 172.68.51.105, server: localhost, request: "GET /api/nowplaying/1?0 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "s1.cloudradio.cz", referrer: "https://cloudradio.cz/station"
web_1       | 2020/01/30 14:01:20 [error] 54#54: *54822 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [2002] Connection refused in /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27
web_1       | Stack trace:
web_1       | #0 /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(27): PDO->__construct()
web_1       | #1 /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php(22): Doctrine\DBAL\Driver\PDOConnection->__construct()
web_1       | #2 /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(362): Doctrine\DBAL\Driver\PDOMySql\Driver->connect()
web_1       | #3 /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1443): Doctrine\DBAL\Connection->connect()
web_1       | #4 /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(890): Doctrine\DBAL\Connection->getWrappedConnection()
web_1       | #5 /var/azuracast/www/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Exec/SingleSelectExecutor.php(50): Doctrine\DBAL\Connection->executeQuery()
web_1       | #6 /var/azuracast/www/vendor/doctrine/or" while reading response header from upstream, client: 172.68.51.105, server: localhost, request: "GET /api/nowplaying/1?0 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "s1.cloudradio.cz", referrer: "https://cloudradio.cz/station"
web_1       | 2020/01/30 14:01:21 [error] 54#54: *54264 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [2002] Connection refused in /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27
web_1       | Stack trace:
web_1       | #0 /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(27): PDO->__construct()
web_1       | #1 /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php(22): Doctrine\DBAL\Driver\PDOConnection->__construct()
web_1       | #2 /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(362): Doctrine\DBAL\Driver\PDOMySql\Driver->connect()
web_1       | #3 /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1443): Doctrine\DBAL\Connection->connect()
web_1       | #4 /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(890): Doctrine\DBAL\Connection->getWrappedConnection()
web_1       | #5 /var/azuracast/www/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Exec/SingleSelectExecutor.php(50): Doctrine\DBAL\Connection->executeQuery()
web_1       | #6 /var/azuracast/www/vendor/doctrine/or" while reading response header from upstream, client: 172.68.51.105, server: localhost, request: "GET /api/nowplaying/1?0 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "s1.cloudradio.cz", referrer: "https://cloudradio.cz/station"
web_1       | 2020/01/30 14:01:22 [error] 54#54: *54264 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [2002] Connection refused in /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27
web_1       | Stack trace:
web_1       | #0 /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(27): PDO->__construct()
web_1       | #1 /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php(22): Doctrine\DBAL\Driver\PDOConnection->__construct()
web_1       | #2 /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(362): Doctrine\DBAL\Driver\PDOMySql\Driver->connect()
web_1       | #3 /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1443): Doctrine\DBAL\Connection->connect()
web_1       | #4 /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(890): Doctrine\DBAL\Connection->getWrappedConnection()
web_1       | #5 /var/azuracast/www/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Exec/SingleSelectExecutor.php(50): Doctrine\DBAL\Connection->executeQuery()
web_1       | #6 /var/azuracast/www/vendor/doctrine/or" while reading response header from upstream, client: 172.68.51.105, server: localhost, request: "GET /api/nowplaying/1?0 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "s1.cloudradio.cz", referrer: "https://cloudradio.cz/station"
web_1       | 2020/01/30 14:01:23 [error] 54#54: *54822 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [2002] Connection refused in /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27
web_1       | Stack trace:
web_1       | #0 /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(27): PDO->__construct()
web_1       | #1 /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php(22): Doctrine\DBAL\Driver\PDOConnection->__construct()
web_1       | #2 /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(362): Doctrine\DBAL\Driver\PDOMySql\Driver->connect()
web_1       | #3 /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1443): Doctrine\DBAL\Connection->connect()
web_1       | #4 /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(890): Doctrine\DBAL\Connection->getWrappedConnection()
web_1       | #5 /var/azuracast/www/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Exec/SingleSelectExecutor.php(50): Doctrine\DBAL\Connection->executeQuery()
web_1       | #6 /var/azuracast/www/vendor/doctrine/or" while reading response header from upstream, client: 172.68.51.105, server: localhost, request: "GET /api/nowplaying/1?0 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "s1.cloudradio.cz", referrer: "https://cloudradio.cz/station"
web_1       |
web_1       | In AbstractMySQLDriver.php line 93:
```

**Comment by IdkWhosThis** [comment]
Well.. really thanks for helping... I had to reinstall my server from Ubuntu 18.04 to Ubuntu 16.04 a everything works fine now..
