### ISSUE TITLE
Invalid JSON response when deleting file through API

### ISSUE THREAD

**Issue by callumok2004** [AzuraCast/AzuraCast#2593]
```js
                    fetch("http://presenter.boun.cc/api/nowplaying/1").then(res => res.json())
                    .then(songInfo => {
                        fetch("http://presenter.boun.cc/api/station/1/file/" + songInfo.now_playing.song.id, {
                            method: "DELETE",
                            Authorization: `Bearer ${authToken}`
                        }).then(res => res.json())
                        .then(songDeleted => {
                            fetch(`http://presenter.boun.cc/api/station/1/backend/skip`, {
                                method: "POST",
                                headers: {
                                    Authorization: `Bearer ${authToken}`
                                }
                            }).then(res => res.json())
                            .then(json => {
                                res.json(songDeleted)
                            })
                        })
                    })
```
```
(node:1805) UnhandledPromiseRejectionWarning: FetchError: invalid json response body at http://presenter.boun.cc/ reason: Unexpected token < in JSON at position 0
    at /root/Bounce/node_modules/node-fetch/lib/index.js:272:32
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:1805) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:1805) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by SlvrEagle23** [comment]
@callumok2004 Like I said, you should probably try `console.log` dumping the raw response or something similar, because if you're authenticated via an API key, sometimes the API will return exceptions in HTML, so you'll likely be seeing an exception message in there somewhere.

**Comment by callumok2004** [comment]
![image](https://user-images.githubusercontent.com/35779365/77962904-5d2bb480-72d4-11ea-859b-12e8b64e1d58.png)

**Comment by callumok2004** [comment]
-.-

**Comment by callumok2004** [comment]
Hello?

**Comment by callumok2004** [comment]
OK, I just did some more testing and I get this:
```
405
Method not allowed. Must be one of: GET
The request method is not supported for the requested resource.
```

**Comment by callumok2004** [comment]
```
DELETE /station​/{station_id}​/file​/{id}
```

**Comment by SlvrEagle23** [comment]
@callumok2004 It's not necessary or helpful to post replies like `-.-` or `hello?` as you did prior to removing them here. We're volunteers with very limited time doing our best to survive a pandemic. Providing support for radio software that we give away for free isn't our highest priority, yet we will do our best to get to your issues all the same.

You're correct, there is currently no `DELETE` endpoint to directly delete files. From our own internal Music files manager, this is a `batch` operation; you can see the specifics by attempting to delete a file from our media manager and inspecting the request it makes to the API. We can add a `DELETE` endpoint in future versions, but this would be a new feature request.

**Comment by callumok2004** [comment]
@SlvrEagle23

**Comment by callumok2004** [comment]
Ah right!
