### ISSUE TITLE
Now Playing Data Doesn't Update

### ISSUE THREAD

**Issue by MegaJoshy** [AzuraCast/AzuraCast#3067]
**Using Docker installation method**
Yes

**AzuraCast version**
v0.10.3, #a283f7d (2020-08-03 14:17)

**Host Operating System**
Ubuntu 20.04

**Describe the bug**
Now playing data does not update, happens when I do it manually and does it automatically. 

**To Reproduce**
1. Manually do it for the docker.sh script or on the administration dashboard

**Expected behavior**
Nowplaying data automatically updates

**Relevant Logs**
```
[2020-08-03T20:02:02.915095+00:00] AzuraCast.INFO: Running Now Playing sync task [] []
web_1                      | [2020-08-03T20:02:02.918117+00:00] AzuraCast.INFO: Running 1-minute sync task [] []
web_1                      | PHP Fatal error:  Uncaught Error: Cannot use object of type NowPlaying\Result\Result as array in /var/azuracast/www/src/Radio/Remote/AzuraRelay.php:34
web_1                      | Stack trace:
web_1                      | #0 /var/azuracast/www/src/Sync/Task/NowPlaying.php(426): App\Radio\Remote\AzuraRelay->updateNowPlaying()
web_1                      | #1 /var/azuracast/www/src/DeferredCallable.php(42): App\Sync\Task\NowPlaying->addToRawFromRemotes()
web_1                      | #2 /var/azuracast/www/vendor/symfony/event-dispatcher/EventDispatcher.php(230): App\DeferredCallable->__invoke()
web_1                      | #3 /var/azuracast/www/vendor/symfony/event-dispatcher/EventDispatcher.php(59): Symfony\Component\EventDispatcher\EventDispatcher->callListeners()
web_1                      | #4 /var/azuracast/www/src/Sync/Task/NowPlaying.php(202): Symfony\Component\EventDispatcher\EventDispatcher->dispatch()
web_1                      | #5 /var/azuracast/www/vendor/malkusch/lock/classes/mutex/LockMutex.php(42): App\Sync\Task\NowPlaying->App\Sync\Task\{closure}()
web_1                      | #6 /var/azuracast/www/src/Lock/Lock.php(83): malkusch\lock\mutex\LockMutex->synchronized()
web_1                      | #7 /var/azuracast/www/src/Sync/Task/NowPlaying.php(335): App\Lock\Lock->run( in /var/azuracast/www/src/Radio/Remote/AzuraRelay.php on line 34
web_1                      | 
web_1                      | Fatal error: Uncaught Error: Cannot use object of type NowPlaying\Result\Result as array in /var/azuracast/www/src/Radio/Remote/AzuraRelay.php:34
web_1                      | Stack trace:
web_1                      | #0 /var/azuracast/www/src/Sync/Task/NowPlaying.php(426): App\Radio\Remote\AzuraRelay->updateNowPlaying()
web_1                      | #1 /var/azuracast/www/src/DeferredCallable.php(42): App\Sync\Task\NowPlaying->addToRawFromRemotes()
web_1                      | #2 /var/azuracast/www/vendor/symfony/event-dispatcher/EventDispatcher.php(230): App\DeferredCallable->__invoke()
web_1                      | #3 /var/azuracast/www/vendor/symfony/event-dispatcher/EventDispatcher.php(59): Symfony\Component\EventDispatcher\EventDispatcher->callListeners()
web_1                      | #4 /var/azuracast/www/src/Sync/Task/NowPlaying.php(202): Symfony\Component\EventDispatcher\EventDispatcher->dispatch()
web_1                      | #5 /var/azuracast/www/vendor/malkusch/lock/classes/mutex/LockMutex.php(42): App\Sync\Task\NowPlaying->App\Sync\Task\{closure}()
web_1                      | #6 /var/azuracast/www/src/Lock/Lock.php(83): malkusch\lock\mutex\LockMutex->synchronized()
web_1                      | #7 /var/azuracast/www/src/Sync/Task/NowPlaying.php(335): App\Lock\Lock->run( in /var/azuracast/www/src/Radio/Remote/AzuraRelay.php on line 34
```

**Additional context**
Using one AzuraRelay.

**Comment by SlvrEagle23** [comment]
@MegaJoshy Thank you for the report. This is likely an issue that we need to fix on our end. I will get back to this as soon as I have a chance.

**Comment by MegaJoshy** [comment]
Alright, thanks for the reply! Hope it gets fixed soon!

**Comment by SlvrEagle23** [comment]
@MegaJoshy This should be fixed as of the latest update. Sorry for the delay in getting back to this.
