### ISSUE TITLE
Cannot get remote icecast listeners

### ISSUE THREAD

**Issue by Abqehebter** [AzuraCast/AzuraCast#4090]
**Using Docker installation method**
Yes

**AzuraCast version**
Rolling Release #ccdee79 (2021-04-27 17:51) • Docker • PHP 8.0

**Host Operating System**
Ubuntu 20.04 LTS

**Describe the bug**
After the updates I installed yesterday, the remote relay listeners no longer work as they did before.

I log in normally to the interface but the stream is shown as offline and the listeners are not shown either. Instead I get a critical error message (See logs)

**Expected behavior**
As described above, AzuraCast does not take over the listeners as it did before. But my status-json.xsl actually looks like AzuraCast reads it out:
```
{
   "icestats":{
      "source":{
         "bitrate":128,
         "genre":"Genre",
         "audio_info":"channels=2;samplerate=44100;bitrate=128",
         "listenurl":"\/station",
         "channels":2,
         "samplerate":44100,
         "server_type":"audio\/mpeg",
         "listeners":"3"
      }
   }
}
```

**Relevant Logs**
```
[2021-04-28T07:46:32.074734+00:00] AzuraCast.ERROR: TypeError: NowPlaying\Result\Listeners::__construct(): Argument #1 ($total) must be of type int, string given, called in /var/azuracast/www/vendor/azuracast/nowplaying/src/Adapter/Icecast.php on line 116 (uncaught exception) at /var/azuracast/www/vendor/azuracast/nowplaying/src/Result/Listeners.php line 13 while running console command `sync:run` {"exception":"[object] (TypeError(code: 0): NowPlaying\\Result\\Listeners::__construct(): Argument #1 ($total) must be of type int, string given, called in /var/azuracast/www/vendor/azuracast/nowplaying/src/Adapter/Icecast.php on line 116 at /var/azuracast/www/vendor/azuracast/nowplaying/src/Result/Listeners.php:13)"} {"station":{"id":1,"name":"Station"}}

[2021-04-28T07:46:32.075050+00:00] AzuraCast.WARNING: Console command `sync:run` exited with error code 1. [] {"station":{"id":1,"name":"Station"}}

[2021-04-28T07:46:32.075328+00:00] AzuraCast.CRITICAL: Fatal error: Uncaught TypeError: NowPlaying\Result\Listeners::__construct(): Argument #1 ($total) must be of type int, string given, called in /var/azuracast/www/vendor/azuracast/nowplaying/src/Adapter/Icecast.php on line 116 and defined in /var/azuracast/www/vendor/azuracast/nowplaying/src/Result/Listeners.php:13 Stack trace: #0 /var/azuracast/www/vendor/azuracast/nowplaying/src/Adapter/Icecast.php(116): NowPlaying\Result\Listeners->__construct() #1 /var/azuracast/www/vendor/azuracast/nowplaying/src/Adapter/Icecast.php(30): NowPlaying\Adapter\Icecast->getJsonNowPlaying() #2 /var/azuracast/www/src/Radio/Remote/AbstractRemote.php(47): NowPlaying\Adapter\Icecast->getNowPlaying() #3 /var/azuracast/www/src/Sync/Task/NowPlayingTask.php(278): App\Radio\Remote\AbstractRemote->updateNowPlaying() #4 /var/azuracast/www/src/DeferredCallable.php(45): App\Sync\Task\NowPlayingTask->addToRawFromRemotes() #5 /var/azuracast/www/vendor/symfony/event-dispatcher/EventDispatcher.php(230): App\DeferredCallable->__invoke() #6 /var/azuracast/www/vendor/symfony/event-dispatcher/EventDispatcher.php(59): Symfony\Component\EventDispatcher\EventDispatcher->callListeners() #7 /var/azuracast/www/src/Sync/Task/NowPlayingTask.php(139): Symfony\Component\EventDispatcher\EventDispatcher->dispatch() #8 /var/azuracast/www/src/Sync/Task/NowPlayingTask.php(88): App\Sync\Task\NowPlayingTask->processStation() #9 /var/azuracast/www/src/Sync/Task/NowPlayingTask.php(64): App\Sync\Task\NowPlayingTask->loadNowPlaying() #10 /var/azuracast/www/src/Sync/Runner.php(108): App\Sync\Task\NowPlayingTask->run() #11 /var/azuracast/www/src/Console/Command/SyncCommand.php(15): App\Sync\Runner->runSyncTask() #12 [internal function]: App\Console\Command\SyncCommand->__invoke() #13 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(74): call_user_func_array() #14 /var/azuracast/www/vendor/mnapoli/silly/src/Application.php(95): Invoker\Invoker->call() #15 /var/azuracast/www/vendor/symfony/console/Command/Command.php(254): Silly\Application->Silly\{closure}() #16 /var/azuracast/www/vendor/symfony/console/Application.php(989): Symfony\Component\Console\Command\Command->run() #17 /var/azuracast/www/vendor/symfony/console/Application.php(290): Symfony\Component\Console\Application->doRunCommand() #18 /var/azuracast/www/vendor/symfony/console/Application.php(166): Symfony\Component\Console\Application->doRun() #19 /var/azuracast/www/bin/console(14): Symfony\Component\Console\Application->run() #20 {main}   thrown in /var/azuracast/www/vendor/azuracast/nowplaying/src/Result/Listeners.php on line 13 [] {"station":{"id":1,"name":"Station"}}
```

**Comment by Abqehebter** [comment]
I have replaced /src/Adapter/Icecast.php in my Docker installation to commit https://github.com/AzuraCast/nowplaying/commit/f159715c22b8c7878eb08381577fc5c4765e53f3 : With this everything seems to work as it should.

**Comment by Abqehebter** [comment]
Thank you @SlvrEagle23 for the commit https://github.com/AzuraCast/nowplaying/commit/84605860c9450023466306edb09b5e1e5fba50cc
It now runs again as usual! :)
