### ISSUE TITLE
Failed update on  Migrate Legacy Configuration

### ISSUE THREAD

**Issue by NicoxDJ** [AzuraCast/AzuraCast#4092]
**Using Docker installation method**
No

**AzuraCast version**
Latest

**Host Operating System**
Ubuntu 20.04.2 LTS

**Describe the bug**
```
TASK [azuracast-setup : Migrate Legacy Configuration (Update Mode)] *********************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "php /var/azuracast/www/bin/console azuracast:config:migrate", "delta": "0:00:02.114485", "end": "2021-04-29 00:03:03.052594", "msg": "non-zero return code", "rc": 255, "start": "2021-04-29 00:03:00.938109", "stderr": "PHP Fatal error:  During class fetch: Uncaught ParseError: syntax error, unexpected 'static' (T_STATIC) in /var/azuracast/www/src/Traits/AvailableStaticallyTrait.php:13\nStack trace:\n#0 /var/azuracast/www/vendor/composer/ClassLoader.php(346): Composer\\Autoload\\includeFile()\n#1 [internal function]: Composer\\Autoload\\ClassLoader->loadClass()\n#2 /var/azuracast/www/src/Environment.php(9): spl_autoload_call()\n#3 /var/azuracast/www/vendor/composer/ClassLoader.php(478): include('/var/azuracast/...')\n#4 /var/azuracast/www/vendor/composer/ClassLoader.php(346): Composer\\Autoload\\includeFile()\n#5 [internal function]: Composer\\Autoload\\ClassLoader->loadClass()\n#6 /var/azuracast/www/bin/console(11): spl_autoload_call()\n#7 {main} in /var/azuracast/www/src/Environment.php on line 9", "stderr_lines": ["PHP Fatal error:  During class fetch: Uncaught ParseError: syntax error, unexpected 'static' (T_STATIC) in /var/azuracast/www/src/Traits/AvailableStaticallyTrait.php:13", "Stack trace:", "#0 /var/azuracast/www/vendor/composer/ClassLoader.php(346): Composer\\Autoload\\includeFile()", "#1 [internal function]: Composer\\Autoload\\ClassLoader->loadClass()", "#2 /var/azuracast/www/src/Environment.php(9): spl_autoload_call()", "#3 /var/azuracast/www/vendor/composer/ClassLoader.php(478): include('/var/azuracast/...')", "#4 /var/azuracast/www/vendor/composer/ClassLoader.php(346): Composer\\Autoload\\includeFile()", "#5 [internal function]: Composer\\Autoload\\ClassLoader->loadClass()", "#6 /var/azuracast/www/bin/console(11): spl_autoload_call()", "#7 {main} in /var/azuracast/www/src/Environment.php on line 9"], "stdout": "\nFatal error: During class fetch: Uncaught ParseError: syntax error, unexpected 'static' (T_STATIC) in /var/azuracast/www/src/Traits/AvailableStaticallyTrait.php:13\nStack trace:\n#0 /var/azuracast/www/vendor/composer/ClassLoader.php(346): Composer\\Autoload\\includeFile()\n#1 [internal function]: Composer\\Autoload\\ClassLoader->loadClass()\n#2 /var/azuracast/www/src/Environment.php(9): spl_autoload_call()\n#3 /var/azuracast/www/vendor/composer/ClassLoader.php(478): include('/var/azuracast/...')\n#4 /var/azuracast/www/vendor/composer/ClassLoader.php(346): Composer\\Autoload\\includeFile()\n#5 [internal function]: Composer\\Autoload\\ClassLoader->loadClass()\n#6 /var/azuracast/www/bin/console(11): spl_autoload_call()\n#7 {main} in /var/azuracast/www/src/Environment.php on line 9", "stdout_lines": ["", "Fatal error: During class fetch: Uncaught ParseError: syntax error, unexpected 'static' (T_STATIC) in /var/azuracast/www/src/Traits/AvailableStaticallyTrait.php:13", "Stack trace:", "#0 /var/azuracast/www/vendor/composer/ClassLoader.php(346): Composer\\Autoload\\includeFile()", "#1 [internal function]: Composer\\Autoload\\ClassLoader->loadClass()", "#2 /var/azuracast/www/src/Environment.php(9): spl_autoload_call()", "#3 /var/azuracast/www/vendor/composer/ClassLoader.php(478): include('/var/azuracast/...')", "#4 /var/azuracast/www/vendor/composer/ClassLoader.php(346): Composer\\Autoload\\includeFile()", "#5 [internal function]: Composer\\Autoload\\ClassLoader->loadClass()", "#6 /var/azuracast/www/bin/console(11): spl_autoload_call()", "#7 {main} in /var/azuracast/www/src/Environment.php on line 9"]}
```

Or after running manual the command: `php /var/azuracast/www/bin/console azuracast:config:migrate`
```
Fatal error: During class fetch: Uncaught ParseError: syntax error, unexpected 'static' (T_STATIC) in /var/azuracast/www/src/Traits/AvailableStaticallyTrait.php:13
Stack trace:
#0 /var/azuracast/www/vendor/composer/ClassLoader.php(346): Composer\Autoload\includeFile()
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#2 /var/azuracast/www/src/Environment.php(9): spl_autoload_call()
#3 /var/azuracast/www/vendor/composer/ClassLoader.php(478): include('/var/azuracast/...')
#4 /var/azuracast/www/vendor/composer/ClassLoader.php(346): Composer\Autoload\includeFile()
#5 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#6 /var/azuracast/www/bin/console(11): spl_autoload_call()
#7 {main} in /var/azuracast/www/src/Environment.php on line 9
```

**Device(s):**
- Device: Raspberry Pi 3b+

**Comment by NicoxDJ** [comment]
`./update.sh --full` fix it
