### ISSUE TITLE
AzuraCast Update Error New Version

### ISSUE THREAD

**Issue by ogrenci01** [AzuraCast/AzuraCast#4387]
**Using Docker installation method?**
No (Ansible)

**AzuraCast version:**
AzuraCast • Rolling Release #3cb73fe (2021-07-06 16:41)

**Host Operating System:**
Ubuntu 18.04 LTS

**Describe the bug:**
I cannot update azuracast to the latest version.

**Expected behavior:**
The update cannot be completed. Azuracast doesn't work at all.

**Relevant logs:**
`Log here:
[2021-07-09T08:32:46.776687+00:00] AzuraCast.CRITICAL: Fatal error: Uncaught RedisException: php_network_getaddresses: getaddrinfo failed: No address associated with hostname in /var/azuracast/www/config/services.php:155 Stack trace: #0 /var/azuracast/www/config/services.php(155): Redis->connect() #1 [internal function]: DI\Definition\Source\DefinitionFile::{closure}() #2 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(74): call_user_func_array() #3 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/FactoryResolver.php(80): Invoker\Invoker->call() #4 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(71): DI\Definition\Resolver\FactoryResolver->resolve() #5 /var/azuracast/www/vendor/php-di/php-di/src/Container.php(387): DI\Definition\Resolver\ResolverDispatcher->resolve() #6 /var/azuracast/www/vendor/php-di/php-di/src/Container.php(138): DI\Container->resolveDefinition() #7 /var/azuracast/www/config/services.php(177): DI\Container->get() #8 [internal function]: DI\Definition\Source\DefinitionFile::{closure}() #9 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(74): call_user_func_array() #10 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/FactoryResolver.php(80): Invoker\Invoker->call() #11 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(71): DI\Definition\Resolver\FactoryResolver->resolve() #12 /var/azuracast/www/vendor/php-di/php-di/src/Container.php(387): DI\Definition\Resolver\ResolverDispatcher->resolve() #13 /var/azuracast/www/vendor/php-di/php-di/src/Container.php(138): DI\Container->resolveDefinition() #14 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Reference.php(53): DI\Container->get() #15 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(66): DI\Definition\Reference->resolve() #16 /var/azuracast/www/vendor/php-di/php-di/src/Container.php(387): DI\Definition\Resolver\ResolverDispatcher->resolve() #17 /var/azuracast/www/vendor/php-di/php-di/src/Container.php(138): DI\Container->resolveDefinition() #18 /var/azuracast/www/vendor/php-di/php-di/src/Invoker/FactoryParameterResolver.php(68): DI\Container->get() #19 /var/azuracast/www/vendor/php-di/invoker/src/ParameterResolver/ResolverChain.php(31): DI\Invoker\FactoryParameterResolver->getParameters() #20 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(58): Invoker\ParameterResolver\ResolverChain->getParameters() #21 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/FactoryResolver.php(80): Invoker\Invoker->call() #22 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(71): DI\Definition\Resolver\FactoryResolver->resolve() #23 /var/azuracast/www/vendor/php-di/php-di/src/Container.php(387): DI\Definition\Resolver\ResolverDispatcher->resolve() #24 /var/azuracast/www/vendor/php-di/php-di/src/Container.php(138): DI\Container->resolveDefinition() #25 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Reference.php(53): DI\Container->get() #26 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(66): DI\Definition\Reference->resolve() #27 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ParameterResolver.php(78): DI\Definition\Resolver\ResolverDispatcher->resolve() #28 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php(138): DI\Definition\Resolver\ParameterResolver->resolveParameters() #29 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php(71): DI\Definition\Resolver\ObjectCreator->createInstance() #30 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(71): DI\Definition\Resolver\ObjectCreator->resolve() #31 /var/azuracast/www/vendor/php-di/php-di/src/Container.php(387): DI\Definition\Resolver\ResolverDispatcher->resolve() #32 /var/azuracast/www/vendor/php-di/php-di/src/Container.php(138): DI\Container->resolveDefinition() #33 /var/azuracast/www/vendor/php-di/php-di/src/Invoker/FactoryParameterResolver.php(68): DI\Container->get() #34 /var/azuracast/www/vendor/php-di/invoker/src/ParameterResolver/ResolverChain.php(31): DI\Invoker\FactoryParameterResolver->getParameters() #35 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(58): Invoker\ParameterResolver\ResolverChain->getParameters() #36 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/FactoryResolver.php(80): Invoker\Invoker->call() #37 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(71): DI\Definition\Resolver\FactoryResolver->resolve() #38 /var/azuracast/www/vendor/php-di/php-di/src/Container.php(387): DI\Definition\Resolver\ResolverDispatcher->resolve() #39 /var/azuracast/www/vendor/php-di/php-di/src/Container.php(138): DI\Container->resolveDefinition() #40 /var/azuracast/www/src/AppFactory.php(44): DI\Container->get() #41 /var/azuracast/www/bin/console(11): App\AppFactory::createCli() #42 {main}   thrown in /var/azuracast/www/config/services.php on line 155 [] []`

**Device(s):**

- Device: PC
- OS: Windows 10
- Browser:  Opera
- Version: Latest

**Additional context:**
I know there is no support for Ansible. Please help me find the source of this problem.

**Comment by ogrenci01** [comment]
Thank you so much. Everything works very well. I love Azuracast and its team. ;)
