### ISSUE TITLE
errors during update

### ISSUE THREAD

**Issue by silvaalex2021** [AzuraCast/AzuraCast#4415]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #599319c (2021-07-19 18:36) 

### What happened?

when upgrading azuracast to version #599319c , some errors appeared when the installer tried to restart the radio stations.

I'm not sure if something went wrong with my installation (almost certainly not since apparently everything works fine), but I'm leaving everything as is just in case.

### Relevant log output

```shell
Restarting all radio stations...
--------------------------------

 0/1 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0%[2021-07-19T18:52:43.103980+00:00] AzuraCast.ERROR: TypeError: str_replace(): Argument #3 ($subject) must be of type array|string, int given (uncaught exception) at /var/azuracast/www/src/Radio/Frontend/SHOUTcast.php line 165 while running console command `azuracast:setup` {"exception":"[object] (TypeError(code: 0): str_replace(): Argument #3 ($subject) must be of type array|string, int given at /var/azuracast/www/src/Radio/Frontend/SHOUTcast.php:165)"} []
[2021-07-19T18:52:43.105302+00:00] AzuraCast.WARNING: Console command `azuracast:setup` exited with error code 1. [] []
[19-Jul-2021 18:52:43 UTC] PHP Fatal error:  Uncaught TypeError: str_replace(): Argument #3 ($subject) must be of type array|string, int given in /var/azuracast/www/src/Radio/Frontend/SHOUTcast.php:165
Stack trace:
#0 /var/azuracast/www/src/Radio/Frontend/SHOUTcast.php(165): str_replace()
#1 /var/azuracast/www/src/Radio/AbstractAdapter.php(50): App\Radio\Frontend\SHOUTcast->getCurrentConfiguration()
#2 /var/azuracast/www/src/Radio/Configuration.php(140): App\Radio\AbstractAdapter->write()
#3 /var/azuracast/www/src/Console/Command/RestartRadioCommand.php(41): App\Radio\Configuration->writeConfiguration()
#4 [internal function]: App\Console\Command\RestartRadioCommand->__invoke()
#5 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(74): call_user_func_array()
#6 /var/azuracast/www/vendor/mnapoli/silly/src/Application.php(95): Invoker\Invoker->call()
#7 /var/azuracast/www/vendor/symfony/console/Command/Command.php(297): Silly\Application->Silly\{closure}()
#8 /var/azuracast/www/src/Console/Command/CommandAbstract.php(32): Symfony\Component\Console\Command\Command->run()
#9 /var/azuracast/www/src/Console/Command/SetupCommand.php(43): App\Console\Command\CommandAbstract->runCommand()
#10 [internal function]: App\Console\Command\SetupCommand->__invoke()
#11 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(74): call_user_func_array()
#12 /var/azuracast/www/vendor/mnapoli/silly/src/Application.php(95): Invoker\Invoker->call()
#13 /var/azuracast/www/vendor/symfony/console/Command/Command.php(297): Silly\Application->Silly\{closure}()
#14 /var/azuracast/www/vendor/symfony/console/Application.php(996): Symfony\Component\Console\Command\Command->run()
#15 /var/azuracast/www/vendor/symfony/console/Application.php(295): Symfony\Component\Console\Application->doRunCommand()
#16 /var/azuracast/www/vendor/symfony/console/Application.php(167): Symfony\Component\Console\Application->doRun()
#17 /var/azuracast/www/bin/console(17): Symfony\Component\Console\Application->run()
#18 {main}
  thrown in /var/azuracast/www/src/Radio/Frontend/SHOUTcast.php on line 165

Fatal error: Uncaught TypeError: str_replace(): Argument #3 ($subject) must be of type array|string, int given in /var/azuracast/www/src/Radio/Frontend/SHOUTcast.php on line 165

TypeError: str_replace(): Argument #3 ($subject) must be of type array|string, int given in /var/azuracast/www/src/Radio/Frontend/SHOUTcast.php on line 165

Call Stack:
    0.0001     391480   1. {main}() /var/azuracast/www/bin/console:0
    0.2506   15644656   2. App\Console\Application->run($input = ???, $output = ???) /var/azuracast/www/bin/console:17
    0.2580   15956544   3. App\Console\Application->doRun($input = class Symfony\Component\Console\Input\ArgvInput { private $tokens = [0 => 'azuracast:setup', 1 => '--update']; private $parsed = []; protected $definition = class Symfony\Component\Console\Input\InputDefinition { private $arguments = [...]; private $requiredCount = 1; private $lastArrayArgument = NULL; private $lastOptionalArgument = NULL; private $options = [...]; private $negations = [...]; private $shortcuts = [...] }; protected $stream = NULL; protected $options = ['update' => TRUE]; protected $arguments = ['command' => 'azuracast:setup']; protected $interactive = TRUE }, $output = class Symfony\Component\Console\Output\ConsoleOutput { private $stderr = class Symfony\Component\Console\Output\StreamOutput { private $stream = resource(577) of type (stream); private ${Symfony\Component\Console\Output\Output}verbosity = 32; private ${Symfony\Component\Console\Output\Output}formatter = class Symfony\Component\Console\Formatter\OutputFormatter { ... } }; private $consoleSectionOutputs = []; private ${Symfony\Component\Console\Output\StreamOutput}stream = resource(569) of type (stream); private ${Symfony\Component\Console\Output\Output}verbosity = 32; private ${Symfony\Component\Console\Output\Output}formatter = class Symfony\Component\Console\Formatter\OutputFormatter { private $decorated = TRUE; private $styles = [...]; private $styleStack = class Symfony\Component\Console\Formatter\OutputFormatterStyleStack { ... } } }) /var/azuracast/www/vendor/symfony/console/Application.php:167
    0.2584   15975712   4. App\Console\Application->doRunCommand($command = class Silly\Command\Command { private ${Symfony\Component\Console\Command\Command}application = class App\Console\Application { private ${Silly\Application}expressionParser = class Silly\Command\ExpressionParser { ... }; private ${Silly\Application}invoker = class Invoker\Invoker { ... }; private ${Silly\Application}container = class DI\Container { ... }; private ${Symfony\Component\Console\Application}commands = [...]; private ${Symfony\Component\Console\Application}wantHelps = FALSE; private ${Symfony\Component\Console\Application}runningCommand = ...; private ${Symfony\Component\Console\Application}name = 'AzuraCast Command Line Tools (production)'; private ${Symfony\Component\Console\Application}version = '0.13.0'; private ${Symfony\Component\Console\Application}commandLoader = NULL; private ${Symfony\Component\Console\Application}catchExceptions = TRUE; private ${Symfony\Component\Console\Application}autoExit = TRUE; private ${Symfony\Component\Console\Application}definition = class Symfony\Component\Console\Input\InputDefinition { ... }; private ${Symfony\Component\Console\Application}helperSet = class Symfony\Component\Console\Helper\HelperSet { ... }; private ${Symfony\Component\Console\Application}dispatcher = class App\EventDispatcher { ... }; private ${Symfony\Component\Console\Application}terminal = class Symfony\Component\Console\Terminal { ... }; private ${Symfony\Component\Console\Application}defaultCommand = 'list'; private ${Symfony\Component\Console\Application}singleCommand = FALSE; private ${Symfony\Component\Console\Application}initialized = TRUE; private ${Symfony\Component\Console\Application}signalRegistry = class Symfony\Component\Console\SignalRegistry\SignalRegistry { ... }; private ${Symfony\Component\Console\Application}signalsToDispatchEvent = [...] }; private ${Symfony\Component\Console\Command\Command}name = 'azuracast:setup'; private ${Symfony\Component\Console\Command\Command}processTitle = NULL; private ${Symfony\Component\Console\Command\Command}aliases = []; private ${Symfony\Component\Console\Command\Command}definition = class Symfony\Component\Console\Input\InputDefinition { private $arguments = [...]; private $requiredCount = 0; private $lastArrayArgument = NULL; private $lastOptionalArgument = NULL; private $options = [...]; private $negations = [...]; private $shortcuts = [...] }; private ${Symfony\Component\Console\Command\Command}hidden = FALSE; private ${Symfony\Component\Console\Command\Command}help = ''; private ${Symfony\Component\Console\Command\Command}description = 'Run all general AzuraCast setup steps.'; private ${Symfony\Component\Console\Command\Command}fullDefinition = class Symfony\Component\Console\Input\InputDefinition { private $arguments = [...]; private $requiredCount = 1; private $lastArrayArgument = NULL; private $lastOptionalArgument = NULL; private $options = [...]; private $negations = [...]; private $shortcuts = [...] }; private ${Symfony\Component\Console\Command\Command}ignoreValidationErrors = FALSE; private ${Symfony\Component\Console\Command\Command}code = class Closure { public $static = [...]; public $this = class App\Console\Application { ... }; public $parameter = [...] }; private ${Symfony\Component\Console\Command\Command}synopsis = []; private ${Symfony\Component\Console\Command\Command}usages = []; private ${Symfony\Component\Console\Command\Command}helperSet = class Symfony\Component\Console\Helper\HelperSet { private $helpers = [...]; private $command = NULL } }, $input = class Symfony\Component\Console\Input\ArgvInput { private $tokens = [0 => 'azuracast:setup', 1 => '--update']; private $parsed = []; protected $definition = class Symfony\Component\Console\Input\InputDefinition { private $arguments = [...]; private $requiredCount = 1; private $lastArrayArgument = NULL; private $lastOptionalArgument = NULL; private $options = [...]; private $negations = [...]; private $shortcuts = [...] }; protected $stream = NULL; protected $options = ['update' => TRUE]; protected $arguments = ['command' => 'azuracast:setup']; protected $interactive = TRUE }, $output = class Symfony\Component\Console\Output\ConsoleOutput { private $stderr = class Symfony\Component\Console\Output\StreamOutput { private $stream = resource(577) of type (stream); private ${Symfony\Component\Console\Output\Output}verbosity = 32; private ${Symfony\Component\Console\Output\Output}formatter = class Symfony\Component\Console\Formatter\OutputFormatter { ... } }; private $consoleSectionOutputs = []; private ${Symfony\Component\Console\Output\StreamOutput}stream = resource(569) of type (stream); private ${Symfony\Component\Console\Output\Output}verbosity = 32; private ${Symfony\Component\Console\Output\Output}formatter = class Symfony\Component\Console\Formatter\OutputFormatter { private $decorated = TRUE; private $styles = [...]; private $styleStack = class Symfony\Component\Console\Formatter\OutputFormatterStyleStack { ... } } }) /var/azuracast/www/vendor/symfony/console/Application.php:295

[2021-07-19T18:52:43.105925+00:00] AzuraCast.CRITICAL: Fatal error: Uncaught TypeError: str_replace(): Argument #3 ($subject) must be of type array|string, int given in /var/azuracast/www/src/Radio/Frontend/SHOUTcast.php:165 Stack trace: #0 /var/azuracast/www/src/Radio/Frontend/SHOUTcast.php(165): str_replace() #1 /var/azuracast/www/src/Radio/AbstractAdapter.php(50): App\Radio\Frontend\SHOUTcast->getCurrentConfiguration() #2 /var/azuracast/www/src/Radio/Configuration.php(140): App\Radio\AbstractAdapter->write() #3 /var/azuracast/www/src/Console/Command/RestartRadioCommand.php(41): App\Radio\Configuration->writeConfiguration() #4 [internal function]: App\Console\Command\RestartRadioCommand->__invoke() #5 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(74): call_user_func_array() #6 /var/azuracast/www/vendor/mnapoli/silly/src/Application.php(95): Invoker\Invoker->call() #7 /var/azuracast/www/vendor/symfony/console/Command/Command.php(297): Silly\Application->Silly\{closure}() #8 /var/azuracast/www/src/Console/Command/CommandAbstract.php(32): Symfony\Component\Console\Command\Command->run() #9 /var/azuracast/www/src/Console/Command/SetupCommand.php(43): App\Console\Command\CommandAbstract->runCommand() #10 [internal function]: App\Console\Command\SetupCommand->__invoke() #11 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(74): call_user_func_array() #12 /var/azuracast/www/vendor/mnapoli/silly/src/Application.php(95): Invoker\Invoker->call() #13 /var/azuracast/www/vendor/symfony/console/Command/Command.php(297): Silly\Application->Silly\{closure}() #14 /var/azuracast/www/vendor/symfony/console/Application.php(996): Symfony\Component\Console\Command\Command->run() #15 /var/azuracast/www/vendor/symfony/console/Application.php(295): Symfony\Component\Console\Application->doRunCommand() #16 /var/azuracast/www/vendor/symfony/console/Application.php(167): Symfony\Component\Console\Application->doRun() #17 /var/azuracast/www/bin/console(17): Symfony\Component\Console\Application->run() #18 {main}   thrown in /var/azuracast/www/src/Radio/Frontend/SHOUTcast.php on line 165 [] []
ERROR: 255
```

**Comment by YosefAdPro** [comment]
I encountered this error even after updating.
I will note that the Shoutcast service is working properly.

![image](https://user-images.githubusercontent.com/11810187/126338204-95b60186-3127-404a-9684-1564df2e3fb8.png)
