### ISSUE TITLE
An Update Error (Ansible)

### ISSUE THREAD

**Issue by ogrenci01** [AzuraCast/AzuraCast#4599]
### Installation Method

Ansible Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#8b83d8a (latest)

### What happened?

I am using Ansible. Update failed. It doesn't seem to be a problem for Docker.

### Relevant log output

```shell
Update Script Error:

fatal: [localhost]: FAILED! => {"changed": true, "cmd": "npm run build", "delta": "0:03:31.100055", "end": "2021-09-21 08:31:48.364869", "msg": "non-zero return code", "rc": 1, "start": "2021-09-21 08:28:17.264814", "stderr": "(node:9549) [DEP_WEBPACK_COMPILATION_NORMAL_MODULE_LOADER_HOOK] DeprecationWarning: Compilation.hooks.normalModuleLoader was moved to NormalModule.getCompilationHooks(compilation).loader\n(Use `node --trace-deprecation ...` to show where the warning was created)\nDEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.\n\nRecommendation: math.div($val, $val * 0 + 1)\n\nMore info and automated migrator: https://sass-lang.com/d/slash-div\n\n   ╷\n76 │   @return $val / ($val * 0 + 1);\n   │           ^^^^^^^^^^^^^^^^^^^^^\n   ╵\n    scss/_functions.scss 76:11             strip-unit()\n    scss/variables/_typography.scss 81:28  @import\n    scss/_common.scss 15:9                 @import\n    scss/style.scss 3:11                   root stylesheet\n\nDEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.\n\nRecommendation: math.div(24, strip-unit($font-size-root))\n\nMore info and automated migrator: https://sass-lang.com/d/slash-div\n\n   ╷\n81 │ $material-icon-size: (24 / strip-unit($font-size-root) * 1rem) !default;\n   │                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n   ╵\n    scss/variables/_typography.scss 81:23  @import\n    scss/_common.scss 15:9                 @import\n    scss/style.scss 3:11                   root stylesheet\n\nDEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.\n\nRecommendation: math.div($btn-height - $btn-font-size * $btn-line-height, 2)\n\nMore info and automated migrator: https://sass-lang.com/d/slash-div\n\n   ╷\n32 │ $btn-padding-y: (($btn-height - $btn-font-size * $btn-line-height) / 2) !default;\n   │                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n   ╵\n    scss/variables/_variable-material.scss 32:18  @import\n    scss/_common.scss 17:9                        @import\n    scss/style.scss 3:11                          root stylesheet\n\nDEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.\n\nRecommendation: math.div($btn-height-lg - $btn-font-size-lg * $btn-line-height, 2)\n\nMore info and automated migrator: https://sass-lang.com/d/slash-div\n\n   ╷\n33 │ $btn-padding-y-lg: (($btn-height-lg - $btn-font-size-lg * $btn-line-height) / 2) !default;\n   │                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n   ╵\n    scss/variables/_variable-material.scss 33:21  @import\n    scss/_common.scss 17:9                        @import\n    scss/style.scss 3:11                          root stylesheet\n\nDEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.\n\nRecommendation: math.div($btn-height-sm - $btn-font-size-sm * $btn-line-height, 2)\n\nMore info and automated migrator: https://sass-lang.com/d/slash-div\n\n   ╷\n34 │ $btn-padding-y-sm: (($btn-height-sm - $btn-font-size-sm * $btn-line-height) / 2) !default;\n   │                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n   ╵\n    scss/variables/_variable-material.scss 34:21  @import\n    scss/_common.scss 17:9                        @import\n    scss/style.scss 3:11                          root stylesheet\n\nWARNING: 142 repetitive deprecation warnings omitted.\n\n(node:9549) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.\nBREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.\n\tDo changes to assets earlier, e. g. in Compilation.hooks.processAssets.\n\tMake sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.\n[webpack-cli] [Error: EACCES: permission denied, mkdir '/var/azuracast/www/web/static/webpack_dist/images'] {\n  errno: -13,\n  code: 'EACCES',\n  syscall: 'mkdir',\n  path: '/var/azuracast/www/web/static/webpack_dist/images'\n}\n[08:31:48] 'build-vue' errored after 3.45 min\n[08:31:48] Error: Non-zero exit code of \"2\"\n    at ChildProcess.<anonymous> (/var/azuracast/www/frontend/node_modules/gulp-run-command/index.es5.js:120:15)\n    at ChildProcess.emit (events.js:400:28)\n    at ChildProcess.emit (domain.js:532:15)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)\n    at Process.callbackTrampoline (internal/async_hooks.js:131:17)\n[08:31:48] 'default' errored after 3.47 min\nnpm ERR! code ELIFECYCLE\nnpm ERR! errno 1\nnpm ERR! azuracast@ build: `gulp`\nnpm ERR! Exit status 1\nnpm ERR! \nnpm ERR! Failed at the azuracast@ build script.\nnpm ERR! This is probably not a problem with npm. There is likely additional logging output above.\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /var/azuracast/.npm/_logs/2021-09-21T05_31_48_348Z-debug.log", "stderr_lines": ["(node:9549) [DEP_WEBPACK_COMPILATION_NORMAL_MODULE_LOADER_HOOK] DeprecationWarning: Compilation.hooks.normalModuleLoader was moved to NormalModule.getCompilationHooks(compilation).loader", "(Use `node --trace-deprecation ...` to show where the warning was created)", "DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.", "", "Recommendation: math.div($val, $val * 0 + 1)", "", "More info and automated migrator: https://sass-lang.com/d/slash-div", "", "   ╷", "76 │   @return $val / ($val * 0 + 1);", "   │           ^^^^^^^^^^^^^^^^^^^^^", "   ╵", "    scss/_functions.scss 76:11             strip-unit()", "    scss/variables/_typography.scss 81:28  @import", "    scss/_common.scss 15:9                 @import", "    scss/style.scss 3:11                   root stylesheet", "", "DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.", "", "Recommendation: math.div(24, strip-unit($font-size-root))", "", "More info and automated migrator: https://sass-lang.com/d/slash-div", "", "   ╷", "81 │ $material-icon-size: (24 / strip-unit($font-size-root) * 1rem) !default;", "   │                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^", "   ╵", "    scss/variables/_typography.scss 81:23  @import", "    scss/_common.scss 15:9                 @import", "    scss/style.scss 3:11                   root stylesheet", "", "DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.", "", "Recommendation: math.div($btn-height - $btn-font-size * $btn-line-height, 2)", "", "More info and automated migrator: https://sass-lang.com/d/slash-div", "", "   ╷", "32 │ $btn-padding-y: (($btn-height - $btn-font-size * $btn-line-height) / 2) !default;", "   │                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^", "   ╵", "    scss/variables/_variable-material.scss 32:18  @import", "    scss/_common.scss 17:9                        @import", "    scss/style.scss 3:11                          root stylesheet", "", "DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.", "", "Recommendation: math.div($btn-height-lg - $btn-font-size-lg * $btn-line-height, 2)", "", "More info and automated migrator: https://sass-lang.com/d/slash-div", "", "   ╷", "33 │ $btn-padding-y-lg: (($btn-height-lg - $btn-font-size-lg * $btn-line-height) / 2) !default;", "   │                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^", "   ╵", "    scss/variables/_variable-material.scss 33:21  @import", "    scss/_common.scss 17:9                        @import", "    scss/style.scss 3:11                          root stylesheet", "", "DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.", "", "Recommendation: math.div($btn-height-sm - $btn-font-size-sm * $btn-line-height, 2)", "", "More info and automated migrator: https://sass-lang.com/d/slash-div", "", "   ╷", "34 │ $btn-padding-y-sm: (($btn-height-sm - $btn-font-size-sm * $btn-line-height) / 2) !default;", "   │                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^", "   ╵", "    scss/variables/_variable-material.scss 34:21  @import", "    scss/_common.scss 17:9                        @import", "    scss/style.scss 3:11                          root stylesheet", "", "WARNING: 142 repetitive deprecation warnings omitted.", "", "(node:9549) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.", "BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.", "\tDo changes to assets earlier, e. g. in Compilation.hooks.processAssets.", "\tMake sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.", "[webpack-cli] [Error: EACCES: permission denied, mkdir '/var/azuracast/www/web/static/webpack_dist/images'] {", "  errno: -13,", "  code: 'EACCES',", "  syscall: 'mkdir',", "  path: '/var/azuracast/www/web/static/webpack_dist/images'", "}", "[08:31:48] 'build-vue' errored after 3.45 min", "[08:31:48] Error: Non-zero exit code of \"2\"", "    at ChildProcess.<anonymous> (/var/azuracast/www/frontend/node_modules/gulp-run-command/index.es5.js:120:15)", "    at ChildProcess.emit (events.js:400:28)", "    at ChildProcess.emit (domain.js:532:15)", "    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)", "    at Process.callbackTrampoline (internal/async_hooks.js:131:17)", "[08:31:48] 'default' errored after 3.47 min", "npm ERR! code ELIFECYCLE", "npm ERR! errno 1", "npm ERR! azuracast@ build: `gulp`", "npm ERR! Exit status 1", "npm ERR! ", "npm ERR! Failed at the azuracast@ build script.", "npm ERR! This is probably not a problem with npm. There is likely additional logging output above.", "", "npm ERR! A complete log of this run can be found in:", "npm ERR!     /var/azuracast/.npm/_logs/2021-09-21T05_31_48_348Z-debug.log"], "stdout": "\n> azuracast@ build /var/azuracast/www/frontend\n> gulp\n\n[08:28:20] Using gulpfile ~/www/frontend/gulpfile.js\n[08:28:20] Starting 'default'...\n[08:28:20] Starting 'clean'...\n[08:28:20] Finished 'clean' after 191 ms\n[08:28:20] Starting 'concat-js'...\n[08:28:20] Starting 'build-vue'...\n[08:28:20] Starting 'build-js'...\n[08:28:20] Starting 'build-css'...\n[08:28:20] Starting 'bundle_deps'...\n[08:28:20] Starting 'scripts:jquery'...\n[08:28:20] Starting 'scripts:bootstrap'...\n[08:28:20] Starting 'scripts:bootstrap-notify'...\n[08:28:20] Starting 'scripts:sweetalert2'...\n[08:28:20] Starting 'scripts:autosize'...\n[08:28:20] Starting 'scripts:material-icons'...\n[08:28:20] Starting 'scripts:roboto-fontface'...\n[08:28:20] Starting 'scripts:dirrty'...\n[08:28:20] Starting 'scripts:zxcvbn'...\n[08:28:20] Starting 'scripts:select2'...\n[08:28:20] Starting 'scripts:luxon'...\n[08:28:20] Starting 'scripts:humanize-duration'...\n[08:28:20] Starting 'scripts:clipboard'...\n[08:28:20] Starting 'scripts:webcaster'...\n[08:29:02] Finished 'build-css' after 42 s\n[08:29:03] Finished 'scripts:zxcvbn' after 43 s\n[08:29:03] Finished 'scripts:jquery' after 43 s\n[08:29:03] Finished 'scripts:bootstrap' after 43 s\n[08:29:03] Finished 'scripts:bootstrap-notify' after 43 s\n[08:29:03] Finished 'scripts:dirrty' after 43 s\n[08:29:03] Finished 'scripts:sweetalert2' after 43 s\n[08:29:03] Finished 'scripts:humanize-duration' after 43 s\n[08:29:03] Finished 'scripts:clipboard' after 43 s\n[08:29:03] Finished 'scripts:luxon' after 43 s\n[08:29:03] Finished 'scripts:autosize' after 43 s\n[08:29:03] Finished 'build-js' after 43 s\n[08:29:03] Finished 'concat-js' after 43 s\n[08:29:03] Finished 'scripts:select2' after 43 s\n[08:29:03] Finished 'scripts:material-icons' after 43 s\n[08:29:03] Finished 'scripts:webcaster' after 43 s\n[08:29:04] Finished 'scripts:roboto-fontface' after 44 s\n[08:29:04] Finished 'bundle_deps' after 44 s", "stdout_lines": ["", "> azuracast@ build /var/azuracast/www/frontend", "> gulp", "", "[08:28:20] Using gulpfile ~/www/frontend/gulpfile.js", "[08:28:20] Starting 'default'...", "[08:28:20] Starting 'clean'...", "[08:28:20] Finished 'clean' after 191 ms", "[08:28:20] Starting 'concat-js'...", "[08:28:20] Starting 'build-vue'...", "[08:28:20] Starting 'build-js'...", "[08:28:20] Starting 'build-css'...", "[08:28:20] Starting 'bundle_deps'...", "[08:28:20] Starting 'scripts:jquery'...", "[08:28:20] Starting 'scripts:bootstrap'...", "[08:28:20] Starting 'scripts:bootstrap-notify'...", "[08:28:20] Starting 'scripts:sweetalert2'...", "[08:28:20] Starting 'scripts:autosize'...", "[08:28:20] Starting 'scripts:material-icons'...", "[08:28:20] Starting 'scripts:roboto-fontface'...", "[08:28:20] Starting 'scripts:dirrty'...", "[08:28:20] Starting 'scripts:zxcvbn'...", "[08:28:20] Starting 'scripts:select2'...", "[08:28:20] Starting 'scripts:luxon'...", "[08:28:20] Starting 'scripts:humanize-duration'...", "[08:28:20] Starting 'scripts:clipboard'...", "[08:28:20] Starting 'scripts:webcaster'...", "[08:29:02] Finished 'build-css' after 42 s", "[08:29:03] Finished 'scripts:zxcvbn' after 43 s", "[08:29:03] Finished 'scripts:jquery' after 43 s", "[08:29:03] Finished 'scripts:bootstrap' after 43 s", "[08:29:03] Finished 'scripts:bootstrap-notify' after 43 s", "[08:29:03] Finished 'scripts:dirrty' after 43 s", "[08:29:03] Finished 'scripts:sweetalert2' after 43 s", "[08:29:03] Finished 'scripts:humanize-duration' after 43 s", "[08:29:03] Finished 'scripts:clipboard' after 43 s", "[08:29:03] Finished 'scripts:luxon' after 43 s", "[08:29:03] Finished 'scripts:autosize' after 43 s", "[08:29:03] Finished 'build-js' after 43 s", "[08:29:03] Finished 'concat-js' after 43 s", "[08:29:03] Finished 'scripts:select2' after 43 s", "[08:29:03] Finished 'scripts:material-icons' after 43 s", "[08:29:03] Finished 'scripts:webcaster' after 43 s", "[08:29:04] Finished 'scripts:roboto-fontface' after 44 s", "[08:29:04] Finished 'bundle_deps' after 44 s"]}

Login Page Error:

https://prnt.sc/1t20f8h

AzuraCast Log:

AzuraCast.ERROR: File not found: "/var/azuracast/www/web/static/assets.json" {"file":"/var/azuracast/www/src/Utilities/Json.php","line":33,"code":0} []
AzuraCast.CRITICAL: Fatal error: Uncaught RedisException: Connection refused in /var/azuracast/www/config/services.php:155 Stack trace: #0 /var/azuracast/www/config/services.php(155): Redis->connect() #1 [internal function]: DI\Definition\Source\DefinitionFile::{closure}() #2 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(74): call_user_func_array() #3 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/FactoryResolver.php(80): Invoker\Invoker->call() #4 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(71): DI\Definition\Resolver\FactoryResolver->resolve() #5 /var/azuracast/www/vendor/php-di/php-di/src/Container.php(390): DI\Definition\Resolver\ResolverDispatcher->resolve() #6 /var/azuracast/www/vendor/php-di/php-di/src/Container.php(139): DI\Container->resolveDefinition() #7 /var/azuracast/www/config/services.php(177): DI\Container->get() #8 [internal function]: DI\Definition\Source\DefinitionFile::{closure}() #9 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(74): call_user_func_array() #10 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/FactoryResolver.php(80): Invoker\Invoker->call() #11 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(71): DI\Definition\Resolver\FactoryResolver->resolve() #12 /var/azuracast/www/vendor/php-di/php-di/src/Container.php(390): DI\Definition\Resolver\ResolverDispatcher->resolve() #13 /var/azuracast/www/vendor/php-di/php-di/src/Container.php(139): DI\Container->resolveDefinition() #14 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Reference.php(53): DI\Container->get() #15 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(66): DI\Definition\Reference->resolve() #16 /var/azuracast/www/vendor/php-di/php-di/src/Container.php(390): DI\Definition\Resolver\ResolverDispatcher->resolve() #17 /var/azuracast/www/vendor/php-di/php-di/src/Container.php(139): DI\Container->resolveDefinition() #18 /var/azuracast/www/vendor/php-di/php-di/src/Invoker/FactoryParameterResolver.php(68): DI\Container->get() #19 /var/azuracast/www/vendor/php-di/invoker/src/ParameterResolver/ResolverChain.php(31): DI\Invoker\FactoryParameterResolver->getParameters() #20 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(58): Invoker\ParameterResolver\ResolverChain->getParameters() #21 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/FactoryResolver.php(80): Invoker\Invoker->call() #22 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(71): DI\Definition\Resolver\FactoryResolver->resolve() #23 /var/azuracast/www/vendor/php-di/php-di/src/Container.php(390): DI\Definition\Resolver\ResolverDispatcher->resolve() #24 /var/azuracast/www/vendor/php-di/php-di/src/Container.php(139): DI\Container->resolveDefinition() #25 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Reference.php(53): DI\Container->get() #26 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(66): DI\Definition\Reference->resolve() #27 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ParameterResolver.php(78): DI\Definition\Resolver\ResolverDispatcher->resolve() #28 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php(138): DI\Definition\Resolver\ParameterResolver->resolveParameters() #29 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php(71): DI\Definition\Resolver\ObjectCreator->createInstance() #30 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(71): DI\Definition\Resolver\ObjectCreator->resolve() #31 /var/azuracast/www/vendor/php-di/php-di/src/Container.php(390): DI\Definition\Resolver\ResolverDispatcher->resolve() #32 /var/azuracast/www/vendor/php-di/php-di/src/Container.php(139): DI\Container->resolveDefinition() #33 /var/azuracast/www/vendor/php-di/php-di/src/Invoker/FactoryParameterResolver.php(68): DI\Container->get() #34 /var/azuracast/www/vendor/php-di/invoker/src/ParameterResolver/ResolverChain.php(31): DI\Invoker\FactoryParameterResolver->getParameters() #35 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(58): Invoker\ParameterResolver\ResolverChain->getParameters() #36 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/FactoryResolver.php(80): Invoker\Invoker->call() #37 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(71): DI\Definition\Resolver\FactoryResolver->resolve() #38 /var/azuracast/www/vendor/php-di/php-di/src/Container.php(390): DI\Definition\Resolver\ResolverDispatcher->resolve() #39 /var/azuracast/www/vendor/php-di/php-di/src/Container.php(139): DI\Container->resolveDefinition() #40 /var/azuracast/www/src/AppFactory.php(66): DI\Container->get() #41 /var/azuracast/www/bin/console(14): App\AppFactory::createCli() #42 {main}   thrown in /var/azuracast/www/config/services.php on line 155 [] []

Php Error Logs:
  thrown in /var/azuracast/www/config/services.php on line 155
[21-Sep-2021 05:34:51 UTC] PHP Fatal error:  Uncaught RedisException: Connection refused in /var/azuracast/www/config/services.php:155
Stack trace:
#0 /var/azuracast/www/config/services.php(155): Redis->connect()
#1 [internal function]: DI\Definition\Source\DefinitionFile::{closure}()
#2 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(74): call_user_func_array()
#3 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/FactoryResolver.php(80): Invoker\Invoker->call()
#4 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(71): DI\Definition\Resolver\FactoryResolver->resolve()
#5 /var/azuracast/www/vendor/php-di/php-di/src/Container.php(390): DI\Definition\Resolver\ResolverDispatcher->resolve()
#6 /var/azuracast/www/vendor/php-di/php-di/src/Container.php(139): DI\Container->resolveDefinition()
#7 /var/azuracast/www/config/services.php(177): DI\Container->get()
#8 [internal function]: DI\Definition\Source\DefinitionFile::{closure}()
#9 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(74): call_user_func_array()
#10 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/FactoryResolver.php(80): Invoker\Invoker->call()
#11 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(71): DI\Definition\Resolver\FactoryResolver->resolve()
#12 /var/azuracast/www/vendor/php-di/php-di/src/Container.php(390): DI\Definition\Resolver\ResolverDispatcher->resolve()
#13 /var/azuracast/www/vendor/php-di/php-di/src/Container.php(139): DI\Container->resolveDefinition()
#14 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Reference.php(53): DI\Container->get()
#15 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(66): DI\Definition\Reference->resolve()
#16 /var/azuracast/www/vendor/php-di/php-di/src/Container.php(390): DI\Definition\Resolver\ResolverDispatcher->resolve()
#17 /var/azuracast/www/vendor/php-di/php-di/src/Container.php(139): DI\Container->resolveDefinition()
#18 /var/azuracast/www/vendor/php-di/php-di/src/Invoker/FactoryParameterResolver.php(68): DI\Container->get()
#19 /var/azuracast/www/vendor/php-di/invoker/src/ParameterResolver/ResolverChain.php(31): DI\Invoker\FactoryParameterResolver->getParameters()
#20 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(58): Invoker\ParameterResolver\ResolverChain->getParameters()
#21 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/FactoryResolver.php(80): Invoker\Invoker->call()
#22 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(71): DI\Definition\Resolver\FactoryResolver->resolve()
#23 /var/azuracast/www/vendor/php-di/php-di/src/Container.php(390): DI\Definition\Resolver\ResolverDispatcher->resolve()
#24 /var/azuracast/www/vendor/php-di/php-di/src/Container.php(139): DI\Container->resolveDefinition()
#25 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Reference.php(53): DI\Container->get()
#26 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(66): DI\Definition\Reference->resolve()
#27 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ParameterResolver.php(78): DI\Definition\Resolver\ResolverDispatcher->resolve()
#28 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php(138): DI\Definition\Resolver\ParameterResolver->resolveParameters()
#29 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php(71): DI\Definition\Resolver\ObjectCreator->createInstance()
#30 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(71): DI\Definition\Resolver\ObjectCreator->resolve()
#31 /var/azuracast/www/vendor/php-di/php-di/src/Container.php(390): DI\Definition\Resolver\ResolverDispatcher->resolve()
#32 /var/azuracast/www/vendor/php-di/php-di/src/Container.php(139): DI\Container->resolveDefinition()
#33 /var/azuracast/www/vendor/php-di/php-di/src/Invoker/FactoryParameterResolver.php(68): DI\Container->get()
#34 /var/azuracast/www/vendor/php-di/invoker/src/ParameterResolver/ResolverChain.php(31): DI\Invoker\FactoryParameterResolver->getParameters()
#35 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(58): Invoker\ParameterResolver\ResolverChain->getParameters()
#36 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/FactoryResolver.php(80): Invoker\Invoker->call()
#37 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(71): DI\Definition\Resolver\FactoryResolver->resolve()
#38 /var/azuracast/www/vendor/php-di/php-di/src/Container.php(390): DI\Definition\Resolver\ResolverDispatcher->resolve()
#39 /var/azuracast/www/vendor/php-di/php-di/src/Container.php(139): DI\Container->resolveDefinition()
#40 /var/azuracast/www/src/AppFactory.php(66): DI\Container->get()
#41 /var/azuracast/www/bin/console(14): App\AppFactory::createCli()
#42 {main}
  thrown in /var/azuracast/www/config/services.php on line 155
```

**Comment by ogrenci01** [comment]
Hello again;

When updating Ansible, /var/azuracast/www/web/static/webpack_dist directory is set to root:root.

chown -R azuracast:azuracast /var/azuracast/www/web/static/webpack_dist

After authorizing, the update will be successful.

**Comment by SlvrEagle23** [comment]
@ogrenci01 Thank you for the report. Fixed in the latest Rolling update.
