### ISSUE TITLE
A few issues with CLI sync:run medium & sync:run

### ISSUE THREAD

**Issue by SC2Mitch** [AzuraCast/AzuraCast#4613]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

4792acc

### What happened?

Issue 1: When running the command `./docker.sh cli sync:run medium` it returns a connection refused despite the fact the service is running and operating normally. I restarted my instance and it still returned the error, running short and long tasks works. 
`mariadb_1                  | 2021-09-24  8:56:12 1299 [Warning] Aborted connection 1299 to db: 'azuracast' user: 'azuracast' host: '172.19.0.6' (Got an error reading communication packets)`

Issue 2: After executing the command `./docker.sh cli sync:run` it returns a large error which can be found in the logs, *I know this is the wrong command but it shouldn't return this huge error* I note that the mariadb collects an aborted connection this may be relevant. 

### Relevant log output

```shell
root@mail:/var/azuracast# ./docker.sh cli sync:run
Creating azuracast_web_run ... done
Starting up AzuraCast services...
Services started up and ready!
[2021-09-24T08:49:24.806279+00:00] AzuraCast.ERROR: TypeError: App\Console\Command\SyncCommand::__invoke(): Argument #2 ($task) must be of type string, null given (uncaught exception) at /var/azuracast/www/src/Console/Command/SyncCommand.php line 12 while running console command `sync:run` {"exception":"[object] (TypeError(code: 0): App\\Console\\Command\\SyncCommand::__invoke(): Argument #2 ($task) must be of type string, null given at /var/azuracast/www/src/Console/Command/SyncCommand.php:12)"} []
[2021-09-24T08:49:24.808879+00:00] AzuraCast.WARNING: Console command `sync:run` exited with error code 1. [] []
[24-Sep-2021 08:49:24 UTC] PHP Fatal error:  Uncaught TypeError: App\Console\Command\SyncCommand::__invoke(): Argument #2 ($task) must be of type string, null given in /var/azuracast/www/src/Console/Command/SyncCommand.php:12
Stack trace:
#0 [internal function]: App\Console\Command\SyncCommand->__invoke()
#1 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(74): call_user_func_array()
#2 /var/azuracast/www/vendor/mnapoli/silly/src/Application.php(95): Invoker\Invoker->call()
#3 /var/azuracast/www/vendor/symfony/console/Command/Command.php(297): Silly\Application->Silly\{closure}()
#4 /var/azuracast/www/vendor/symfony/console/Application.php(996): Symfony\Component\Console\Command\Command->run()
#5 /var/azuracast/www/vendor/symfony/console/Application.php(295): Symfony\Component\Console\Application->doRunCommand()
#6 /var/azuracast/www/vendor/symfony/console/Application.php(167): Symfony\Component\Console\Application->doRun()
#7 /var/azuracast/www/bin/console(17): Symfony\Component\Console\Application->run()
#8 {main}
  thrown in /var/azuracast/www/src/Console/Command/SyncCommand.php on line 12

Fatal error: Uncaught TypeError: App\Console\Command\SyncCommand::__invoke(): Argument #2 ($task) must be of type string, null given in /var/azuracast/www/src/Console/Command/SyncCommand.php on line 12

TypeError: App\Console\Command\SyncCommand::__invoke(): Argument #2 ($task) must be of type string, null given in /var/azuracast/www/src/Console/Command/SyncCommand.php on line 12

Call Stack:
    0.0002     391536   1. {main}() /var/azuracast/www/bin/console:0
    0.4970   15427528   2. App\Console\Application->run($input = ???, $output = ???) /var/azuracast/www/bin/console:17
    0.5171   15739416   3. App\Console\Application->doRun($input = class Symfony\Component\Console\Input\ArgvInput { private $tokens = [0 => 'sync:run']; private $parsed = []; protected $definition = class Symfony\Component\Console\Input\InputDefinition { private $arguments = [...]; private $requiredCount = 1; private $lastArrayArgument = NULL; private $lastOptionalArgument = class Silly\Input\InputArgument { ... }; private $options = [...]; private $negations = [...]; private $shortcuts = [...] }; protected $stream = NULL; protected $options = []; protected $arguments = ['command' => 'sync:run']; protected $interactive = TRUE }, $output = class Symfony\Component\Console\Output\ConsoleOutput { private $stderr = class Symfony\Component\Console\Output\StreamOutput { private $stream = resource(543) of type (stream); private ${Symfony\Component\Console\Output\Output}verbosity = 32; private ${Symfony\Component\Console\Output\Output}formatter = class Symfony\Component\Console\Formatter\OutputFormatter { ... } }; private $consoleSectionOutputs = []; private ${Symfony\Component\Console\Output\StreamOutput}stream = resource(535) of type (stream); private ${Symfony\Component\Console\Output\Output}verbosity = 32; private ${Symfony\Component\Console\Output\Output}formatter = class Symfony\Component\Console\Formatter\OutputFormatter { private $decorated = TRUE; private $styles = [...]; private $styleStack = class Symfony\Component\Console\Formatter\OutputFormatterStyleStack { ... } } }) /var/azuracast/www/vendor/symfony/console/Application.php:167
    0.5177   15743208   4. App\Console\Application->doRunCommand($command = class Silly\Command\Command { private ${Symfony\Component\Console\Command\Command}application = class App\Console\Application { private ${Silly\Application}expressionParser = class Silly\Command\ExpressionParser { ... }; private ${Silly\Application}invoker = class Invoker\Invoker { ... }; private ${Silly\Application}container = class DI\Container { ... }; private ${Symfony\Component\Console\Application}commands = [...]; private ${Symfony\Component\Console\Application}wantHelps = FALSE; private ${Symfony\Component\Console\Application}runningCommand = ...; private ${Symfony\Component\Console\Application}name = 'AzuraCast Command Line Tools (production)'; private ${Symfony\Component\Console\Application}version = '0.14.1'; private ${Symfony\Component\Console\Application}commandLoader = NULL; private ${Symfony\Component\Console\Application}catchExceptions = TRUE; private ${Symfony\Component\Console\Application}autoExit = TRUE; private ${Symfony\Component\Console\Application}definition = class Symfony\Component\Console\Input\InputDefinition { ... }; private ${Symfony\Component\Console\Application}helperSet = class Symfony\Component\Console\Helper\HelperSet { ... }; private ${Symfony\Component\Console\Application}dispatcher = class Azura\SlimCallableEventDispatcher\SlimCallableEventDispatcher { ... }; private ${Symfony\Component\Console\Application}terminal = class Symfony\Component\Console\Terminal { ... }; private ${Symfony\Component\Console\Application}defaultCommand = 'list'; private ${Symfony\Component\Console\Application}singleCommand = FALSE; private ${Symfony\Component\Console\Application}initialized = TRUE; private ${Symfony\Component\Console\Application}signalRegistry = class Symfony\Component\Console\SignalRegistry\SignalRegistry { ... }; private ${Symfony\Component\Console\Application}signalsToDispatchEvent = [...] }; private ${Symfony\Component\Console\Command\Command}name = 'sync:run'; private ${Symfony\Component\Console\Command\Command}processTitle = NULL; private ${Symfony\Component\Console\Command\Command}aliases = []; private ${Symfony\Component\Console\Command\Command}definition = class Symfony\Component\Console\Input\InputDefinition { private $arguments = [...]; private $requiredCount = 0; private $lastArrayArgument = NULL; private $lastOptionalArgument = class Silly\Input\InputArgument { ... }; private $options = [...]; private $negations = [...]; private $shortcuts = [...] }; private ${Symfony\Component\Console\Command\Command}hidden = FALSE; private ${Symfony\Component\Console\Command\Command}help = ''; private ${Symfony\Component\Console\Command\Command}description = 'Run one or more scheduled synchronization tasks.'; private ${Symfony\Component\Console\Command\Command}fullDefinition = class Symfony\Component\Console\Input\InputDefinition { private $arguments = [...]; private $requiredCount = 1; private $lastArrayArgument = NULL; private $lastOptionalArgument = class Silly\Input\InputArgument { ... }; private $options = [...]; private $negations = [...]; private $shortcuts = [...] }; private ${Symfony\Component\Console\Command\Command}ignoreValidationErrors = FALSE; private ${Symfony\Component\Console\Command\Command}code = class Closure { public $static = [...]; public $this = class App\Console\Application { ... }; public $parameter = [...] }; private ${Symfony\Component\Console\Command\Command}synopsis = []; private ${Symfony\Component\Console\Command\Command}usages = []; private ${Symfony\Component\Console\Command\Command}helperSet = class Symfony\Component\Console\Helper\HelperSet { private $helpers = [...]; private $command = NULL } }, $input = class Symfony\Component\Console\Input\ArgvInput { private $tokens = [0 => 'sync:run']; private $parsed = []; protected $definition = class Symfony\Component\Console\Input\InputDefinition { private $arguments = [...]; private $requiredCount = 1; private $lastArrayArgument = NULL; private $lastOptionalArgument = class Silly\Input\InputArgument { ... }; private $options = [...]; private $negations = [...]; private $shortcuts = [...] }; protected $stream = NULL; protected $options = []; protected $arguments = ['command' => 'sync:run']; protected $interactive = TRUE }, $output = class Symfony\Component\Console\Output\ConsoleOutput { private $stderr = class Symfony\Component\Console\Output\StreamOutput { private $stream = resource(543) of type (stream); private ${Symfony\Component\Console\Output\Output}verbosity = 32; private ${Symfony\Component\Console\Output\Output}formatter = class Symfony\Component\Console\Formatter\OutputFormatter { ... } }; private $consoleSectionOutputs = []; private ${Symfony\Component\Console\Output\StreamOutput}stream = resource(535) of type (stream); private ${Symfony\Component\Console\Output\Output}verbosity = 32; private ${Symfony\Component\Console\Output\Output}formatter = class Symfony\Component\Console\Formatter\OutputFormatter { private $decorated = TRUE; private $styles = [...]; private $styleStack = class Symfony\Component\Console\Formatter\OutputFormatterStyleStack { ... } } }) /var/azuracast/www/vendor/symfony/console/Application.php:295

[2021-09-24T08:49:24.809752+00:00] AzuraCast.CRITICAL: Fatal error: Uncaught TypeError: App\Console\Command\SyncCommand::__invoke(): Argument #2 ($task) must be of type string, null given in /var/azuracast/www/src/Console/Command/SyncCommand.php:12 Stack trace: #0 [internal function]: App\Console\Command\SyncCommand->__invoke() #1 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(74): call_user_func_array() #2 /var/azuracast/www/vendor/mnapoli/silly/src/Application.php(95): Invoker\Invoker->call() #3 /var/azuracast/www/vendor/symfony/console/Command/Command.php(297): Silly\Application->Silly\{closure}() #4 /var/azuracast/www/vendor/symfony/console/Application.php(996): Symfony\Component\Console\Command\Command->run() #5 /var/azuracast/www/vendor/symfony/console/Application.php(295): Symfony\Component\Console\Application->doRunCommand() #6 /var/azuracast/www/vendor/symfony/console/Application.php(167): Symfony\Component\Console\Application->doRun() #7 /var/azuracast/www/bin/console(17): Symfony\Component\Console\Application->run() #8 {main}   thrown in /var/azuracast/www/src/Console/Command/SyncCommand.php on line 12 [] []
---
root@mail:/var/azuracast# ./docker.sh cli sync:run medium
Creating azuracast_web_run ... done
Starting up AzuraCast services...
Services started up and ready!
[2021-09-24T08:46:27.954139+00:00] AzuraCast.NOTICE: Running sync task: 5-Minute Sync {"force":false} []
[2021-09-24T08:46:28.046102+00:00] AzuraCast.ERROR: Symfony\Component\Messenger\Exception\TransportException: Socket error 111: Connection refused (uncaught exception) at /var/azuracast/www/vendor/symfony/beanstalkd-messenger/Transport/Connection.php line 159 while running console command `sync:run` {"exception":"[object] (Symfony\\Component\\Messenger\\Exception\\TransportException(code: 0): Socket error 111: Connection refused at /var/azuracast/www/vendor/symfony/beanstalkd-messenger/Transport/Connection.php:159)\n[previous exception] [object] (Pheanstalk\\Exception\\ConnectionException(code: 0): Socket error 111: Connection refused at /var/azuracast/www/vendor/pda/pheanstalk/src/Socket/SocketSocket.php:52)"} []
[2021-09-24T08:46:28.046679+00:00] AzuraCast.WARNING: Console command `sync:run` exited with error code 1. [] []

In Connection.php line 159:

  Socket error 111: Connection refused


In SocketSocket.php line 52:

  Socket error 111: Connection refused


sync:run [--force] [--] [<task>]
```

**Comment by groxana** [comment]
Hello,

it seems being and issue with beanstalk
`
● beanstalkd.service - Simple, fast work queue
     Loaded: loaded (/lib/systemd/system/beanstalkd.service; disabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Fri 2021-11-19 18:00:41 UTC; 1s ago
       Docs: man:beanstalkd(1)
    Process: 124008 ExecStart=/usr/bin/beanstalkd -l ${BEANSTALKD_LISTEN_ADDR} -p ${BEANSTALKD_LISTEN_PORT} $BEANSTALKD_EXTRA (code=exited, status=111)
   Main PID: 124008 (code=exited, status=111)
`

i fixed mine by forcing  beanstalk.service to listen on loopback ( 127.0.0.1 ) and default port and everything works now , including WebSocket errors

`
● beanstalkd.service - Simple, fast work queue
     Loaded: loaded (/lib/systemd/system/beanstalkd.service; disabled; vendor preset: enabled)
     Active: active (running) since Fri 2021-11-19 18:03:59 UTC; 3s ago
       Docs: man:beanstalkd(1)
   Main PID: 124239 (beanstalkd)
      Tasks: 1 (limit: 9025)
     CGroup: /system.slice/beanstalkd.service
             └─124239 /usr/bin/beanstalkd -l 127.0.0.1 -p  -z 262140
`

Steps done:


- sudo nano /lib/systemd/system/beanstalkd.service

`ExecStart=/usr/bin/beanstalkd -l 127.0.0.1 -p 11300 $BEANSTALKD_EXTRA`

- sudo systemctl daemon-reload
- sudo service beanstalkd restart
