### ISSUE TITLE
Dj Streaming Error [docker station container, Ffmpeg_decoder related]

### ISSUE THREAD

**Issue by dvdred** [AzuraCast/AzuraCast#5075]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #fef3932 (2022-02-06 1:58) • Docker • PHP 8.1 

### What happened?

After the latest update, DJs can no longer stream to the radio (their playlists are made up of mp3 files).
As soon as they connect, the radio broadcasts background noise for a few seconds and then disconnects the DJ. Looking at the logs, I found following relevant lines:
```
...
2022/02/05 18:22:52 [lang:3] DJ Source connected! Last authenticated DJ: XYZ - [("Authorization", "Basic xxxx"), ("Host", "xxxx:8005"), ("User-Agent", "libshout/2.4.1"), ("Content-Type", "audio/mpeg"), ("ice-public", "1"), ("ice-name", "yyy!"), ("ice-description", "zzz!"), ("ice-genre", "Live Mix"), ("ice-url", "https://zzzz/public/zzz/"), ("ice-irc", " "), ("ice-aim", " "), ("ice-icq", " "), ("ice-audio-info", "bitrate=128")]
2022/02/05 18:22:52 [lang:3] API djon - Sending POST request to 'http://web/api/internal/1/djon' with body: { "user": "XYZ" }
2022/02/05 18:22:52 [lang:3] API feedback - Response (200): OK
2022/02/05 18:22:53 [lang:3] API nextsong - Response (200): annotate:title="WARNING (REMIX)",artist="... SR",duration="187.38",song_id="8265951f3fcc958edaf7bc2c5dcb88e7",media_id="39819",liq_amplify="0.00dB",playlist_id="31":/....
2022/02/05 18:22:53 [lang:3] API djon - Response (200): /var/azuracast/stations/..../temp/XYZ/stream_20220205-182252.mp3
2022/02/05 18:22:53 [input_streamer:3] Decoding...
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
[mp3 @ 0x7f1244004380] Format mp3 detected only with low score of 1, misdetection possible!
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
2022/02/05 18:22:53 [input_streamer:2] Feeding stopped: Ffmpeg_decoder.End_of_file.
2022/02/05 18:22:53 [lang:3] API djoff - Sending POST request to 'http://web/api/internal/1/djoff' with body: { "user": "XYZ" }
2022/02/05 18:22:53 [lang:3] API djoff - Response (200): true
2022/02/05 18:22:53 [next_song:3] Prepared "..." (RID 41).
2022/02/05 18:22:53 [lang:3] AutoDJ is ready!
...
```

And the station container reported this error:
```
stations_1  | 2022-02-05 18:18:36,020 INFO exited: station_1_backend (terminated by SIGSEGV (core dumped); not expected)
stations_1  | 2022-02-05 18:18:37,023 INFO spawned: 'station_1_backend' with pid 2095

```

**I was able to restore the correct behavior of the radio** by pointing to the previous azuracast_stations container image in the _docker-compose.override.yml_ file :
...
  stations:
    image: 'ghcr.io/azuracast/radio:stable'
...

**Comment by SC2Mitch** [comment]
reviewing, standby.

**Comment by SC2Mitch** [comment]
Was unable to replicate this on my localhost machine, my logs are below. Can you provide some of the songs you're attempting to play so I can test them on my dev machine? Cheers. 

```2022/02/06 13:30:33 [lang:3] API auth - Sending POST request to 'http://web/api/internal/1/auth' with body: { "password": "test", "user": "john" }
2022/02/06 13:30:33 [lang:3] API auth - Response (200): true
2022/02/06 13:30:33 [lang:3] DJ Source connected! Last authenticated DJ: john - [("Authorization", "Basic am9objp0ZXN0"), ("Host", "localhost:8005"), ("User-Agent", "libshout/2.4.1"), ("Content-Type", "audio/mpeg"), ("ice-public", "0"), ("ice-name", " "), ("ice-description", "This stream is online for testing purposes!"), ("ice-genre", "Live Mix"), ("ice-url", "https://www.mixxx.org"), ("ice-irc", " "), ("ice-aim", " "), ("ice-icq", " "), ("ice-audio-info", "bitrate=256")]
2022/02/06 13:30:33 [lang:3] API djon - Sending POST request to 'http://web/api/internal/1/djon' with body: { "user": "john" }
2022/02/06 13:30:34 [lang:3] API djon - Response (200): true
2022/02/06 13:30:34 [input_streamer:3] Decoding...
2022/02/06 13:30:39 [live_fallback:3] Switch to map_metadata_0 with transition.
2022/02/06 13:30:39 [map_metadata_0:3] Inserting missing metadata.
2022/02/06 13:30:40 [lang:3] API auth - Sending POST request to 'http://web/api/internal/1/auth' with body: { "password": "test", "user": "john" }
2022/02/06 13:30:41 [lang:3] API auth - Response (200): true
2022/02/06 13:30:41 [input_streamer:3] New metadata chunk ? -- Aaron Gordon - 9 OUT OF 10 (Official Music Video).
2022/02/06 13:33:12 [lang:3] API auth - Sending POST request to 'http://web/api/internal/1/auth' with body: { "password": "test", "user": "john" }
2022/02/06 13:33:12 [lang:3] API auth - Response (200): true
2022/02/06 13:33:12 [input_streamer:3] New metadata chunk ? -- W.A.S.P. - Mephisto Waltz.
```

**Comment by dvdred** [comment]
Thanks for the quick response.
I doubt it could depend on the songs: we use Mixxx as a streaming program (from various pc / mac / linux) and we all have the same problem even with the microphone audio only. All of us, using the same configurations and each with its own songs, are able to connect without problems using the container image 'ghcr.io/azuracast/radio:stable', while we have the problem using the latest.
If necessary, as soon as possible, I can replicate the problem and include the complete logs
I don't know if it is useful but these are the characteristics of the operating environment: VM CentOS 7 x64, 4 vCpu 2 i7 3.40GHz [~ 0,5 load], 6GB Ram [40% free] Docker version 20.10.12

**Comment by Vaalyn** [comment]
I have just tested this on the latest Rolling-Release on my test server with Mixxx 2.3.1 (Windows and macOS) with the Livestreaming settings set to 128kbps Stereo MP3 as well as using the types `Icecast 2` and `Shoutcast 1` and it works without crashing on both.

When I manually disconnect from the stream I get the `Invalid return value 0 for stream protocol` log entries too but I think those are just informational from FFmpeg it seeing no further data in the disconnected stream.

I don't see the `Format mp3 detected only with low score of 1, misdetection possible!` though.

Since your LS actually segfaults with a core dump this is most likely related to the actual data that is processed by LS / FFmpeg.

What Mixxx version are you using and are they all the same or different versions?

Just to be sure I'd also ask you if you can provide us with a file that you tried to play when it crashes.

Could you provide us with the core dump that LS generated, I'd like to try finding out where in LS it crashed via gdb.
You should find the core dump in `/var/lib/docker/volumes/azuracast_station_data/_data/<station name>/config/` and the file should be named something with dump in it.

**Comment by LordHelmchen666** [comment]
I have the same problem. I use Mixxx 2.3.1. Also tried IDJC 0.9.3 and got identical error. Using `image: 'ghcr.io/azuracast/radio:stable'` also fixes for me.

**Comment by Vaalyn** [comment]
> I have the same problem. I use Mixxx 2.3.1. Also tried IDJC 0.9.3 and got identical error. Using `image: 'ghcr.io/azuracast/radio:stable'` also fixes for me.

Can you provide us with the core dump file I mentioned too?

Since I'm not able to see this on my test server, could you post your LS config?
Maybe there is some setting that provokes this. 🤔

**Comment by Vaalyn** [comment]
I have finally managed to get my test installation to crash and I attached gdb to it to see why it is crashing.

There have been a few commits on the LS 2.0.3-preview branch since the commit that the current `azuracast/radio:latest` uses so I'll first try to compile LS from that one, check this again and if it still crashes I'll notify the LS team about this and see how we can resolve it.

gdb trace:
```
gdb liquidsoap
(gdb) r liquidsoap.liq
Starting program: /usr/local/bin/liquidsoap liquidsoap.liq

...

2022/02/06 19:38:08 [lang:3] API auth - Response (200): true
2022/02/06 19:38:08 [input_streamer:3] New metadata chunk ? -- Daniel ingram - Time To Be Awesome.

Thread 5 "liquidsoap" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7f41affff700 (LWP 6620)]
0x000055766da4555e in caml_taglib_tag_set_string (t=139920220917352, name=93967137988728, v=139920216452504) at taglib_stubs.cc:446
446	taglib_stubs.cc: No such file or directory.

(gdb) thread apply all bt

Thread 15 (Thread 0x7f41acff9700 (LWP 6657)):
#0  0x00007f41d533012b in __GI___select (nfds=53, readfds=readfds@entry=0x7f41acff7900, writefds=writefds@entry=0x7f41acff7980, exceptfds=exceptfds@entry=0x7f41acff7a00, timeout=timeout@entry=0x7f41acff78b0) at ../sysdeps/unix/sysv/linux/select.c:41
#1  0x000055766da8e826 in unix_select (readfds=<optimized out>, writefds=<optimized out>, exceptfds=<optimized out>, timeout=93967137595200) at select.c:94
#2  0x000055766d8a79c4 in camlTutils__wait_1188 () at tools/tutils.ml:371
#3  0x000055766d766f98 in camlHarbor_input__f_1589 () at sources/harbor_input.ml:122
#4  0x000055766d766d22 in camlHarbor_input__read_1578 () at sources/harbor_input.ml:128
#5  0x000055766dab5bcc in caml_start_program ()
#6  0x000055766daaaf98 in caml_callback3_exn (closure=<optimized out>, arg1=<optimized out>, arg2=arg2@entry=1, arg3=arg3@entry=8193) at callback.c:124
#7  0x000055766da4c4f4 in ocaml_avio_read_callback (private=0x7f4190000b60, buf=0x7f419000c3c0 "Tn\322\356\230[\261\n\a\207\222^U]\240\003\305\024y\344}\377\373\222D\n\200\002\267&V\006c", buf_size=4096) at av_stubs.c:295
#8  0x00007f41d73cfa25 in avio_read () at /lib/x86_64-linux-gnu/libavformat.so.58
#9  0x00007f41d75145b1 in  () at /lib/x86_64-linux-gnu/libavformat.so.58
#10 0x00007f41d74774b4 in  () at /lib/x86_64-linux-gnu/libavformat.so.58
#11 0x00007f41d7519783 in  () at /lib/x86_64-linux-gnu/libavformat.so.58
#12 0x00007f41d751a04b in  () at /lib/x86_64-linux-gnu/libavformat.so.58
#13 0x00007f41d751aed8 in av_read_frame () at /lib/x86_64-linux-gnu/libavformat.so.58
#14 0x000055766da4f122 in read_packet (av=0x7f4190000ce0, av=0x7f4190000ce0, packet=0x7f419000bcc0) at av_stubs.c:991
#15 ocaml_av_read_input (_packet=<optimized out>, _frame=<optimized out>, _av=<optimized out>) at av_stubs.c:1033
#16 0x000055766d8fd7a9 in camlAv__read_input_inner_1436 () at av/av.ml:216
#17 0x000055766d6d03d0 in camlFfmpeg_decoder__f_1228 () at decoder/ffmpeg_decoder.ml:662
#18 0x000055766d764241 in camlHarbor_input__fun_5949 () at sources/harbor_input.ml:163
#19 0x000055766d8a6457 in camlTutils__process_730 () at tools/tutils.ml:175
#20 0x000055766d9d9d35 in camlThread__fun_314 () at thread.ml:41
#21 0x000055766dab5bcc in caml_start_program ()
#22 0x000055766daaaf01 in caml_callback_exn (closure=closure@entry=139920541976280, arg=<optimized out>, arg@entry=1) at callback.c:111
#23 0x000055766da89a80 in caml_thread_start (arg=0x7f419800e620) at st_stubs.c:539
#24 0x00007f41d5434609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#25 0x00007f41d533a293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```
