### ISSUE TITLE
Problem update Ansible 20.04

### ISSUE THREAD

**Issue by stemvantwente** [AzuraCast/AzuraCast#5451]
### Installation Method

Ansible Installation

### AzuraCast Release Channel

Rolling Release Channel

### What happened?

New server had some errors but manged to fix them all

Errors:
TASK [init : Update pip components] *
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: No module named pkg_resources
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to import the required Python library (setuptools) on server ip .........'s Python /usr/bin/python. Please read module documentation and install in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"}

Fixed this one with command in ssh: update-alternatives --install /usr/bin/python python /usr/bin/python3 10 

When all went true I got he error when I visited the webpage:
azuracast Slim Application Error A website error has occurred. Sorry for the temporary inconvenience.

So now I did update --full and now all is down with allot errors

### Relevant log output

```shell
TASK [azuracast-setup : Run AzuraCast Setup (Install Mode)] *********************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "php /var/azuracast/www/bin/console azuracast:setup", "delta": "0:00:00.076470", "end": "2022-06-01 20:32:13.911734", "msg": "non-zero return code", "rc": 255, "start": "2022-06-01 20:32:13.835264", "stderr": "[2022-06-01T18:32:13.905660+00:00] AzuraCast.ALERT: Fatal Error (E_ERROR): Uncaught RedisException: No such file or directory in /var/azuracast/www_tmp/CompiledContainer.php:245 Stack trace: #0 /var/azuracast/www_tmp/CompiledContainer.php(245): Redis->connect() #1 [internal function]: CompiledContainer::{closure}() #2 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(74): call_user_func_array() #3 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(121): Invoker\\Invoker->call() #4 /var/azuracast/www_tmp/CompiledContainer.php(252): DI\\CompiledContainer->resolveFactory() #5 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(57): CompiledContainer->get11() #6 /var/azuracast/www_tmp/CompiledContainer.php(273): DI\\CompiledContainer->get() #7 [internal function]: CompiledContainer::{closure}() #8 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(74): call_user_func_array() #9 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(121): Invoker\\Invoker->call() #10 /var/azuracast/www_tmp/CompiledContainer.php(278): DI\\CompiledContainer->resolveFactory() #11 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(57): CompiledContainer->get12() #12 /var/azuracast/www_tmp/CompiledContainer.php(288): DI\\CompiledContainer->get() #13 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(57): CompiledContainer->get14() #14 /var/azuracast/www/vendor/php-di/php-di/src/Invoker/FactoryParameterResolver.php(63): DI\\CompiledContainer->get() #15 /var/azuracast/www/vendor/php-di/invoker/src/ParameterResolver/ResolverChain.php(31): DI\\Invoker\\FactoryParameterResolver->getParameters() #16 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(58): Invoker\\ParameterResolver\\ResolverChain->getParameters() #17 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(121): Invoker\\Invoker->call() #18 /var/azuracast/www_tmp/CompiledContainer.php(295): DI\\CompiledContainer->resolveFactory() #19 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(57): CompiledContainer->get15() #20 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Reference.php(44): DI\\CompiledContainer->get() #21 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(56): DI\\Definition\\Reference->resolve() #22 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ParameterResolver.php(73): DI\\Definition\\Resolver\\ResolverDispatcher->resolve() #23 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php(124): DI\\Definition\\Resolver\\ParameterResolver->resolveParameters() #24 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php(56): DI\\Definition\\Resolver\\ObjectCreator->createInstance() #25 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(61): DI\\Definition\\Resolver\\ObjectCreator->resolve() #26 /var/azuracast/www/vendor/php-di/php-di/src/Container.php(356): DI\\Definition\\Resolver\\ResolverDispatcher->resolve() #27 /var/azuracast/www/vendor/php-di/php-di/src/Container.php(136): DI\\Container->resolveDefinition() #28 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(68): DI\\Container->get() #29 /var/azuracast/www/vendor/php-di/php-di/src/Invoker/FactoryParameterResolver.php(63): DI\\CompiledContainer->get() #30 /var/azuracast/www/vendor/php-di/invoker/src/ParameterResolver/ResolverChain.php(31): DI\\Invoker\\FactoryParameterResolver->getParameters() #31 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(58): Invoker\\ParameterResolver\\ResolverChain->getParameters() #32 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(121): Invoker\\Invoker->call() #33 /var/azuracast/www_tmp/CompiledContainer.php(356): DI\\CompiledContainer->resolveFactory() #34 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(57): CompiledContainer->get18() #35 /var/azuracast/www/src/AppFactory.php(41): DI\\CompiledContainer->get() #36 /var/azuracast/www/bin/console(13): App\\AppFactory::createCli() #37 {main}   thrown {\"code\":1,\"message\":\"Uncaught RedisException: No such file or directory in /var/azuracast/www_tmp/CompiledContainer.php:245\\nStack trace:\\n#0 /var/azuracast/www_tmp/CompiledContainer.php(245): Redis->connect()\\n#1 [internal function]: CompiledContainer::{closure}()\\n#2 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(74): call_user_func_array()\\n#3 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(121): Invoker\\\\Invoker->call()\\n#4 /var/azuracast/www_tmp/CompiledContainer.php(252): DI\\\\CompiledContainer->resolveFactory()\\n#5 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(57): CompiledContainer->get11()\\n#6 /var/azuracast/www_tmp/CompiledContainer.php(273): DI\\\\CompiledContainer->get()\\n#7 [internal function]: CompiledContainer::{closure}()\\n#8 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(74): call_user_func_array()\\n#9 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(121): Invoker\\\\Invoker->call()\\n#10 /var/azuracast/www_tmp/CompiledContainer.php(278): DI\\\\CompiledContainer->resolveFactory()\\n#11 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(57): CompiledContainer->get12()\\n#12 /var/azuracast/www_tmp/CompiledContainer.php(288): DI\\\\CompiledContainer->get()\\n#13 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(57): CompiledContainer->get14()\\n#14 /var/azuracast/www/vendor/php-di/php-di/src/Invoker/FactoryParameterResolver.php(63): DI\\\\CompiledContainer->get()\\n#15 /var/azuracast/www/vendor/php-di/invoker/src/ParameterResolver/ResolverChain.php(31): DI\\\\Invoker\\\\FactoryParameterResolver->getParameters()\\n#16 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(58): Invoker\\\\ParameterResolver\\\\ResolverChain->getParameters()\\n#17 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(121): Invoker\\\\Invoker->call()\\n#18 /var/azuracast/www_tmp/CompiledContainer.php(295): DI\\\\CompiledContainer->resolveFactory()\\n#19 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(57): CompiledContainer->get15()\\n#20 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Reference.php(44): DI\\\\CompiledContainer->get()\\n#21 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(56): DI\\\\Definition\\\\Reference->resolve()\\n#22 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ParameterResolver.php(73): DI\\\\Definition\\\\Resolver\\\\ResolverDispatcher->resolve()\\n#23 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php(124): DI\\\\Definition\\\\Resolver\\\\ParameterResolver->resolveParameters()\\n#24 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php(56): DI\\\\Definition\\\\Resolver\\\\ObjectCreator->createInstance()\\n#25 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(61): DI\\\\Definition\\\\Resolver\\\\ObjectCreator->resolve()\\n#26 /var/azuracast/www/vendor/php-di/php-di/src/Container.php(356): DI\\\\Definition\\\\Resolver\\\\ResolverDispatcher->resolve()\\n#27 /var/azuracast/www/vendor/php-di/php-di/src/Container.php(136): DI\\\\Container->resolveDefinition()\\n#28 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(68): DI\\\\Container->get()\\n#29 /var/azuracast/www/vendor/php-di/php-di/src/Invoker/FactoryParameterResolver.php(63): DI\\\\CompiledContainer->get()\\n#30 /var/azuracast/www/vendor/php-di/invoker/src/ParameterResolver/ResolverChain.php(31): DI\\\\Invoker\\\\FactoryParameterResolver->getParameters()\\n#31 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(58): Invoker\\\\ParameterResolver\\\\ResolverChain->getParameters()\\n#32 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(121): Invoker\\\\Invoker->call()\\n#33 /var/azuracast/www_tmp/CompiledContainer.php(356): DI\\\\CompiledContainer->resolveFactory()\\n#34 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(57): CompiledContainer->get18()\\n#35 /var/azuracast/www/src/AppFactory.php(41): DI\\\\CompiledContainer->get()\\n#36 /var/azuracast/www/bin/console(13): App\\\\AppFactory::createCli()\\n#37 {main}\\n  thrown\",\"file\":\"/var/azuracast/www_tmp/CompiledContainer.php\",\"line\":245,\"trace\":null} []", "stderr_lines": ["[2022-06-01T18:32:13.905660+00:00] AzuraCast.ALERT: Fatal Error (E_ERROR): Uncaught RedisException: No such file or directory in /var/azuracast/www_tmp/CompiledContainer.php:245 Stack trace: #0 /var/azuracast/www_tmp/CompiledContainer.php(245): Redis->connect() #1 [internal function]: CompiledContainer::{closure}() #2 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(74): call_user_func_array() #3 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(121): Invoker\\Invoker->call() #4 /var/azuracast/www_tmp/CompiledContainer.php(252): DI\\CompiledContainer->resolveFactory() #5 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(57): CompiledContainer->get11() #6 /var/azuracast/www_tmp/CompiledContainer.php(273): DI\\CompiledContainer->get() #7 [internal function]: CompiledContainer::{closure}() #8 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(74): call_user_func_array() #9 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(121): Invoker\\Invoker->call() #10 /var/azuracast/www_tmp/CompiledContainer.php(278): DI\\CompiledContainer->resolveFactory() #11 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(57): CompiledContainer->get12() #12 /var/azuracast/www_tmp/CompiledContainer.php(288): DI\\CompiledContainer->get() #13 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(57): CompiledContainer->get14() #14 /var/azuracast/www/vendor/php-di/php-di/src/Invoker/FactoryParameterResolver.php(63): DI\\CompiledContainer->get() #15 /var/azuracast/www/vendor/php-di/invoker/src/ParameterResolver/ResolverChain.php(31): DI\\Invoker\\FactoryParameterResolver->getParameters() #16 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(58): Invoker\\ParameterResolver\\ResolverChain->getParameters() #17 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(121): Invoker\\Invoker->call() #18 /var/azuracast/www_tmp/CompiledContainer.php(295): DI\\CompiledContainer->resolveFactory() #19 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(57): CompiledContainer->get15() #20 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Reference.php(44): DI\\CompiledContainer->get() #21 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(56): DI\\Definition\\Reference->resolve() #22 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ParameterResolver.php(73): DI\\Definition\\Resolver\\ResolverDispatcher->resolve() #23 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php(124): DI\\Definition\\Resolver\\ParameterResolver->resolveParameters() #24 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php(56): DI\\Definition\\Resolver\\ObjectCreator->createInstance() #25 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(61): DI\\Definition\\Resolver\\ObjectCreator->resolve() #26 /var/azuracast/www/vendor/php-di/php-di/src/Container.php(356): DI\\Definition\\Resolver\\ResolverDispatcher->resolve() #27 /var/azuracast/www/vendor/php-di/php-di/src/Container.php(136): DI\\Container->resolveDefinition() #28 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(68): DI\\Container->get() #29 /var/azuracast/www/vendor/php-di/php-di/src/Invoker/FactoryParameterResolver.php(63): DI\\CompiledContainer->get() #30 /var/azuracast/www/vendor/php-di/invoker/src/ParameterResolver/ResolverChain.php(31): DI\\Invoker\\FactoryParameterResolver->getParameters() #31 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(58): Invoker\\ParameterResolver\\ResolverChain->getParameters() #32 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(121): Invoker\\Invoker->call() #33 /var/azuracast/www_tmp/CompiledContainer.php(356): DI\\CompiledContainer->resolveFactory() #34 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(57): CompiledContainer->get18() #35 /var/azuracast/www/src/AppFactory.php(41): DI\\CompiledContainer->get() #36 /var/azuracast/www/bin/console(13): App\\AppFactory::createCli() #37 {main}   thrown {\"code\":1,\"message\":\"Uncaught RedisException: No such file or directory in /var/azuracast/www_tmp/CompiledContainer.php:245\\nStack trace:\\n#0 /var/azuracast/www_tmp/CompiledContainer.php(245): Redis->connect()\\n#1 [internal function]: CompiledContainer::{closure}()\\n#2 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(74): call_user_func_array()\\n#3 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(121): Invoker\\\\Invoker->call()\\n#4 /var/azuracast/www_tmp/CompiledContainer.php(252): DI\\\\CompiledContainer->resolveFactory()\\n#5 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(57): CompiledContainer->get11()\\n#6 /var/azuracast/www_tmp/CompiledContainer.php(273): DI\\\\CompiledContainer->get()\\n#7 [internal function]: CompiledContainer::{closure}()\\n#8 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(74): call_user_func_array()\\n#9 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(121): Invoker\\\\Invoker->call()\\n#10 /var/azuracast/www_tmp/CompiledContainer.php(278): DI\\\\CompiledContainer->resolveFactory()\\n#11 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(57): CompiledContainer->get12()\\n#12 /var/azuracast/www_tmp/CompiledContainer.php(288): DI\\\\CompiledContainer->get()\\n#13 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(57): CompiledContainer->get14()\\n#14 /var/azuracast/www/vendor/php-di/php-di/src/Invoker/FactoryParameterResolver.php(63): DI\\\\CompiledContainer->get()\\n#15 /var/azuracast/www/vendor/php-di/invoker/src/ParameterResolver/ResolverChain.php(31): DI\\\\Invoker\\\\FactoryParameterResolver->getParameters()\\n#16 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(58): Invoker\\\\ParameterResolver\\\\ResolverChain->getParameters()\\n#17 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(121): Invoker\\\\Invoker->call()\\n#18 /var/azuracast/www_tmp/CompiledContainer.php(295): DI\\\\CompiledContainer->resolveFactory()\\n#19 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(57): CompiledContainer->get15()\\n#20 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Reference.php(44): DI\\\\CompiledContainer->get()\\n#21 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(56): DI\\\\Definition\\\\Reference->resolve()\\n#22 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ParameterResolver.php(73): DI\\\\Definition\\\\Resolver\\\\ResolverDispatcher->resolve()\\n#23 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php(124): DI\\\\Definition\\\\Resolver\\\\ParameterResolver->resolveParameters()\\n#24 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php(56): DI\\\\Definition\\\\Resolver\\\\ObjectCreator->createInstance()\\n#25 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(61): DI\\\\Definition\\\\Resolver\\\\ObjectCreator->resolve()\\n#26 /var/azuracast/www/vendor/php-di/php-di/src/Container.php(356): DI\\\\Definition\\\\Resolver\\\\ResolverDispatcher->resolve()\\n#27 /var/azuracast/www/vendor/php-di/php-di/src/Container.php(136): DI\\\\Container->resolveDefinition()\\n#28 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(68): DI\\\\Container->get()\\n#29 /var/azuracast/www/vendor/php-di/php-di/src/Invoker/FactoryParameterResolver.php(63): DI\\\\CompiledContainer->get()\\n#30 /var/azuracast/www/vendor/php-di/invoker/src/ParameterResolver/ResolverChain.php(31): DI\\\\Invoker\\\\FactoryParameterResolver->getParameters()\\n#31 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(58): Invoker\\\\ParameterResolver\\\\ResolverChain->getParameters()\\n#32 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(121): Invoker\\\\Invoker->call()\\n#33 /var/azuracast/www_tmp/CompiledContainer.php(356): DI\\\\CompiledContainer->resolveFactory()\\n#34 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(57): CompiledContainer->get18()\\n#35 /var/azuracast/www/src/AppFactory.php(41): DI\\\\CompiledContainer->get()\\n#36 /var/azuracast/www/bin/console(13): App\\\\AppFactory::createCli()\\n#37 {main}\\n  thrown\",\"file\":\"/var/azuracast/www_tmp/CompiledContainer.php\",\"line\":245,\"trace\":null} []"], "stdout": "\nFatal error: Uncaught RedisException: No such file or directory in /var/azuracast/www_tmp/CompiledContainer.php:245\nStack trace:\n#0 /var/azuracast/www_tmp/CompiledContainer.php(245): Redis->connect()\n#1 [internal function]: CompiledContainer::{closure}()\n#2 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(74): call_user_func_array()\n#3 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(121): Invoker\\Invoker->call()\n#4 /var/azuracast/www_tmp/CompiledContainer.php(252): DI\\CompiledContainer->resolveFactory()\n#5 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(57): CompiledContainer->get11()\n#6 /var/azuracast/www_tmp/CompiledContainer.php(273): DI\\CompiledContainer->get()\n#7 [internal function]: CompiledContainer::{closure}()\n#8 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(74): call_user_func_array()\n#9 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(121): Invoker\\Invoker->call()\n#10 /var/azuracast/www_tmp/CompiledContainer.php(278): DI\\CompiledContainer->resolveFactory()\n#11 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(57): CompiledContainer->get12()\n#12 /var/azuracast/www_tmp/CompiledContainer.php(288): DI\\CompiledContainer->get()\n#13 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(57): CompiledContainer->get14()\n#14 /var/azuracast/www/vendor/php-di/php-di/src/Invoker/FactoryParameterResolver.php(63): DI\\CompiledContainer->get()\n#15 /var/azuracast/www/vendor/php-di/invoker/src/ParameterResolver/ResolverChain.php(31): DI\\Invoker\\FactoryParameterResolver->getParameters()\n#16 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(58): Invoker\\ParameterResolver\\ResolverChain->getParameters()\n#17 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(121): Invoker\\Invoker->call()\n#18 /var/azuracast/www_tmp/CompiledContainer.php(295): DI\\CompiledContainer->resolveFactory()\n#19 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(57): CompiledContainer->get15()\n#20 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Reference.php(44): DI\\CompiledContainer->get()\n#21 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(56): DI\\Definition\\Reference->resolve()\n#22 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ParameterResolver.php(73): DI\\Definition\\Resolver\\ResolverDispatcher->resolve()\n#23 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php(124): DI\\Definition\\Resolver\\ParameterResolver->resolveParameters()\n#24 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php(56): DI\\Definition\\Resolver\\ObjectCreator->createInstance()\n#25 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(61): DI\\Definition\\Resolver\\ObjectCreator->resolve()\n#26 /var/azuracast/www/vendor/php-di/php-di/src/Container.php(356): DI\\Definition\\Resolver\\ResolverDispatcher->resolve()\n#27 /var/azuracast/www/vendor/php-di/php-di/src/Container.php(136): DI\\Container->resolveDefinition()\n#28 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(68): DI\\Container->get()\n#29 /var/azuracast/www/vendor/php-di/php-di/src/Invoker/FactoryParameterResolver.php(63): DI\\CompiledContainer->get()\n#30 /var/azuracast/www/vendor/php-di/invoker/src/ParameterResolver/ResolverChain.php(31): DI\\Invoker\\FactoryParameterResolver->getParameters()\n#31 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(58): Invoker\\ParameterResolver\\ResolverChain->getParameters()\n#32 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(121): Invoker\\Invoker->call()\n#33 /var/azuracast/www_tmp/CompiledContainer.php(356): DI\\CompiledContainer->resolveFactory()\n#34 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(57): CompiledContainer->get18()\n#35 /var/azuracast/www/src/AppFactory.php(41): DI\\CompiledContainer->get()\n#36 /var/azuracast/www/bin/console(13): App\\AppFactory::createCli()\n#37 {main}\n  thrown in /var/azuracast/www_tmp/CompiledContainer.php on line 245", "stdout_lines": ["", "Fatal error: Uncaught RedisException: No such file or directory in /var/azuracast/www_tmp/CompiledContainer.php:245", "Stack trace:", "#0 /var/azuracast/www_tmp/CompiledContainer.php(245): Redis->connect()", "#1 [internal function]: CompiledContainer::{closure}()", "#2 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(74): call_user_func_array()", "#3 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(121): Invoker\\Invoker->call()", "#4 /var/azuracast/www_tmp/CompiledContainer.php(252): DI\\CompiledContainer->resolveFactory()", "#5 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(57): CompiledContainer->get11()", "#6 /var/azuracast/www_tmp/CompiledContainer.php(273): DI\\CompiledContainer->get()", "#7 [internal function]: CompiledContainer::{closure}()", "#8 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(74): call_user_func_array()", "#9 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(121): Invoker\\Invoker->call()", "#10 /var/azuracast/www_tmp/CompiledContainer.php(278): DI\\CompiledContainer->resolveFactory()", "#11 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(57): CompiledContainer->get12()", "#12 /var/azuracast/www_tmp/CompiledContainer.php(288): DI\\CompiledContainer->get()", "#13 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(57): CompiledContainer->get14()", "#14 /var/azuracast/www/vendor/php-di/php-di/src/Invoker/FactoryParameterResolver.php(63): DI\\CompiledContainer->get()", "#15 /var/azuracast/www/vendor/php-di/invoker/src/ParameterResolver/ResolverChain.php(31): DI\\Invoker\\FactoryParameterResolver->getParameters()", "#16 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(58): Invoker\\ParameterResolver\\ResolverChain->getParameters()", "#17 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(121): Invoker\\Invoker->call()", "#18 /var/azuracast/www_tmp/CompiledContainer.php(295): DI\\CompiledContainer->resolveFactory()", "#19 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(57): CompiledContainer->get15()", "#20 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Reference.php(44): DI\\CompiledContainer->get()", "#21 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(56): DI\\Definition\\Reference->resolve()", "#22 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ParameterResolver.php(73): DI\\Definition\\Resolver\\ResolverDispatcher->resolve()", "#23 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php(124): DI\\Definition\\Resolver\\ParameterResolver->resolveParameters()", "#24 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php(56): DI\\Definition\\Resolver\\ObjectCreator->createInstance()", "#25 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(61): DI\\Definition\\Resolver\\ObjectCreator->resolve()", "#26 /var/azuracast/www/vendor/php-di/php-di/src/Container.php(356): DI\\Definition\\Resolver\\ResolverDispatcher->resolve()", "#27 /var/azuracast/www/vendor/php-di/php-di/src/Container.php(136): DI\\Container->resolveDefinition()", "#28 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(68): DI\\Container->get()", "#29 /var/azuracast/www/vendor/php-di/php-di/src/Invoker/FactoryParameterResolver.php(63): DI\\CompiledContainer->get()", "#30 /var/azuracast/www/vendor/php-di/invoker/src/ParameterResolver/ResolverChain.php(31): DI\\Invoker\\FactoryParameterResolver->getParameters()", "#31 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(58): Invoker\\ParameterResolver\\ResolverChain->getParameters()", "#32 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(121): Invoker\\Invoker->call()", "#33 /var/azuracast/www_tmp/CompiledContainer.php(356): DI\\CompiledContainer->resolveFactory()", "#34 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(57): CompiledContainer->get18()", "#35 /var/azuracast/www/src/AppFactory.php(41): DI\\CompiledContainer->get()", "#36 /var/azuracast/www/bin/console(13): App\\AppFactory::createCli()", "#37 {main}", "  thrown in /var/azuracast/www_tmp/CompiledContainer.php on line 245"]}
```

**Comment by SlvrEagle23** [comment]
@stemvantwente You may have to try running `./update.sh --full` again...really not sure what's causing this in some circumstances.

**Comment by stemvantwente** [comment]
@SlvrEagle23 

I went back to my old version wish is working perfect, I think I just wait for some more updates and try again then, worked for me before, thnx for the reply back!

Greets
Roy

**Comment by SC2Mitch** [comment]
If you run into issues let us know, going to close this then.
