### ISSUE TITLE
Attempting to download Streamer Recordings returns Unknown named parameter $id

### ISSUE THREAD

**Issue by fidegr** [AzuraCast/AzuraCast#5452]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### What happened?

-- EDITED BY SC2MITCH
Attempting to download a streamer recording returns the following error to be shown: `Unknown named parameter $id `, here's the trace from the Slim Application Error.  

--

Since the last update it does not give this error when trying to download the recordings.

![image](https://user-images.githubusercontent.com/16152034/171494920-88b19547-f8d5-409a-bf04-b8da91eab67b.png)

### Relevant log output

```
Details
Type: Error
Code: 0
Message: Unknown named parameter $id
File: /var/azuracast/www/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponseNamedArgs.php
Line: 47
Trace
#0 /var/azuracast/www/vendor/slim/slim/Slim/Routing/Route.php(384): Slim\Handlers\Strategies\RequestResponseNamedArgs->__invoke()
#1 /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\Routing\Route->handle()
#2 /var/azuracast/www/src/Middleware/Permissions.php(48): Slim\MiddlewareDispatcher->handle()
#3 /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): App\Middleware\Permissions->__invoke()
#4 /var/azuracast/www/src/Middleware/RequireStation.php(26): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#5 /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(209): App\Middleware\RequireStation->__invoke()
#6 /var/azuracast/www/src/Middleware/GetStation.php(50): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#7 /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(209): App\Middleware\GetStation->process()
#8 /var/azuracast/www/src/Middleware/Module/Api.php(53): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#9 /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(209): App\Middleware\Module\Api->__invoke()
#10 /var/azuracast/www/src/Middleware/Auth/AbstractAuth.php(46): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#11 /var/azuracast/www/src/Middleware/Auth/ApiAuth.php(40): App\Middleware\Auth\AbstractAuth->process()
#12 /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(209): App\Middleware\Auth\ApiAuth->process()
#13 /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#14 /var/azuracast/www/vendor/slim/slim/Slim/Routing/Route.php(341): Slim\MiddlewareDispatcher->handle()
#15 /var/azuracast/www/vendor/slim/slim/Slim/Routing/RouteRunner.php(84): Slim\Routing\Route->run()
#16 /var/azuracast/www/src/Middleware/WrapExceptionsWithRequestData.php(26): Slim\Routing\RouteRunner->handle()
#17 /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(209): App\Middleware\WrapExceptionsWithRequestData->process()
#18 /var/azuracast/www/src/Middleware/EnforceSecurity.php(47): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#19 /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(209): App\Middleware\EnforceSecurity->process()
#20 /var/azuracast/www/src/Middleware/InjectRouter.php(34): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#21 /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(209): App\Middleware\InjectRouter->process()
#22 /var/azuracast/www/src/Middleware/InjectRateLimit.php(32): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#23 /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(209): App\Middleware\InjectRateLimit->process()
#24 /var/azuracast/www/src/Middleware/ReopenEntityManagerMiddleware.php(27): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#25 /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(209): App\Middleware\ReopenEntityManagerMiddleware->process()
#26 /var/azuracast/www/vendor/slim/slim/Slim/Middleware/BodyParsingMiddleware.php(68): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#27 /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\BodyParsingMiddleware->process()
#28 /var/azuracast/www/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(59): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#29 /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\RoutingMiddleware->process()
#30 /var/azuracast/www/src/Middleware/RemoveSlashes.php(38): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#31 /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): App\Middleware\RemoveSlashes->process()
#32 /var/azuracast/www/src/Middleware/ApplyXForwardedProto.php(29): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#33 /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): App\Middleware\ApplyXForwardedProto->process()
#34 /var/azuracast/www/src/Middleware/InjectSession.php(79): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#35 /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(209): App\Middleware\InjectSession->process()
#36 /var/azuracast/www/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(107): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#37 /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\ErrorMiddleware->process()
#38 /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#39 /var/azuracast/www/vendor/slim/slim/Slim/App.php(215): Slim\MiddlewareDispatcher->handle()
#40 /var/azuracast/www/vendor/slim/slim/Slim/App.php(199): Slim\App->handle()
#41 /var/azuracast/www/web/index.php(16): Slim\App->run()
#42 {main}
```

**Comment by Spereztorrealba** [comment]
I have seen this too.

**Comment by SC2Mitch** [comment]
Thanks, reproduced and extra logs added to your post.
