### ISSUE TITLE
Manually running Sync Tasks results in a "404 Not Found"

### ISSUE THREAD

**Issue by Vaalyn** [AzuraCast/AzuraCast#5840]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#107482f (2022-11-09 7:48)

### What happened?

When running any of the `Synchronization Tasks` from the `System Debugger` page manually via the `Run Task` button it results in a "404 Not Found" page instead of executing the task.

### Relevant log output

```shell
#0 /var/azuracast/www/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(44): Slim\Middleware\RoutingMiddleware->performRouting()
#1 /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Middleware\RoutingMiddleware->process()
#2 /var/azuracast/www/src/Middleware/RemoveSlashes.php(34): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#3 /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(121): App\Middleware\RemoveSlashes->process()
#4 /var/azuracast/www/src/Middleware/ApplyXForwardedProto.php(29): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#5 /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(121): App\Middleware\ApplyXForwardedProto->process()
#6 /var/azuracast/www/src/Middleware/InjectSession.php(72): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#7 /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(168): App\Middleware\InjectSession->process()
#8 /var/azuracast/www/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(76): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#9 /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Middleware\ErrorMiddleware->process()
#10 /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#11 /var/azuracast/www/vendor/slim/slim/Slim/App.php(199): Slim\MiddlewareDispatcher->handle()
#12 /var/azuracast/www/vendor/slim/slim/Slim/App.php(183): Slim\App->handle()
#13 /var/azuracast/www/web/index.php(16): Slim\App->run()
#14 {main}
```

Also from the logs when this happens:
```
azuracast  | NOTICE: PHP message: PHP Warning:  Undefined variable $customization in /var/azuracast/www/templates/minimal.phtml on line 19
azuracast  | NOTICE: PHP message: PHP Stack trace:
azuracast  | NOTICE: PHP message: PHP   1. {main}() /var/azuracast/www/web/index.php:0
azuracast  | NOTICE: PHP message: PHP   2. Slim\App->run($request = *uninitialized*) /var/azuracast/www/web/index.php:16
azuracast  | NOTICE: PHP message: PHP   3. Slim\App->handle($request = class App\Http\ServerRequest { protected Psr\Http\Message\ServerRequestInterface $serverRequest = class GuzzleHttp\Psr7\ServerRequest { private ${GuzzleHttp\Psr7\Request}method = 'GET'; private ${GuzzleHttp\Psr7\Request}requestTarget = NULL; private ${GuzzleHttp\Psr7\Request}uri = class GuzzleHttp\Psr7\Uri { ... }; private ${GuzzleHttp\Psr7\Request}headers = [...]; private ${GuzzleHttp\Psr7\Request}headerNames = [...]; private ${GuzzleHttp\Psr7\Request}protocol = '1.1'; private ${GuzzleHttp\Psr7\Request}stream = class GuzzleHttp\Psr7\CachingStream { ... }; private $attributes = [...]; private $cookieParams = [...]; private $parsedBody = [...]; private $queryParams = [...]; private $serverParams = [...]; private $uploadedFiles = [...] }; protected array $bodyParsers = ['application/json' => class Closure { virtual $closure = "$this->Slim\Http\{closure}", ... }, 'application/xml' => class Closure { virtual $closure = "$this->Slim\Http\{closure}", ......
azuracast  | NOTICE: PHP message: PHP   4. Slim\MiddlewareDispatcher->handle($request = class App\Http\ServerRequest { protected Psr\Http\Message\ServerRequestInterface $serverRequest = class GuzzleHttp\Psr7\ServerRequest { private ${GuzzleHttp\Psr7\Request}method = 'GET'; private ${GuzzleHttp\Psr7\Request}requestTarget = NULL; private ${GuzzleHttp\Psr7\Request}uri = class GuzzleHttp\Psr7\Uri { ... }; private ${GuzzleHttp\Psr7\Request}headers = [...]; private ${GuzzleHttp\Psr7\Request}headerNames = [...]; private ${GuzzleHttp\Psr7\Request}protocol = '1.1'; private ${GuzzleHttp\Psr7\Request}stream = class GuzzleHttp\Psr7\CachingStream { ... }; private $attributes = [...]; private $cookieParams = [...]; private $parsedBody = [...]; private $queryParams = [...]; private $serverParams = [...]; private $uploadedFiles = [...] }; protected array $bodyParsers = ['application/json' => class Closure { virtual $closure = "$this->Slim\Http\{closure}", ... }, 'application/xml' => class Closure { virtual $closure = "$this->Slim\Htt...
azuracast  | NOTICE: PHP message: PHP   5. {anonymous-class:/var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php:108-123}->handle($request = class App\Http\ServerRequest { protected Psr\Http\Message\ServerRequestInterface $serverRequest = class GuzzleHttp\Psr7\ServerRequest { private ${GuzzleHttp\Psr7\Request}method = 'GET'; private ${GuzzleHttp\Psr7\Request}requestTarget = NULL; private ${GuzzleHttp\Psr7\Request}uri = class GuzzleHttp\Psr7\Uri { ... }; private ${GuzzleHttp\Psr7\Request}headers = [...]; private ${GuzzleHttp\Psr7\Request}headerNames = [...]; private ${GuzzleHttp\Psr7\Request}protocol = '1.1'; private ${GuzzleHttp\Psr7\Request}stream = class GuzzleHttp\Psr7\CachingStream { ... }; private $attributes = [...]; private $cookieParams = [...]; private $parsedBody = [...]; private $queryParams = [...]; private $serverParams = [...]; private $uploadedFiles = [...] }; protected array $bodyParsers = ['application/json' => class Closure { virtual $closure = "$this->Slim\Http\{closure}", ... }, 'appli...
azuracast  | NOTICE: PHP message: PHP   6. Slim\Middleware\ErrorMiddleware->process($request = class App\Http\ServerRequest { protected Psr\Http\Message\ServerRequestInterface $serverRequest = class GuzzleHttp\Psr7\ServerRequest { private ${GuzzleHttp\Psr7\Request}method = 'GET'; private ${GuzzleHttp\Psr7\Request}requestTarget = NULL; private ${GuzzleHttp\Psr7\Request}uri = class GuzzleHttp\Psr7\Uri { ... }; private ${GuzzleHttp\Psr7\Request}headers = [...]; private ${GuzzleHttp\Psr7\Request}headerNames = [...]; private ${GuzzleHttp\Psr7\Request}protocol = '1.1'; private ${GuzzleHttp\Psr7\Request}stream = class GuzzleHttp\Psr7\CachingStream { ... }; private $attributes = [...]; private $cookieParams = [...]; private $parsedBody = [...]; private $queryParams = [...]; private $serverParams = [...]; private $uploadedFiles = [...] }; protected array $bodyParsers = ['application/json' => class Closure { virtual $closure = "$this->Slim\Http\{closure}", ... }, 'application/xml' => class Closure { virtual $closure = "$this->S...
azuracast  | NOTICE: PHP message: PHP   7. Slim\Middleware\ErrorMiddleware->handleException($request = class App\Http\ServerRequest { protected Psr\Http\Message\ServerRequestInterface $serverRequest = class GuzzleHttp\Psr7\ServerRequest { private ${GuzzleHttp\Psr7\Request}method = 'GET'; private ${GuzzleHttp\Psr7\Request}requestTarget = NULL; private ${GuzzleHttp\Psr7\Request}uri = class GuzzleHttp\Psr7\Uri { ... }; private ${GuzzleHttp\Psr7\Request}headers = [...]; private ${GuzzleHttp\Psr7\Request}headerNames = [...]; private ${GuzzleHttp\Psr7\Request}protocol = '1.1'; private ${GuzzleHttp\Psr7\Request}stream = class GuzzleHttp\Psr7\CachingStream { ... }; private $attributes = [...]; private $cookieParams = [...]; private $parsedBody = [...]; private $queryParams = [...]; private $serverParams = [...]; private $uploadedFiles = [...] }; protected array $bodyParsers = ['application/json' => class Closure { virtual $closure = "$this->Slim\Http\{closure}", ... }, 'application/xml' => class Closure { virtual $closure = "...
azuracast  | NOTICE: PHP message: PHP   8. App\Http\ErrorHandler->__invoke($request = class App\Http\ServerRequest { protected Psr\Http\Message\ServerRequestInterface $serverRequest = class GuzzleHttp\Psr7\ServerRequest { private ${GuzzleHttp\Psr7\Request}method = 'GET'; private ${GuzzleHttp\Psr7\Request}requestTarget = NULL; private ${GuzzleHttp\Psr7\Request}uri = class GuzzleHttp\Psr7\Uri { ... }; private ${GuzzleHttp\Psr7\Request}headers = [...]; private ${GuzzleHttp\Psr7\Request}headerNames = [...]; private ${GuzzleHttp\Psr7\Request}protocol = '1.1'; private ${GuzzleHttp\Psr7\Request}stream = class GuzzleHttp\Psr7\CachingStream { ... }; private $attributes = [...]; private $cookieParams = [...]; private $parsedBody = [...]; private $queryParams = [...]; private $serverParams = [...]; private $uploadedFiles = [...] }; protected array $bodyParsers = ['application/json' => class Closure { virtual $closure = "$this->Slim\Http\{closure}", ... }, 'application/xml' => class Closure { virtual $closure = "$this->Slim\Http\...
azuracast  | NOTICE: PHP message: PHP   9. Slim\Handlers\ErrorHandler->__invoke($request = class App\Http\ServerRequest { protected Psr\Http\Message\ServerRequestInterface $serverRequest = class GuzzleHttp\Psr7\ServerRequest { private ${GuzzleHttp\Psr7\Request}method = 'GET'; private ${GuzzleHttp\Psr7\Request}requestTarget = NULL; private ${GuzzleHttp\Psr7\Request}uri = class GuzzleHttp\Psr7\Uri { ... }; private ${GuzzleHttp\Psr7\Request}headers = [...]; private ${GuzzleHttp\Psr7\Request}headerNames = [...]; private ${GuzzleHttp\Psr7\Request}protocol = '1.1'; private ${GuzzleHttp\Psr7\Request}stream = class GuzzleHttp\Psr7\CachingStream { ... }; private $attributes = [...]; private $cookieParams = [...]; private $parsedBody = [...]; private $queryParams = [...]; private $serverParams = [...]; private $uploadedFiles = [...] }; protected array $bodyParsers = ['application/json' => class Closure { virtual $closure = "$this->Slim\Http\{closure}", ... }, 'application/xml' => class Closure { virtual $closure = "$this->Slim\...
azuracast  | NOTICE: PHP message: PHP  10. App\Http\ErrorHandler->respond() /var/azuracast/www/vendor/slim/slim/Slim/Handlers/ErrorHandler.php:135
azuracast  | NOTICE: PHP message: PHP  11. App\View->renderToResponse($response = class App\Http\Response { protected Psr\Http\Message\ResponseInterface $response = class GuzzleHttp\Psr7\Response { private $reasonPhrase = 'Not Found'; private $statusCode = 404; private $headers = [...]; private $headerNames = [...]; private $protocol = '1.1'; private $stream = NULL }; protected Psr\Http\Message\StreamFactoryInterface $streamFactory = class GuzzleHttp\Psr7\HttpFactory {  } }, $templateName = 'system/error_http', $templateArgs = ['exception' => class Slim\Exception\HttpNotFoundException { protected $message = 'Not found.'; private string ${Exception}string = ''; protected $code = 404; protected string $file = '/var/azuracast/www/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php'; protected int $line = 76; private array ${Exception}trace = [...]; private ?Throwable ${Exception}previous = NULL; protected Psr\Http\Message\ServerRequestInterface $request = class App\Http\ServerRequest { ... }; protected string $title =...
azuracast  | NOTICE: PHP message: PHP  12. League\Plates\Engine->render($name = 'system/error_http', $data = ['exception' => class Slim\Exception\HttpNotFoundException { protected $message = 'Not found.'; private string ${Exception}string = ''; protected $code = 404; protected string $file = '/var/azuracast/www/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php'; protected int $line = 76; private array ${Exception}trace = [...]; private ?Throwable ${Exception}previous = NULL; protected Psr\Http\Message\ServerRequestInterface $request = class App\Http\ServerRequest { ... }; protected string $title = '404 Not Found'; protected string $description = 'The requested resource could not be found. Please verify the URI and try again.'; public $xdebug_message = '<tr><th align=\'left\' bgcolor=\'#f57900\' colspan="5"><span style=\'background-color: #cc0000; color: #fce94f; font-size: x-large;\'>( ! )</span> Slim\\Exception\\HttpNotFoundException: Not found. in /var/azuracast/www/vendor/slim/slim/Slim/Middleware/RoutingMiddl...
azuracast  | NOTICE: PHP message: PHP  13. League\Plates\Template\Template->render($data = ['exception' => class Slim\Exception\HttpNotFoundException { protected $message = 'Not found.'; private string ${Exception}string = ''; protected $code = 404; protected string $file = '/var/azuracast/www/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php'; protected int $line = 76; private array ${Exception}trace = [...]; private ?Throwable ${Exception}previous = NULL; protected Psr\Http\Message\ServerRequestInterface $request = class App\Http\ServerRequest { ... }; protected string $title = '404 Not Found'; protected string $description = 'The requested resource could not be found. Please verify the URI and try again.'; public $xdebug_message = '<tr><th align=\'left\' bgcolor=\'#f57900\' colspan="5"><span style=\'background-color: #cc0000; color: #fce94f; font-size: x-large;\'>( ! )</span> Slim\\Exception\\HttpNotFoundException: Not found. in /var/azuracast/www/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php on line ...
azuracast  | NOTICE: PHP message: PHP  14. League\Plates\Template\Template->render($data = ['title' => '404 Not Found', 'page_class' => 'error-content']) /var/azuracast/www/vendor/league/plates/src/Template/Template.php:171
azuracast  | NOTICE: PHP message: PHP  15. include() /var/azuracast/www/vendor/league/plates/src/Template/Template.php:164
```

**Comment by Vaalyn** [comment]
When compared to an earlier version the `App/Sync/Task/CheckFolderPlaylistsTask` for the parameter `{task}` of the `/admin/debug/sync/{task}` route was URL encoded like this: `App%5CSync%5CTask%5CCheckMediaTask` which is most likely the cause of this bug.
