### ISSUE TITLE
Errors after updating

### ISSUE THREAD

**Issue by griffon56** [AzuraCast/AzuraCast#592]
- **Installation Method: Docker 
- **Host OS (if using Docker): Ubuntu 16.04

**Describe the issue in full detail, including screenshots if possible:**

HI, 
FYI

The system is behaving correctly but I got following error at the end of docker-update.sh script :

```
Restarting station #3: radio
[23-May-2018 10:01:15 UTC] PHP Fatal error:  Uncaught Error: Cannot use object of type Entity\StationPlaylist as array in /var/azuracast/www/app/src/AzuraCast/Radio/Backend/Liquidsoap.php:183
Stack trace:
#0 /var/azuracast/www/app/src/AzuraCast/Radio/Configuration.php(77): AzuraCast\Radio\Backend\Liquidsoap->write()
#1 /var/azuracast/www/app/src/AzuraCast/Console/Command/RestartRadio.php(44): AzuraCast\Radio\Configuration->writeConfiguration(Object(Entity\Station))
#2 /var/azuracast/www/vendor/symfony/console/Command/Command.php(252): AzuraCast\Console\Command\RestartRadio->execute(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/azuracast/www/app/src/AzuraCast/Console/Command/Setup.php(58): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/azuracast/www/app/src/AzuraCast/Console/Command/Setup.php(45): AzuraCast\Console\Command\Setup->runCommand(Object(Symfony\Component\Consol in /var/azuracast/www/app/src/AzuraCast/Radio/Backend/Liquidsoap.php on line 183
2018/05/23 10:01:15 Command exited with error: exit status 255
azuracast_influxdb_1 is up-to-date
Creating azuracast_letsencrypt_1 ...
azuracast_redis_1 is up-to-date
azuracast_mariadb_1 is up-to-date
azuracast_stations is up-to-date
azuracast_web_1 is up-to-date
Creating azuracast_letsencrypt_1
Creating azuracast_nginx_1 ...
Creating azuracast_cli_1 ...
Creating azuracast_cron ...
Creating azuracast_nginx_1
Creating azuracast_cli_1
Creating azuracast_nginx_1 ... done
```

Also, since a month or two, i always need to launch these commands after a docker-update.sh in order for the "SYNCHRONIZATION TASKS" to work at all.

```
docker-compose down
docker-compose up -d
```

**Comment by griffon56** [comment]
Thank YOU man !
But what about the second issue (synchronization task) ?

**Comment by SlvrEagle23** [comment]
@griffon56 The general rule on here is "one issue per issue" because I can't mark things as 50% done or keep track mentally of the fact that one issue has 2 items in it that are otherwise unrelated.

You should try pulling down the new `docker.sh` utility script, which includes an updated...updater

**Comment by griffon56** [comment]
I pulled the docker.sh script, executed it, and got the same errors :

```
[24-May-2018 12:50:01 UTC] PHP Fatal error:  Uncaught Error: Cannot use object of type Entity\StationPlaylist as array in /var/azuracast/www/app/src/AzuraCast/Radio/Backend/Liquidsoap.php:183                                                                                                                                                                                                                                                                                   
Stack trace:
#0 /var/azuracast/www/app/src/AzuraCast/Radio/Configuration.php(77): AzuraCast\Radio\Backend\Liquidsoap->write()
#1 /var/azuracast/www/app/src/AzuraCast/Console/Command/RestartRadio.php(44): Az                                                                                                                                                             uraCast\Radio\Configuration->writeConfiguration(Object(Entity\Station))
#2 /var/azuracast/www/vendor/symfony/console/Command/Command.php(252): AzuraCast                                                                                                                                                             \Console\Command\RestartRadio->execute(Object(Symfony\Component\Console\Input\Ar                                                                                                                                                             rayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/azuracast/www/app/src/AzuraCast/Console/Command/Setup.php(58): Symfony\C                                                                                                                                                             omponent\Console\Command\Command->run(Object(Symfony\Component\Console\Input\Arr                                                                                                                                                             ayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/azuracast/www/app/src/AzuraCast/Console/Command/Setup.php(45): AzuraCast                                                                                                                                                             \Console\Command\Setup->runCommand(Object(Symfony\Component\Consol in /var/azura                                                                                                                                                             cast/www/app/src/AzuraCast/Radio/Backend/Liquidsoap.php on line 183
2018/05/24 12:50:01 Command exited with error: exit status 255
azuracast_stations is up-to-date
Creating azuracast_letsencrypt_1 ...
azuracast_mariadb_1 is up-to-date
azuracast_influxdb_1 is up-to-date
azuracast_redis_1 is up-to-date
Creating azuracast_letsencrypt_1
azuracast_web_1 is up-to-date
Creating azuracast_nginx_1 ...
Creating azuracast_cron ...
Creating azuracast_cli_1 ...
Creating azuracast_nginx_1
Creating azuracast_cron
Creating azuracast_letsencrypt_1 ... done
"docker rmi" requires at least 1 argument(s).
See 'docker rmi --help'.

Usage:  docker rmi [OPTIONS] IMAGE [IMAGE...]

Remove one or more images
```

**Comment by griffon56** [comment]
I don't know if it has something to do with previous error, but I get following error when triggering the current title sync 
```
cURL error 7: Failed to connect to stations port 8020: Connection refused (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
CurlFactory.php : 185
```

**Comment by SlvrEagle23** [comment]
@griffon56 That error was fixed, though...the update script should've pulled down the newest version of the code before doing any operations, provided you aren't running it in development mode.

**Comment by griffon56** [comment]
I fixed the error by using the old docker-update.sh script. Thanks again for all your efforts.
