### ISSUE TITLE
Can't run now playing after update

### ISSUE THREAD

**Issue by istahilagi** [AzuraCast/AzuraCast#6613]
### Installation Method

One-Click Installation (Docker)

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

97744ed

### What happened?

My panel can't run now playing after updating from v17 to v19.1 stable version...
after that I migrated to the rolling release version but it still wouldn't run now playing

this is the azuracast application log
and the bottom one is azuracast now playing log... hope the availability helps

2023-09-13T09:44:13.571068+00:00] AzuraCast.ERROR: This instance is not the current active instance. [] []
[2023-09-13T09:44:15.185066+00:00] AzuraCast.ERROR: This instance is not the current active instance. [] []
[2023-09-13T09:44:48.598169+00:00] AzuraCast.NOTICE: Starting new Message Queue worker process. {"runtime":0,"workerName":"app_worker_0"} []
[2023-09-13T09:44:53.611524+00:00] AzuraCast.ERROR: TypeError: App\Console\Command\Sync\NowPlayingCommand::start(): Argument #2 ($shortName) must be of type string, int given, called in /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php on line 100 (uncaught exception) at /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php line 143 while running console command `azuracast:sync:nowplaying` {"exception":"[object] (TypeError(code: 0): App\\Console\\Command\\Sync\\NowPlayingCommand::start(): Argument #2 ($shortName) must be of type string, int given, called in /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php on line 100 at /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php:143)"} []
[2023-09-13T09:44:53.696954+00:00] AzuraCast.WARNING: Console command `azuracast:sync:nowplaying` exited with error code 1. [] []
[2023-09-13T09:44:53.699001+00:00] AzuraCast.ALERT: Fatal Error (E_ERROR): Uncaught TypeError: App\Console\Command\Sync\NowPlayingCommand::start(): Argument #2 ($shortName) must be of type string, int given, called in /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php on line 100 and defined in /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php:143 Stack trace: #0 /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php(100): App\Console\Command\Sync\NowPlayingCommand->start() #1 /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php(67): App\Console\Command\Sync\NowPlayingCommand->loop() #2 /var/azuracast/www/vendor/symfony/console/Command/Command.php(326): App\Console\Command\Sync\NowPlayingCommand->execute() #3 /var/azuracast/www/vendor/symfony/console/Application.php(1081): Symfony\Component\Console\Command\Command->run() #4 /var/azuracast/www/vendor/symfony/console/Application.php(320): Symfony\Component\Console\Application->doRunCommand() #5 /var/azuracast/www/vendor/symfony/console/Application.php(174): Symfony\Component\Console\Application->doRun() #6 /var/azuracast/www/bin/console(16): Symfony\Component\Console\Application->run() #7 {main}   thrown {"code":1,"message":"Uncaught TypeError: App\\Console\\Command\\Sync\\NowPlayingCommand::start(): Argument #2 ($shortName) must be of type string, int given, called in /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php on line 100 and defined in /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php:143\nStack trace:\n#0 /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php(100): App\\Console\\Command\\Sync\\NowPlayingCommand->start()\n#1 /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php(67): App\\Console\\Command\\Sync\\NowPlayingCommand->loop()\n#2 /var/azuracast/www/vendor/symfony/console/Command/Command.php(326): App\\Console\\Command\\Sync\\NowPlayingCommand->execute()\n#3 /var/azuracast/www/vendor/symfony/console/Application.php(1081): Symfony\\Component\\Console\\Command\\Command->run()\n#4 /var/azuracast/www/vendor/symfony/console/Application.php(320): Symfony\\Component\\Console\\Application->doRunCommand()\n#5 /var/azuracast/www/vendor/symfony/console/Application.php(174): Symfony\\Component\\Console\\Application->doRun()\n#6 /var/azuracast/www/bin/console(16): Symfony\\Component\\Console\\Application->run()\n#7 {main}\n  thrown","file":"/var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php","line":143,"trace":null} []
[2023-09-13T09:44:57.232241+00:00] AzuraCast.WARNING: Console command `azuracast:acme:get-certificate` exited with error code 1. [] []
[2023-09-13T09:45:07.246182+00:00] AzuraCast.ERROR: TypeError: App\Console\Command\Sync\NowPlayingCommand::start(): Argument #2 ($shortName) must be of type string, int given, called in /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php on line 100 (uncaught exception) at /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php line 143 while running console command `azuracast:sync:nowplaying` {"exception":"[object] (TypeError(code: 0): App\\Console\\Command\\Sync\\NowPlayingCommand::start(): Argument #2 ($shortName) must be of type string, int given, called in /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php on line 100 at /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php:143)"} []
[2023-09-13T09:45:07.252826+00:00] AzuraCast.WARNING: Console command `azuracast:sync:nowplaying` exited with error code 1. [] []
[2023-09-13T09:45:07.255922+00:00] AzuraCast.ALERT: Fatal Error (E_ERROR): Uncaught TypeError: App\Console\Command\Sync\NowPlayingCommand::start(): Argument #2 ($shortName) must be of type string, int given, called in /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php on line 100 and defined in /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php:143 Stack trace: #0 /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php(100): App\Console\Command\Sync\NowPlayingCommand->start() #1 /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php(67): App\Console\Command\Sync\NowPlayingCommand->loop() #2 /var/azuracast/www/vendor/symfony/console/Command/Command.php(326): App\Console\Command\Sync\NowPlayingCommand->execute() #3 /var/azuracast/www/vendor/symfony/console/Application.php(1081): Symfony\Component\Console\Command\Command->run() #4 /var/azuracast/www/vendor/symfony/console/Application.php(320): Symfony\Component\Console\Application->doRunCommand() #5 /var/azuracast/www/vendor/symfony/console/Application.php(174): Symfony\Component\Console\Application->doRun() #6 /var/azuracast/www/bin/console(16): Symfony\Component\Console\Application->run() #7 {main}   thrown {"code":1,"message":"Uncaught TypeError: App\\Console\\Command\\Sync\\NowPlayingCommand::start(): Argument #2 ($shortName) must be of type string, int given, called in /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php on line 100 and defined in /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php:143\nStack trace:\n#0 /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php(100): App\\Console\\Command\\Sync\\NowPlayingCommand->start()\n#1 /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php(67): App\\Console\\Command\\Sync\\NowPlayingCommand->loop()\n#2 /var/azuracast/www/vendor/symfony/console/Command/Command.php(326): App\\Console\\Command\\Sync\\NowPlayingCommand->execute()\n#3 /var/azuracast/www/vendor/symfony/console/Application.php(1081): Symfony\\Component\\Console\\Command\\Command->run()\n#4 /var/azuracast/www/vendor/symfony/console/Application.php(320): Symfony\\Component\\Console\\Application->doRunCommand()\n#5 /var/azuracast/www/vendor/symfony/console/Application.php(174): Symfony\\Component\\Console\\Application->doRun()\n#6 /var/azuracast/www/bin/console(16): Symfony\\Component\\Console\\Application->run()\n#7 {main}\n  thrown","file":"/var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php","line":143,"trace":null} []
[2023-09-13T09:45:20.200269+00:00] AzuraCast.ERROR: TypeError: App\Console\Command\Sync\NowPlayingCommand::start(): Argument #2 ($shortName) must be of type string, int given, called in /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php on line 100 (uncaught exception) at /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php line 143 while running console command `azuracast:sync:nowplaying` {"exception":"[object] (TypeError(code: 0): App\\Console\\Command\\Sync\\NowPlayingCommand::start(): Argument #2 ($shortName) must be of type string, int given, called in /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php on line 100 at /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php:143)"} []
[2023-09-13T09:45:20.206695+00:00] AzuraCast.WARNING: Console command `azuracast:sync:nowplaying` exited with error code 1. [] []
[2023-09-13T09:45:20.211504+00:00] AzuraCast.ALERT: Fatal Error (E_ERROR): Uncaught TypeError: App\Console\Command\Sync\NowPlayingCommand::start(): Argument #2 ($shortName) must be of type string, int given, called in /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php on line 100 and defined in /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php:143 Stack trace: #0 /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php(100): App\Console\Command\Sync\NowPlayingCommand->start() #1 /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php(67): App\Console\Command\Sync\NowPlayingCommand->loop() #2 /var/azuracast/www/vendor/symfony/console/Command/Command.php(326): App\Console\Command\Sync\NowPlayingCommand->execute() #3 /var/azuracast/www/vendor/symfony/console/Application.php(1081): Symfony\Component\Console\Command\Command->run() #4 /var/azuracast/www/vendor/symfony/console/Application.php(320): Symfony\Component\Console\Application->doRunCommand() #5 /var/azuracast/www/vendor/symfony/console/Application.php(174): Symfony\Component\Console\Application->doRun() #6 /var/azuracast/www/bin/console(16): Symfony\Component\Console\Application->run() #7 {main}   thrown {"code":1,"message":"Uncaught TypeError: App\\Console\\Command\\Sync\\NowPlayingCommand::start(): Argument #2 ($shortName) must be of type string, int given, called in /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php on line 100 and defined in /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php:143\nStack trace:\n#0 /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php(100): App\\Console\\Command\\Sync\\NowPlayingCommand->start()\n#1 /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php(67): App\\Console\\Command\\Sync\\NowPlayingCommand->loop()\n#2 /var/azuracast/www/vendor/symfony/console/Command/Command.php(326): App\\Console\\Command\\Sync\\NowPlayingCommand->execute()\n#3 /var/azuracast/www/vendor/symfony/console/Application.php(1081): Symfony\\Component\\Console\\Command\\Command->run()\n#4 /var/azuracast/www/vendor/symfony/console/Application.php(320): Symfony\\Component\\Console\\Application->doRunCommand()\n#5 /var/azuracast/www/vendor/symfony/console/Application.php(174): Symfony\\Component\\Console\\Application->doRun()\n#6 /var/azuracast/www/bin/console(16): Symfony\\Component\\Console\\Application->run()\n#7 {main}\n  thrown","file":"/var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php","line":143,"trace":null} []
[2023-09-13T09:45:26.520942+00:00] AzuraCast.ERROR: TypeError: App\Console\Command\Sync\NowPlayingCommand::start(): Argument #2 ($shortName) must be of type string, int given, called in /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php on line 100 (uncaught exception) at /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php line 143 while running console command `azuracast:sync:nowplaying` {"exception":"[object] (TypeError(code: 0): App\\Console\\Command\\Sync\\NowPlayingCommand::start(): Argument #2 ($shortName) must be of type string, int given, called in /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php on line 100 at /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php:143)"} []
[2023-09-13T09:45:26.525148+00:00] AzuraCast.WARNING: Console command `azuracast:sync:nowplaying` exited with error code 1. [] []

### Relevant log output

```shell
[2023-09-13T09:47:43.538793+00:00] AzuraCast.ERROR: TypeError: App\Console\Command\Sync\NowPlayingCommand::start(): Argument #2 ($shortName) must be of type string, int given, called in /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php on line 100 (uncaught exception) at /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php line 143 while running console command `azuracast:sync:nowplaying` {"exception":"[object] (TypeError(code: 0): App\\Console\\Command\\Sync\\NowPlayingCommand::start(): Argument #2 ($shortName) must be of type string, int given, called in /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php on line 100 at /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php:143)"} []
[2023-09-13T09:47:43.542335+00:00] AzuraCast.WARNING: Console command `azuracast:sync:nowplaying` exited with error code 1. [] []
[2023-09-13T09:47:43.542882+00:00] AzuraCast.ALERT: Fatal Error (E_ERROR): Uncaught TypeError: App\Console\Command\Sync\NowPlayingCommand::start(): Argument #2 ($shortName) must be of type string, int given, called in /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php on line 100 and defined in /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php:143 Stack trace: #0 /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php(100): App\Console\Command\Sync\NowPlayingCommand->start() #1 /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php(67): App\Console\Command\Sync\NowPlayingCommand->loop() #2 /var/azuracast/www/vendor/symfony/console/Command/Command.php(326): App\Console\Command\Sync\NowPlayingCommand->execute() #3 /var/azuracast/www/vendor/symfony/console/Application.php(1081): Symfony\Component\Console\Command\Command->run() #4 /var/azuracast/www/vendor/symfony/console/Application.php(320): Symfony\Component\Console\Application->doRunCommand() #5 /var/azuracast/www/vendor/symfony/console/Application.php(174): Symfony\Component\Console\Application->doRun() #6 /var/azuracast/www/bin/console(16): Symfony\Component\Console\Application->run() #7 {main}   thrown {"code":1,"message":"Uncaught TypeError: App\\Console\\Command\\Sync\\NowPlayingCommand::start(): Argument #2 ($shortName) must be of type string, int given, called in /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php on line 100 and defined in /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php:143\nStack trace:\n#0 /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php(100): App\\Console\\Command\\Sync\\NowPlayingCommand->start()\n#1 /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php(67): App\\Console\\Command\\Sync\\NowPlayingCommand->loop()\n#2 /var/azuracast/www/vendor/symfony/console/Command/Command.php(326): App\\Console\\Command\\Sync\\NowPlayingCommand->execute()\n#3 /var/azuracast/www/vendor/symfony/console/Application.php(1081): Symfony\\Component\\Console\\Command\\Command->run()\n#4 /var/azuracast/www/vendor/symfony/console/Application.php(320): Symfony\\Component\\Console\\Application->doRunCommand()\n#5 /var/azuracast/www/vendor/symfony/console/Application.php(174): Symfony\\Component\\Console\\Application->doRun()\n#6 /var/azuracast/www/bin/console(16): Symfony\\Component\\Console\\Application->run()\n#7 {main}\n  thrown","file":"/var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php","line":143,"trace":null} []
[2023-09-13T09:47:45.150626+00:00] AzuraCast.ERROR: TypeError: App\Console\Command\Sync\NowPlayingCommand::start(): Argument #2 ($shortName) must be of type string, int given, called in /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php on line 100 (uncaught exception) at /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php line 143 while running console command `azuracast:sync:nowplaying` {"exception":"[object] (TypeError(code: 0): App\\Console\\Command\\Sync\\NowPlayingCommand::start(): Argument #2 ($shortName) must be of type string, int given, called in /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php on line 100 at /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php:143)"} []
[2023-09-13T09:47:45.156206+00:00] AzuraCast.WARNING: Console command `azuracast:sync:nowplaying` exited with error code 1. [] []
[2023-09-13T09:47:45.156871+00:00] AzuraCast.ALERT: Fatal Error (E_ERROR): Uncaught TypeError: App\Console\Command\Sync\NowPlayingCommand::start(): Argument #2 ($shortName) must be of type string, int given, called in /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php on line 100 and defined in /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php:143 Stack trace: #0 /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php(100): App\Console\Command\Sync\NowPlayingCommand->start() #1 /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php(67): App\Console\Command\Sync\NowPlayingCommand->loop() #2 /var/azuracast/www/vendor/symfony/console/Command/Command.php(326): App\Console\Command\Sync\NowPlayingCommand->execute() #3 /var/azuracast/www/vendor/symfony/console/Application.php(1081): Symfony\Component\Console\Command\Command->run() #4 /var/azuracast/www/vendor/symfony/console/Application.php(320): Symfony\Component\Console\Application->doRunCommand() #5 /var/azuracast/www/vendor/symfony/console/Application.php(174): Symfony\Component\Console\Application->doRun() #6 /var/azuracast/www/bin/console(16): Symfony\Component\Console\Application->run() #7 {main}   thrown {"code":1,"message":"Uncaught TypeError: App\\Console\\Command\\Sync\\NowPlayingCommand::start(): Argument #2 ($shortName) must be of type string, int given, called in /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php on line 100 and defined in /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php:143\nStack trace:\n#0 /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php(100): App\\Console\\Command\\Sync\\NowPlayingCommand->start()\n#1 /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php(67): App\\Console\\Command\\Sync\\NowPlayingCommand->loop()\n#2 /var/azuracast/www/vendor/symfony/console/Command/Command.php(326): App\\Console\\Command\\Sync\\NowPlayingCommand->execute()\n#3 /var/azuracast/www/vendor/symfony/console/Application.php(1081): Symfony\\Component\\Console\\Command\\Command->run()\n#4 /var/azuracast/www/vendor/symfony/console/Application.php(320): Symfony\\Component\\Console\\Application->doRunCommand()\n#5 /var/azuracast/www/vendor/symfony/console/Application.php(174): Symfony\\Component\\Console\\Application->doRun()\n#6 /var/azuracast/www/bin/console(16): Symfony\\Component\\Console\\Application->run()\n#7 {main}\n  thrown","file":"/var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php","line":143,"trace":null} []
[2023-09-13T09:47:48.699391+00:00] AzuraCast.ERROR: TypeError: App\Console\Command\Sync\NowPlayingCommand::start(): Argument #2 ($shortName) must be of type string, int given, called in /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php on line 100 (uncaught exception) at /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php line 143 while running console command `azuracast:sync:nowplaying` {"exception":"[object] (TypeError(code: 0): App\\Console\\Command\\Sync\\NowPlayingCommand::start(): Argument #2 ($shortName) must be of type string, int given, called in /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php on line 100 at /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php:143)"} []
[2023-09-13T09:47:48.703875+00:00] AzuraCast.WARNING: Console command `azuracast:sync:nowplaying` exited with error code 1. [] []
[2023-09-13T09:47:48.704435+00:00] AzuraCast.ALERT: Fatal Error (E_ERROR): Uncaught TypeError: App\Console\Command\Sync\NowPlayingCommand::start(): Argument #2 ($shortName) must be of type string, int given, called in /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php on line 100 and defined in /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php:143 Stack trace: #0 /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php(100): App\Console\Command\Sync\NowPlayingCommand->start() #1 /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php(67): App\Console\Command\Sync\NowPlayingCommand->loop() #2 /var/azuracast/www/vendor/symfony/console/Command/Command.php(326): App\Console\Command\Sync\NowPlayingCommand->execute() #3 /var/azuracast/www/vendor/symfony/console/Application.php(1081): Symfony\Component\Console\Command\Command->run() #4 /var/azuracast/www/vendor/symfony/console/Application.php(320): Symfony\Component\Console\Application->doRunCommand() #5 /var/azuracast/www/vendor/symfony/console/Application.php(174): Symfony\Component\Console\Application->doRun() #6 /var/azuracast/www/bin/console(16): Symfony\Component\Console\Application->run() #7 {main}   thrown {"code":1,"message":"Uncaught TypeError: App\\Console\\Command\\Sync\\NowPlayingCommand::start(): Argument #2 ($shortName) must be of type string, int given, called in /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php on line 100 and defined in /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php:143\nStack trace:\n#0 /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php(100): App\\Console\\Command\\Sync\\NowPlayingCommand->start()\n#1 /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php(67): App\\Console\\Command\\Sync\\NowPlayingCommand->loop()\n#2 /var/azuracast/www/vendor/symfony/console/Command/Command.php(326): App\\Console\\Command\\Sync\\NowPlayingCommand->execute()\n#3 /var/azuracast/www/vendor/symfony/console/Application.php(1081): Symfony\\Component\\Console\\Command\\Command->run()\n#4 /var/azuracast/www/vendor/symfony/console/Application.php(320): Symfony\\Component\\Console\\Application->doRunCommand()\n#5 /var/azuracast/www/vendor/symfony/console/Application.php(174): Symfony\\Component\\Console\\Application->doRun()\n#6 /var/azuracast/www/bin/console(16): Symfony\\Component\\Console\\Application->run()\n#7 {main}\n  thrown","file":"/var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php","line":143,"trace":null} []
[2023-09-13T09:47:53.026403+00:00] AzuraCast.ERROR: TypeError: App\Console\Command\Sync\NowPlayingCommand::start(): Argument #2 ($shortName) must be of type string, int given, called in /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php on line 100 (uncaught exception) at /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php line 143 while running console command `azuracast:sync:nowplaying` {"exception":"[object] (TypeError(code: 0): App\\Console\\Command\\Sync\\NowPlayingCommand::start(): Argument #2 ($shortName) must be of type string, int given, called in /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php on line 100 at /var/azuracast/www/src/Console/Command/Sync/NowPlayingCommand.php:143)"} []
[2023-09-13T09:47:53.029462+00:00] AzuraCast.WARNING: Console command `azuracast:sync:nowplaying` exited with error code 1. [] []
```

**Comment by istahilagi** [comment]
I have done it but it doesn't work
