### ISSUE TITLE
Cannot start streaming with WebDJ

### ISSUE THREAD

**Issue by nickdeppe** [AzuraCast/AzuraCast#6995]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.19.5 Stable

### What happened?

When trying to use WebDJ, I enter the username and password, and click "Start Streaming", but nothing happens.  I'm getting an error in console, "DOMException: Failed to construct 'webSocket': The URL 'undefined' is invalid.  I've tried reinstalling another instance with rolling release, but I keep getting the same error.  Tried in Edge, Chrome, and Firefox, but get the same issue in each browser.  

<img width="1213" alt="Screenshot 2024-03-05 220954" src="https://github.com/AzuraCast/AzuraCast/assets/11273420/7c2c3650-1e95-4a9c-9e62-02979c267a7e">

### Relevant log output

```shell
vue-D_WLdR4x.js:13  DOMException: Failed to construct 'WebSocket': The URL 'undefined' is invalid.
    at connect (https://192.168.0.184/static/vite_dist/assets/PublicWebDJ-D7lpc58V.js:1:8272)
    at startStream (https://192.168.0.184/static/vite_dist/assets/PublicWebDJ-D7lpc58V.js:1:3389)
    at x.onClick.s.<computed>.s.<computed> (https://192.168.0.184/static/vite_dist/assets/PublicWebDJ-D7lpc58V.js:1:18541)
    at Ue (https://192.168.0.184/static/vite_dist/vue-D_WLdR4x.js:13:1373)
    at we (https://192.168.0.184/static/vite_dist/vue-D_WLdR4x.js:13:1443)
    at HTMLButtonElement.n (https://192.168.0.184/static/vite_dist/vue-D_WLdR4x.js:17:8113)
```

**Comment by jvsouto** [comment]
@nickdeppe Your Rolling Release version is older than the version where it was fixed.

**Comment by nickdeppe** [comment]
@jvsouto Thanks.  I initially tried to install the rolling release, but I had some problems getting it installed, which is why I switched to the stable release.  I just did a fresh install of rolling release, and now this bug is fixed.
