### ISSUE TITLE
"Bad Gateway" when installing Azuracast in "Rolling Release"

### ISSUE THREAD

**Issue by benoitcrauet** [AzuraCast/AzuraCast#7023]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Latest version on 2024-02-24 (I don't know how to see the version without nginx)

### What happened?

Hello

I try to install AzuraCast in a VM on Proxmox host, but once installed, I have a "**Bad Gateway**" error on web interface.

It's happen each time I install "Rolling release" version.
But it's a transfert from other AzuraCast install (physical machine).

If I install AzuraCast in "stable", I have the web interface, BUT, when I restore my archive, Azuracast instantly displays "**Bad Gateway**".

We are totally helpless with Azuracast now. I have tried to install it in another Proxmox host : same result.

Thanks

PS : I have the same log (below) in CLI when I type `./docker.sh cli cache:clear`

### Relevant log output

```
2024-03-24T11:05:43.871395564Z Fatal error: Uncaught RedisException: No such file or directory in /var/azuracast/www/src/Service/RedisFactory.php:33
2024-03-24T11:05:43.871400863Z Stack trace:
2024-03-24T11:05:43.871411819Z #0 /var/azuracast/www/src/Service/RedisFactory.php(33): Redis->connect('/run/redis/redi...')
2024-03-24T11:05:43.871417682Z #1 /var/azuracast/www_tmp/CompiledContainer.php(246): App\Service\RedisFactory->getInstance()
2024-03-24T11:05:43.871422601Z #2 [internal function]: CompiledContainer::{closure}(Object(App\Environment), Object(Monolog\Logger), Object(App\Service\RedisFactory))
2024-03-24T11:05:43.871427555Z #3 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(74): call_user_func_array(Object(Closure), Array)
2024-03-24T11:05:43.871442147Z #4 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(108): Invoker\Invoker->call(Object(Closure), Array)
2024-03-24T11:05:43.871448250Z #5 /var/azuracast/www_tmp/CompiledContainer.php(237): DI\CompiledContainer->resolveFactory(Object(Closure), 'Symfony\\Contrac...')
2024-03-24T11:05:43.871453327Z #6 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(54): CompiledContainer->get11()
2024-03-24T11:05:43.871458178Z #7 /var/azuracast/www_tmp/CompiledContainer.php(272): DI\CompiledContainer->get('Symfony\\Contrac...')
2024-03-24T11:05:43.871463046Z #8 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(54): CompiledContainer->get13()
2024-03-24T11:05:43.871467852Z #9 /var/azuracast/www/vendor/php-di/php-di/src/Invoker/FactoryParameterResolver.php(63): DI\CompiledContainer->get('Psr\\Cache\\Cache...')
2024-03-24T11:05:43.871472888Z #10 /var/azuracast/www/vendor/php-di/invoker/src/ParameterResolver/ResolverChain.php(30): DI\Invoker\FactoryParameterResolver->getParameters(Object(ReflectionFunction), Array, Array)
2024-03-24T11:05:43.871478014Z #11 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(58): Invoker\ParameterResolver\ResolverChain->getParameters(Object(ReflectionFunction), Array, Array)
2024-03-24T11:05:43.871483051Z #12 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(108): Invoker\Invoker->call(Object(Closure), Array)
2024-03-24T11:05:43.871487983Z #13 /var/azuracast/www_tmp/CompiledContainer.php(277): DI\CompiledContainer->resolveFactory(Object(Closure), 'Psr\\SimpleCache...')
2024-03-24T11:05:43.871492969Z #14 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(54): CompiledContainer->get14()
2024-03-24T11:05:43.871498498Z #15 /var/azuracast/www_tmp/CompiledContainer.php(760): DI\CompiledContainer->get('Psr\\SimpleCache...')
2024-03-24T11:05:43.871503628Z #16 /var/azuracast/www_tmp/CompiledContainer.php(770): CompiledContainer->get61()
2024-03-24T11:05:43.871508320Z #17 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(54): CompiledContainer->get60()
2024-03-24T11:05:43.871513043Z #18 /var/azuracast/www/vendor/php-di/php-di/src/Invoker/FactoryParameterResolver.php(63): DI\CompiledContainer->get('App\\Version')
2024-03-24T11:05:43.871517985Z #19 /var/azuracast/www/vendor/php-di/invoker/src/ParameterResolver/ResolverChain.php(30): DI\Invoker\FactoryParameterResolver->getParameters(Object(ReflectionFunction), Array, Array)
2024-03-24T11:05:43.871523004Z #20 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(58): Invoker\ParameterResolver\ResolverChain->getParameters(Object(ReflectionFunction), Array, Array)
2024-03-24T11:05:43.871532457Z #21 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(108): Invoker\Invoker->call(Object(Closure), Array)
2024-03-24T11:05:43.871538018Z #22 /var/azuracast/www_tmp/CompiledContainer.php(294): DI\CompiledContainer->resolveFactory(Object(Closure), 'App\\Console\\App...')
2024-03-24T11:05:43.871543133Z #23 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(54): CompiledContainer->get16()
2024-03-24T11:05:43.871547920Z #24 /var/azuracast/www/src/AppFactory.php(43): DI\CompiledContainer->get('App\\Console\\App...')
2024-03-24T11:05:43.871552885Z #25 /var/azuracast/www/bin/console(11): App\AppFactory::createCli()
2024-03-24T11:05:43.871557614Z #26 {main}
2024-03-24T11:05:43.871562235Z   thrown in /var/azuracast/www/src/Service/RedisFactory.php on line 33
2024-03-24T11:05:43.872897509Z [2024-03-24T11:05:43.871915+00:00] AzuraCast.ALERT: Fatal Error (E_ERROR): Uncaught RedisException: No such file or directory in /var/azuracast/www/src/Service/RedisFactory.php:33 Stack trace: #0 /var/azuracast/www/src/Service/RedisFactory.php(33): Redis->connect('/run/redis/redi...') #1 /var/azuracast/www_tmp/CompiledContainer.php(246): App\Service\RedisFactory->getInstance() #2 [internal function]: CompiledContainer::{closure}(Object(App\Environment), Object(Monolog\Logger), Object(App\Service\RedisFactory)) #3 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(74): call_user_func_array(Object(Closure), Array) #4 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(108): Invoker\Invoker->call(Object(Closure), Array) #5 /var/azuracast/www_tmp/CompiledContainer.php(237): DI\CompiledContainer->resolveFactory(Object(Closure), 'Symfony\\Contrac...') #6 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(54): CompiledContainer->get11() #7 /var/azuracast/www_tmp/CompiledContainer.php(272): DI\CompiledContainer->get('Symfony\\Contrac...') #8 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(54): CompiledContainer->get13() #9 /var/azuracast/www/vendor/php-di/php-di/src/Invoker/FactoryParameterResolver.php(63): DI\CompiledContainer->get('Psr\\Cache\\Cache...') #10 /var/azuracast/www/vendor/php-di/invoker/src/ParameterResolver/ResolverChain.php(30): DI\Invoker\FactoryParameterResolver->getParameters(Object(ReflectionFunction), Array, Array) #11 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(58): Invoker\ParameterResolver\ResolverChain->getParameters(Object(ReflectionFunction), Array, Array) #12 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(108): Invoker\Invoker->call(Object(Closure), Array) #13 /var/azuracast/www_tmp/CompiledContainer.php(277): DI\CompiledContainer->resolveFactory(Object(Closure), 'Psr\\SimpleCache...') #14 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(54): CompiledContainer->get14() #15 /var/azuracast/www_tmp/CompiledContainer.php(760): DI\CompiledContainer->get('Psr\\SimpleCache...') #16 /var/azuracast/www_tmp/CompiledContainer.php(770): CompiledContainer->get61() #17 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(54): CompiledContainer->get60() #18 /var/azuracast/www/vendor/php-di/php-di/src/Invoker/FactoryParameterResolver.php(63): DI\CompiledContainer->get('App\\Version') #19 /var/azuracast/www/vendor/php-di/invoker/src/ParameterResolver/ResolverChain.php(30): DI\Invoker\FactoryParameterResolver->getParameters(Object(ReflectionFunction), Array, Array) #20 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(58): Invoker\ParameterResolver\ResolverChain->getParameters(Object(ReflectionFunction), Array, Array) #21 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(108): Invoker\Invoker->call(Object(Closure), Array) #22 /var/azuracast/www_tmp/CompiledContainer.php(294): DI\CompiledContainer->resolveFactory(Object(Closure), 'App\\Console\\App...') #23 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(54): CompiledContainer->get16() #24 /var/azuracast/www/src/AppFactory.php(43): DI\CompiledContainer->get('App\\Console\\App...') #25 /var/azuracast/www/bin/console(11): App\AppFactory::createCli() #26 {main}   thrown {"code":1,"message":"Uncaught RedisException: No such file or directory in /var/azuracast/www/src/Service/RedisFactory.php:33\nStack trace:\n#0 /var/azuracast/www/src/Service/RedisFactory.php(33): Redis->connect('/run/redis/redi...')\n#1 /var/azuracast/www_tmp/CompiledContainer.php(246): App\\Service\\RedisFactory->getInstance()\n#2 [internal function]: CompiledContainer::{closure}(Object(App\\Environment), Object(Monolog\\Logger), Object(App\\Service\\RedisFactory))\n#3 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(74): call_user_func_array(Object(Closure), Array)\n#4 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(108): Invoker\\Invoker->call(Object(Closure), Array)\n#5 /var/azuracast/www_tmp/CompiledContainer.php(237): DI\\CompiledContainer->resolveFactory(Object(Closure), 'Symfony\\\\Contrac...')\n#6 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(54): CompiledContainer->get11()\n#7 /var/azuracast/www_tmp/CompiledContainer.php(272): DI\\CompiledContainer->get('Symfony\\\\Contrac...')\n#8 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(54): CompiledContainer->get13()\n#9 /var/azuracast/www/vendor/php-di/php-di/src/Invoker/FactoryParameterResolver.php(63): DI\\CompiledContainer->get('Psr\\\\Cache\\\\Cache...')\n#10 /var/azuracast/www/vendor/php-di/invoker/src/ParameterResolver/ResolverChain.php(30): DI\\Invoker\\FactoryParameterResolver->getParameters(Object(ReflectionFunction), Array, Array)\n#11 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(58): Invoker\\ParameterResolver\\ResolverChain->getParameters(Object(ReflectionFunction), Array, Array)\n#12 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(108): Invoker\\Invoker->call(Object(Closure), Array)\n#13 /var/azuracast/www_tmp/CompiledContainer.php(277): DI\\CompiledContainer->resolveFactory(Object(Closure), 'Psr\\\\SimpleCache...')\n#14 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(54): CompiledContainer->get14()\n#15 /var/azuracast/www_tmp/CompiledContainer.php(760): DI\\CompiledContainer->get('Psr\\\\SimpleCache...')\n#16 /var/azuracast/www_tmp/CompiledContainer.php(770): CompiledContainer->get61()\n#17 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(54): CompiledContainer->get60()\n#18 /var/azuracast/www/vendor/php-di/php-di/src/Invoker/FactoryParameterResolver.php(63): DI\\CompiledContainer->get('App\\\\Version')\n#19 /var/azuracast/www/vendor/php-di/invoker/src/ParameterResolver/ResolverChain.php(30): DI\\Invoker\\FactoryParameterResolver->getParameters(Object(ReflectionFunction), Array, Array)\n#20 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(58): Invoker\\ParameterResolver\\ResolverChain->getParameters(Object(ReflectionFunction), Array, Array)\n#21 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(108): Invoker\\Invoker->call(Object(Closure), Array)\n#22 /var/azuracast/www_tmp/CompiledContainer.php(294): DI\\CompiledContainer->resolveFactory(Object(Closure), 'App\\\\Console\\\\App...')\n#23 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(54): CompiledContainer->get16()\n#24 /var/azuracast/www/src/AppFactory.php(43): DI\\CompiledContainer->get('App\\\\Console\\\\App...')\n#25 /var/azuracast/www/bin/console(11): App\\AppFactory::createCli()\n#26 {main}\n  thrown","file":"/var/azuracast/www/src/Service/RedisFactory.php","line":33,"trace":null} []
🖥️🎵－🎶－📻 Waiting...2024-03-24 11:05:44,789 INFO success: php-worker entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-03-24T11:05:44.789694195Z 2024-03-24 11:05:44,789 WARN exited: php-worker (exit status 255; not expected)
🖥️－🎵－🎶📻 Waiting...2024-03-24 11:05:45,790 INFO spawned: 'php-worker' with pid 1948
```

**Comment by nikolaign** [comment]
Same issue after newest update on rolling release channel. This needs to be high priority.

**Comment by BusterNeece** [comment]
I need more logs to be able to diagnose this. If anyone is running into this issue, please run, on the host machine:

```bash
cd /var/azuracast
docker-compose logs -f web
```

I especially want to see what's causing the Redis service not to start correctly on your installations.

**Comment by nikolaign** [comment]
Thanks @BusterNeece for your quick reply! Here is an output of docker-compose logs -f web
[https://pastebin.dmz.rs/?c564386e628e6583#ByMbyci27r2EBxG5iagYPvmfwgvNmxdV9zXagis2vgXY](url)

**Comment by BusterNeece** [comment]
@nikolaign Thank you. What version is your host operating system?

If you're running on an older OS, you may want to try running `./docker.sh install-docker` to update the Docker version. Unfortunately, the logs aren't giving us much information on why the Redis service is failing, but it could be due to an outdated component somewhere further up the stack.

**Comment by nikolaign** [comment]
This was the version of my system - Ubuntu 22.04.3 LTS (GNU/Linux 5.15.0-100-generic x86_64). 
I did a full upgrade on Ubuntu vm. 
Afterward I did a manual update of azuracast via ssh as stated in docs. 

Issue still persists.

**Comment by BusterNeece** [comment]
I've switched our upstream Rolling Release back over to using Redis (just a newer version, the last version that is licensed in such a way that we can use it directly). Please update and let me know if this resolves the issues you're having.

**Comment by benoitcrauet** [comment]
Wow great!
It works!

Maybe adding possibility to install specific older version of Azuracast in case of emergency in `docker.sh`? :-)

Thanks a lot for speed and efficacy! Really.

**Comment by RadioFlamingo** [comment]
I also got the "bad gateway 502" error from nginx when i updated to the latest stable version.
I switched from stable to the rolling release, update again and the error was gone.
