### ISSUE TITLE
Azuracast behaves strangely after trying and failing to play music files

### ISSUE THREAD

**Issue by neosonic2** [AzuraCast/AzuraCast#7094]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.19.7

### What happened?

I installed Azuracast a few months ago and set up one station but didn't really have the time to mess around with it; now I do, so I updated my install to the latest stable release using the "docker.sh update" command, and the update was successful. I then added an Amazon S3 storage location for station media, set it as the default for my station, and uploaded a few music files, all with no issues. My install uses non-standard HTTP and HTTPS ports and sits behind an Nginx reverse proxy so I can host multiple sites on the same server.

However, problems began when I tried to play any of the music I uploaded through the play button on the Music Files page. Nothing happens when I click on it, and clicking on the song name hyperlink just opens a blank browser window with a URL of the form "/api/station/1/file/18/play".

From that point forward, Azuracast begins to exhibit strange behavior such as:

* Showing the name of another user after a few page refreshes, instead of the user account I am logged into
* Showing a "could not complete your request" error (paraphrased) when I click the Edit button next to any music file. The editor dialog still opens, but all fields are blank.
* Sometimes showing the word "false" in the browser window that opens when a music file is clicked on 9see above) instead of a blank window
* Showing a blank screen, the word "false", an Azuracast page with only the header nav menu and footer, or the JSON response of what appears to be an API request when the page is reloaded (see example below)

Example JSON response sometimes seen in browser (one of several, and the actual domain name has been masked):

```
{"page":1,"per_page":10,"total":19,"total_pages":2,"links":{"first":"/api/station/1/files/list?internal=true&rowCount=10&current=1&sortOrder=ASC&currentDirectory=&page=1","previous":"/api/station/1/files/list?internal=true&rowCount=10&current=1&sortOrder=ASC&currentDirectory=&page=1","next":"/api/station/1/files/list?internal=true&rowCount=10&current=1&sortOrder=ASC&currentDirectory=&page=2","last":"/api/station/1/files/list?internal=true&rowCount=10&current=1&sortOrder=ASC&currentDirectory=&page=2"},"rows":[{"path":"five_questions_with__jennifer_cody.mp3","path_short":"five_questions_with__jennifer_cody.mp3","text":" - five questions with  jennifer cody","timestamp":1715204904,"size":7170669,"is_dir":false,"is_cover_art":false,"media":{"id":"b69c3c76002f123bacca1e07bd00ce5e","text":" - five questions with  jennifer cody","artist":"","title":"five questions with  jennifer cody","album":null,"genre":null,"isrc":null,"lyrics":"","art":"/api/station/1/art/dc6b80e350a5dfe3ec622e10","custom_fields":[],"media_id":18,"unique_id":"dc6b80e350a5dfe3ec622e10","art_updated_at":0,"is_playable":true,"length":298,"length_text":"4:58","links":{"play":"https://azuracast.domain.com/api/station/1/file/18/play","edit":"/api/station/1/file/18","art":"/api/station/1/art/18","waveform":"/api/station/1/waveform/dc6b80e350a5dfe3ec622e10-0.json"}},"playlists":[],"links":{"download":"/api/station/1/files/download?file=five_questions_with__jennifer_cody.mp3","rename":"/api/station/1/files/rename?file=five_questions_with__jennifer_cody.mp3"}},{"path":"hispanic_heritage__from_puerto_rico_to_rochester,_salsa_icon_johnny_vega.mp3","path_short":"hispanic_heritage__from_puerto_rico_to_roches...nny_vega.mp3","text":" - hispanic heritage  from puerto rico to rochester, salsa icon johnny vega","timestamp":1715204887,"size":5625031,"is_dir":false,"is_cover_art":false,"media":{"id":"5473fb9d47193e8f38eece85fa42b5f1","text":" - hispanic heritage  from puerto rico to rochester, salsa icon johnny vega","artist":"","title":"hispanic heritage  from puerto rico to rochester, salsa icon johnny vega","album":null,"genre":null,"isrc":null,"lyrics":"","art":"/api/station/1/art/b750bd701c4980f7ea650b4e","custom_fields":[],"media_id":3,"unique_id":"b750bd701c4980f7ea650b4e","art_updated_at":0,"is_playable":true,"length":234,"length_text":"3:54","links":{"play":"https://azuracast.domain.com/api/station/1/file/3/play","edit":"/api/station/1/file/3","art":"/api/station/1/art/3","waveform":"/api/station/1/waveform/b750bd701c4980f7ea650b4e-0.json"}},"playlists":[],"links":{"download":"/api/station/1/files/download?file=hispanic_heritage__from_puerto_rico_to_rochester%2C_salsa_icon_johnny_vega.mp3","rename":"/api/station/1/files/rename?file=hispanic_heritage__from_puerto_rico_to_rochester%2C_salsa_icon_johnny_vega.mp3"}},{"path":"if_i_had_just_one_wish.mp3","path_short":"if_i_had_just_one_wish.mp3","text":" - if i had just one wish","timestamp":1715204900,"size":4049325,"is_dir":false,"is_cover_art":false,"media":{"id":"627a18091852cc4ccca483ab842d706a","text":" - if i had just one wish","artist":"","title":"if i had just one wish","album":null,"genre":null,"isrc":null,"lyrics":"","art":"/api/station/1/art/21c054cb6fb5496221bf89ae","custom_fields":[],"media_id":14,"unique_id":"21c054cb6fb5496221bf89ae","art_updated_at":0,"is_playable":true,"length":168,"length_text":"2:48","links":{"play":"https://azuracast.domain.com/api/station/1/file/14/play","edit":"/api/station/1/file/14","art":"/api/station/1/art/14","waveform":"/api/station/1/waveform/21c054cb6fb5496221bf89ae-0.json"}},"playlists":[],"links":{"download":"/api/station/1/files/download?file=if_i_had_just_one_wish.mp3","rename":"/api/station/1/files/rename?file=if_i_had_just_one_wish.mp3"}},{"path":"jars_of_clay_-_crazy_times_-_1997_gma_dove_awards.mp3","path_short":"jars_of_clay_-_crazy_times_-_1997_gma_dove_awards.mp3","text":"jars of clay - crazy times - 1997 gma dove awards","timestamp":1715204891,"size":5720953,"is_dir":false,"is_cover_art":false,"media":{"id":"c567bf01aa6bff425e640de123dfc654","text":"jars of clay - crazy times - 1997 gma dove awards","artist":"jars of clay","title":"crazy times - 1997 gma dove awards","album":null,"genre":null,"isrc":null,"lyrics":"","art":"/api/station/1/art/dc6b42e747ae85515fcd268f","custom_fields":[],"media_id":6,"unique_id":"dc6b42e747ae85515fcd268f","art_updated_at":0,"is_playable":true,"length":238,"length_text":"3:58","links":{"play":"https://azuracast.domain.com/api/station/1/file/6/play","edit":"/api/station/1/file/6","art":"/api/station/1/art/6","waveform":"/api/station/1/waveform/dc6b42e747ae85515fcd268f-0.json"}},"playlists":[],"links":{"download":"/api/station/1/files/download?file=jars_of_clay_-_crazy_times_-_1997_gma_dove_awards.mp3","rename":"/api/station/1/files/rename?file=jars_of_clay_-_crazy_times_-_1997_gma_dove_awards.mp3"}},{"path":"jars_of_clay_-_disappear_(live).mp3","path_short":"jars_of_clay_-_disappear_(live).mp3","text":"jars of clay - disappear (live)","timestamp":1715204893,"size":5527229,"is_dir":false,"is_cover_art":false,"media":{"id":"5d5ec9201c6b9e7a2d52fd6342571197","text":"jars of clay - disappear (live)","artist":"jars of clay","title":"disappear (live)","album":null,"genre":null,"isrc":null,"lyrics":"","art":"/api/station/1/art/495a31b1038b1e1350c7afe0","custom_fields":[],"media_id":7,"unique_id":"495a31b1038b1e1350c7afe0","art_updated_at":0,"is_playable":true,"length":230,"length_text":"3:50","links":{"play":"https://azuracast.domain.com/api/station/1/file/7/play","edit":"/api/station/1/file/7","art":"/api/station/1/art/7","waveform":"/api/station/1/waveform/495a31b1038b1e1350c7afe0-0.json"}},"playlists":[],"links":{"download":"/api/station/1/files/download?file=jars_of_clay_-_disappear_%28live%29.mp3","rename":"/api/station/1/files/rename?file=jars_of_clay_-_disappear_%28live%29.mp3"}},{"path":"jars_of_clay_-_flood_(original_version).mp3","path_short":"jars_of_clay_-_flood_(original_version).mp3","text":"jars of clay - flood (original version)","timestamp":1715204895,"size":5139117,"is_dir":false,"is_cover_art":false,"media":{"id":"cd7550b9bc34d3ba10e08f2e7261b10d","text":"jars of clay - flood (original version)","artist":"jars of clay","title":"flood (original version)","album":null,"genre":null,"isrc":null,"lyrics":"","art":"/api/station/1/art/688c4ffa8f0acaedc18bdf26","custom_fields":[],"media_id":9,"unique_id":"688c4ffa8f0acaedc18bdf26","art_updated_at":0,"is_playable":true,"length":214,"length_text":"3:34","links":{"play":"https://azuracast.domain.com/api/station/1/file/9/play","edit":"/api/station/1/file/9","art":"/api/station/1/art/9","waveform":"/api/station/1/waveform/688c4ffa8f0acaedc18bdf26-0.json"}},"playlists":[],"links":{"download":"/api/station/1/files/download?file=jars_of_clay_-_flood_%28original_version%29.mp3","rename":"/api/station/1/files/rename?file=jars_of_clay_-_flood_%28original_version%29.mp3"}},{"path":"jars_of_clay_-_liquid_(live).mp3","path_short":"jars_of_clay_-_liquid_(live).mp3","text":"jars of clay - liquid (live)","timestamp":1715204890,"size":5390829,"is_dir":false,"is_cover_art":false,"media":{"id":"5fbc64a8ba8e740fd4db3ea55f7850e4","text":"jars of clay - liquid (live)","artist":"jars of clay","title":"liquid (live)","album":null,"genre":null,"isrc":null,"lyrics":"","art":"/api/station/1/art/743832e6f606d00bd7f83c27","custom_fields":[],"media_id":5,"unique_id":"743832e6f606d00bd7f83c27","art_updated_at":0,"is_playable":true,"length":224,"length_text":"3:44","links":{"play":"https://azuracast.domain.com/api/station/1/file/5/play","edit":"/api/station/1/file/5","art":"/api/station/1/art/5","waveform":"/api/station/1/waveform/743832e6f606d00bd7f83c27-0.json"}},"playlists":[],"links":{"download":"/api/station/1/files/download?file=jars_of_clay_-_liquid_%28live%29.mp3","rename":"/api/station/1/files/rename?file=jars_of_clay_-_liquid_%28live%29.mp3"}},{"path":"jars_of_clay_-_show_you_love.mp3","path_short":"jars_of_clay_-_show_you_love.mp3","text":"jars of clay - show you love","timestamp":1715204894,"size":4587448,"is_dir":false,"is_cover_art":false,"media":{"id":"62a2ed5e6f5c4823bf5b89e9b5c76358","text":"jars of clay - show you love","artist":"jars of clay","title":"show you love","album":null,"genre":null,"isrc":null,"lyrics":"","art":"/api/station/1/art/7fccc9ae9a496b97fb2cadb4","custom_fields":[],"media_id":8,"unique_id":"7fccc9ae9a496b97fb2cadb4","art_updated_at":0,"is_playable":true,"length":191,"length_text":"3:11","links":{"play":"https://azuracast.domain.com/api/station/1/file/8/play","edit":"/api/station/1/file/8","art":"/api/station/1/art/8","waveform":"/api/station/1/waveform/7fccc9ae9a496b97fb2cadb4-0.json"}},"playlists":[],"links":{"download":"/api/station/1/files/download?file=jars_of_clay_-_show_you_love.mp3","rename":"/api/station/1/files/rename?file=jars_of_clay_-_show_you_love.mp3"}},{"path":"jennifer_codydaddys_little_girl_with_darren_bluestone,_kyle_lamar_mitchell,_steven_grant_douglas.mp3","path_short":"jennifer_codydaddys_little_girl_with_darren_b..._douglas.mp3","text":" - jennifer codydaddys little girl with darren bluestone, kyle lamar mitchell, steven grant douglas","timestamp":1715204903,"size":6631895,"is_dir":false,"is_cover_art":false,"media":{"id":"dbb5889bb3a841ce565df1f3c2209e82","text":" - jennifer codydaddys little girl with darren bluestone, kyle lamar mitchell, steven grant douglas","artist":"","title":"jennifer codydaddys little girl with darren bluestone, kyle lamar mitchell, steven grant douglas","album":null,"genre":null,"isrc":null,"lyrics":"","art":"/api/station/1/art/8bbcf1fbb3eba1d24d9669ce","custom_fields":[],"media_id":17,"unique_id":"8bbcf1fbb3eba1d24d9669ce","art_updated_at":0,"is_playable":true,"length":276,"length_text":"4:36","links":{"play":"https://azuracast.domain.com/api/station/1/file/17/play","edit":"/api/station/1/file/17","art":"/api/station/1/art/17","waveform":"/api/station/1/waveform/8bbcf1fbb3eba1d24d9669ce-0.json"}},"playlists":[],"links":{"download":"/api/station/1/files/download?file=jennifer_codydaddys_little_girl_with_darren_bluestone%2C_kyle_lamar_mitchell%2C_steven_grant_douglas.mp3","rename":"/api/station/1/files/rename?file=jennifer_codydaddys_little_girl_with_darren_bluestone%2C_kyle_lamar_mitchell%2C_steven_grant_douglas.mp3"}},{"path":"john_ellison_and_the_soul_brothers_six_-_dazz_(funk)_(soul)_(1976).mp3","path_short":"john_ellison_and_the_soul_brothers_six_-_dazz...)_(1976).mp3","text":"john ellison and the soul brothers six - dazz (funk) (soul) (1976)","timestamp":1715204898,"size":4801861,"is_dir":false,"is_cover_art":false,"media":{"id":"f15654b187619673a3548d61cbbd8298","text":"john ellison and the soul brothers six - dazz (funk) (soul) (1976)","artist":"john ellison and the soul brothers six","title":"dazz (funk) (soul) (1976)","album":null,"genre":null,"isrc":null,"lyrics":"","art":"/api/station/1/art/48fe3ab4a0735eb1b41c51ab","custom_fields":[],"media_id":12,"unique_id":"48fe3ab4a0735eb1b41c51ab","art_updated_at":0,"is_playable":true,"length":200,"length_text":"3:20","links":{"play":"https://azuracast.domain.com/api/station/1/file/12/play","edit":"/api/station/1/file/12","art":"/api/station/1/art/12","waveform":"/api/station/1/waveform/48fe3ab4a0735eb1b41c51ab-0.json"}},"playlists":[],"links":{"download":"/api/station/1/files/download?file=john_ellison_and_the_soul_brothers_six_-_dazz_%28funk%29_%28soul%29_%281976%29.mp3","rename":"/api/station/1/files/rename?file=john_ellison_and_the_soul_brothers_six_-_dazz_%28funk%29_%28soul%29_%281976%29.mp3"}}]}
```

I suspect based on the symptoms that this is some kind of caching issue but I don't know enough about Azuracast to prove this theory, and the logs are of no assistance as they don't show any errors related to what I'm experiencing.

Here is my Nginx reverse proxy configuration:

```
	location / {
		proxy_pass http://127.0.0.1:8080/;
		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection Upgrade;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header X-Forwarded-Scheme $scheme;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header Host $host;
		proxy_cache off;
	}
```

Any assistance that could be provided here would be greatly appreciated. I like Azuracast so far but these issues are making it practically unusable for me at the moment.

### Relevant log output

```
azuracast          | {"level":"warn","ts":1715436985379396160,"logger":"server","msg":"soft worker error, worker won't be restarted","reason":"SoftJob","pid":24725,"internal_event_name":"EventWorkerSoftError","error":"sync_worker_receive_frame: SoftJobError: RuntimeException: Stream is not seekable in /var/azuracast/www/vendor/guzzlehttp/psr7/src/Stream.php:209\nStack trace:\n#0 /var/azuracast/www/vendor/guzzlehttp/psr7/src/Stream.php(198): GuzzleHttp\\Psr7\\Stream->seek(0)\n#1 /var/azuracast/www/vendor/spiral/roadrunner-http/src/PSR7Worker.php(99): GuzzleHttp\\Psr7\\Stream->rewind()\n#2 [internal function]: Spiral\\RoadRunner\\Http\\PSR7Worker->streamToGenerator(Object(GuzzleHttp\\Psr7\\Stream))\n#3 /var/azuracast/www/vendor/spiral/roadrunner-http/src/HttpWorker.php(111): Generator->valid()\n#4 /var/azuracast/www/vendor/spiral/roadrunner-http/src/HttpWorker.php(93): Spiral\\RoadRunner\\Http\\HttpWorker->respondStream(200, Object(Generator), Array, true)\n#5 /var/azuracast/www/vendor/spiral/roadrunner-http/src/PSR7Worker.php(84): Spiral\\RoadRunner\\Http\\HttpWorker->respond(200, Object(Generator), Array)\n#6 /var/azuracast/www/util/rr_http_worker.php(41): Spiral\\RoadRunner\\Http\\PSR7Worker->respond(Object(App\\Http\\Response))\n#7 {main}"}
azuracast          | {"level":"error","ts":1715436985379685516,"logger":"http","msg":"execute","start":1715436985377506780,"elapsed":0.002169885,"error":"sync_worker_receive_frame: SoftJobError: RuntimeException: Stream is not seekable in /var/azuracast/www/vendor/guzzlehttp/psr7/src/Stream.php:209\nStack trace:\n#0 /var/azuracast/www/vendor/guzzlehttp/psr7/src/Stream.php(198): GuzzleHttp\\Psr7\\Stream->seek(0)\n#1 /var/azuracast/www/vendor/spiral/roadrunner-http/src/PSR7Worker.php(99): GuzzleHttp\\Psr7\\Stream->rewind()\n#2 [internal function]: Spiral\\RoadRunner\\Http\\PSR7Worker->streamToGenerator(Object(GuzzleHttp\\Psr7\\Stream))\n#3 /var/azuracast/www/vendor/spiral/roadrunner-http/src/HttpWorker.php(111): Generator->valid()\n#4 /var/azuracast/www/vendor/spiral/roadrunner-http/src/HttpWorker.php(93): Spiral\\RoadRunner\\Http\\HttpWorker->respondStream(200, Object(Generator), Array, true)\n#5 /var/azuracast/www/vendor/spiral/roadrunner-http/src/PSR7Worker.php(84): Spiral\\RoadRunner\\Http\\HttpWorker->respond(200, Object(Generator), Array)\n#6 /var/azuracast/www/util/rr_http_worker.php(41): Spiral\\RoadRunner\\Http\\PSR7Worker->respond(Object(App\\Http\\Response))\n#7 {main}"}
```

**Comment by gAlleb** [comment]
Hi @neosonic2! I'm using Asuracast with nginx proxy too and have no problems at all.

Maybe you could try this config - this should help:

```ruby
 location / {
            proxy_pass                         https://127.0.0.1:8080;
            # Websocket 
            proxy_http_version                 1.1;
            proxy_cache_bypass                 $http_upgrade;
            proxy_set_header Upgrade           $http_upgrade;
            proxy_set_header Connection        "upgrade";

            # Proxy headers
            proxy_set_header Host              $host;
            proxy_set_header X-Real-IP         $remote_addr;
            proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Host  $host;
            proxy_set_header X-Forwarded-Port  $server_port;
            proxy_set_header X-Forwarded-Scheme $scheme;
            proxy_set_header Accept-Encoding "";

            # Proxy timeouts
            proxy_connect_timeout              2400s;
            proxy_send_timeout                 60s;
            proxy_read_timeout                 60s;

            proxy_buffering           off;
            proxy_ignore_client_abort off;
        }
```

**Comment by neosonic2** [comment]
Hi @gAlleb, thanks for your configuration but unfortunately that didn't solve my issue. I see the same behaviors even after applying it and restarting Nginx and Azuracast. I did have to modify your config slightly because my instance of Azuracast is litening on HTTP only on port 8080, and does not have HTTPS set up because Nginx terminates SSL (before proxying the connection to the service).

I wonder if this is related to a caching issue; seeing details of a different user account (other than my own) after a few page refreshes leads me to believe I'm seeing cached data from other users that I shouldn't be seeing, but I don't know enough of how Azuracast works to investigate this angle more thorougly. I'm using built-in Redis caching and have not touched that part of the Azuracast configuration.

**Comment by neosonic2** [comment]
I think I may have found the cause of the issue but am not sure what its solution is. Whenever I try to click the play button or the name hyperlink of a song I've uploaded to Azuracast and which is stored in the Amazon S3 bucket, the following shows up in the logs (along with all the other symptoms I mentioned above):

```
azuracast          | {"level":"warn","ts":1715436985379396160,"logger":"server","msg":"soft worker error, worker won't be restarted","reason":"SoftJob","pid":24725,"internal_event_name":"EventWorkerSoftError","error":"sync_worker_receive_frame: SoftJobError: RuntimeException: Stream is not seekable in /var/azuracast/www/vendor/guzzlehttp/psr7/src/Stream.php:209\nStack trace:\n#0 /var/azuracast/www/vendor/guzzlehttp/psr7/src/Stream.php(198): GuzzleHttp\\Psr7\\Stream->seek(0)\n#1 /var/azuracast/www/vendor/spiral/roadrunner-http/src/PSR7Worker.php(99): GuzzleHttp\\Psr7\\Stream->rewind()\n#2 [internal function]: Spiral\\RoadRunner\\Http\\PSR7Worker->streamToGenerator(Object(GuzzleHttp\\Psr7\\Stream))\n#3 /var/azuracast/www/vendor/spiral/roadrunner-http/src/HttpWorker.php(111): Generator->valid()\n#4 /var/azuracast/www/vendor/spiral/roadrunner-http/src/HttpWorker.php(93): Spiral\\RoadRunner\\Http\\HttpWorker->respondStream(200, Object(Generator), Array, true)\n#5 /var/azuracast/www/vendor/spiral/roadrunner-http/src/PSR7Worker.php(84): Spiral\\RoadRunner\\Http\\HttpWorker->respond(200, Object(Generator), Array)\n#6 /var/azuracast/www/util/rr_http_worker.php(41): Spiral\\RoadRunner\\Http\\PSR7Worker->respond(Object(App\\Http\\Response))\n#7 {main}"}
azuracast          | {"level":"error","ts":1715436985379685516,"logger":"http","msg":"execute","start":1715436985377506780,"elapsed":0.002169885,"error":"sync_worker_receive_frame: SoftJobError: RuntimeException: Stream is not seekable in /var/azuracast/www/vendor/guzzlehttp/psr7/src/Stream.php:209\nStack trace:\n#0 /var/azuracast/www/vendor/guzzlehttp/psr7/src/Stream.php(198): GuzzleHttp\\Psr7\\Stream->seek(0)\n#1 /var/azuracast/www/vendor/spiral/roadrunner-http/src/PSR7Worker.php(99): GuzzleHttp\\Psr7\\Stream->rewind()\n#2 [internal function]: Spiral\\RoadRunner\\Http\\PSR7Worker->streamToGenerator(Object(GuzzleHttp\\Psr7\\Stream))\n#3 /var/azuracast/www/vendor/spiral/roadrunner-http/src/HttpWorker.php(111): Generator->valid()\n#4 /var/azuracast/www/vendor/spiral/roadrunner-http/src/HttpWorker.php(93): Spiral\\RoadRunner\\Http\\HttpWorker->respondStream(200, Object(Generator), Array, true)\n#5 /var/azuracast/www/vendor/spiral/roadrunner-http/src/PSR7Worker.php(84): Spiral\\RoadRunner\\Http\\HttpWorker->respond(200, Object(Generator), Array)\n#6 /var/azuracast/www/util/rr_http_worker.php(41): Spiral\\RoadRunner\\Http\\PSR7Worker->respond(Object(App\\Http\\Response))\n#7 {main}"}
```

Note this issue occurs when using Wasabi as an S3 provider as well, but does not occur when using a local storage location; in that case everything works as expected. If anyone has any insight into this,  please feel free to contribute.

**Comment by neosonic2** [comment]
Thank you so much - I think we’re much closer to a solution now. I switched to the rolling release channel and updated, and now when I click to play any uploaded music, the browser gives an error because the URL is https://azuracast.domain.com:8080/api/station/1/file/73/play (domain obfuscated) instead of https://azuracast.domain.com/api/station/1/file/73/play (since https://azuracast.domain.com <https://azuracast.domain.com/> is what’s set in my system settings). 

If I load https://azuracast.domain.com/api/station/1/file/73/play directly, the browser prompts me to download the audio file just as it should.

Port 8080 is what Azuracast HTTP is listening on but I’m proxying requests through Nginx as originally mentioned to hide the port number. I have “Prefer browser URL” turned on but the issue occurs even if it’s turned off.

**Comment by neosonic2** [comment]
Actually I take that back - turning off “Prefer browser URL” fixes the problem and now the media plays and downloads as it should on the latest rolling release channel update.

**Comment by BusterNeece** [comment]
@neosonic2 Excellent. I'll go ahead and close this issue for now assuming this is fixed in the latest Rolling channel; if you run into any such issues in the future feel free to reopen.
